<div id="auth-login-box" class="login-box visible widget-box no-border">

    <div class="widget-header">
        <div class="widget-toolbar no-border pull-left">
            <ul class="nav nav-tabs" id="auth-tab">
                <li class="active">
                <a data-toggle="tab" href="#auth-tab-register"><?=$this->tag->_('New User');?></a>
                </li>
                <li>
                <a data-toggle="tab" href="#auth-tab-bind"><?=$this->tag->_('Already Have an Account');?></a>
                </li>
            </ul>
        </div>
    </div>


    <div class="widget-body">
        <div class="widget-main">
            <div class="tab-content">
                <div id="auth-tab-register" class="tab-pane in active">

                    <h4 class="header blue lighter bigger">
                        <?if($token && isset($token['remoteImageUrl'])):?>
                        <img alt="" src="<?=$token['remoteImageUrl']?>" width="30" height="30" class="nav-user-photo">
                        <?else:?>
                        <i class="icon-coffee green"></i>
                        <?endif?>
                        <?=$this->tag->_('Register and Connect');?> 
                    </h4>

                    <div class="space-6"></div>


                    <form action="/auth/register" method="POST">
                        <fieldset>
                            <div class="form-group">
                                <label class="block clearfix">
                                    <span class="block input-icon input-icon-right">
                                        <input type="email" name="email" class="form-control" placeholder="<?=$this->tag->_('Email');?>" data-parsley-trigger="blur change" data-parsley-remote="/admin/register/check" data-parsley-remote-options='{ method: "GET", dataType: "json"}' data-parsley-remote-message="<?=$this->tag->_('This email has been taken');?>"  value="<?=isset($suggestEmail) ? $suggestEmail: ''?>" required />
                                        <i class="icon-envelope"></i>
                                    </span>
                                </label>
                            </div>

                            <div class="form-group">
                                <label class="block clearfix">
                                    <span class="block input-icon input-icon-right">
                                        <input type="text" name="username" class="form-control" placeholder="<?=$this->tag->_('Username');?>"
                                        value="<?=isset($suggestUsername) ? $suggestUsername : ''?>"
                                        data-parsley-trigger="blur change"
                                        data-parsley-type="alphanum"
                                        data-parsley-minlength="4"
                                        data-parsley-maxlength="24"
                                        data-parsley-pattern="^(?![0-9]+$)"
                                        data-parsley-pattern-message="<?=$this->tag->_('Username not allow pure digits');?>"
                                        data-parsley-remote="/admin/register/check"
                                        data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                        data-parsley-remote-message="<?=$this->tag->_('This username has been taken');?>"
                                        required />
                                        <i class="icon-user"></i>
                                    </span>
                                </label>
                            </div>

                            <div class="social-or-login">
                                <span class="bigger-110">
                                    <?=isset($token['remoteUserName']) && $token['remoteUserName'] ? $token['remoteUserName'] . ', ' : (isset($token['remoteNickName']) && $token['remoteNickName'] ? $token['remoteNickName'] . ', ' : '') ?>
                                    <?=$this->tag->_('You are connecting with');?> <?=$token['adapterKey']?></span>
                            </div>

                            <div class="space"></div>

                            <div class="clearfix">

                                <button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
                                    <i class="icon-exchange"></i>
                                    <?=$this->tag->_('Register');?> 
                                </button>
                            </div>

                            <div class="space-4"></div>
                        </fieldset>
                    </form>


                </div><!-- /#auth-tab-register -->


                <div id="auth-tab-bind" class="tab-pane">
                    <h4 class="header blue lighter bigger">
                        <?if($token && isset($token['remoteImageUrl'])):?>
                        <img alt="" src="<?=$token['remoteImageUrl']?>" width="30" height="30" class="nav-user-photo">
                        <?else:?>
                        <i class="icon-coffee green"></i>
                        <?endif?>
                        <?=$this->tag->_('Login and Connect');?> 
                    </h4>

                    <div class="space-6"></div>


                    <form action="/auth/login" method="POST">
                        <fieldset>
                            <div class="form-group">
                                <label class="block clearfix">
                                    <span class="block input-icon input-icon-right">
                                        <input type="text" name="identify" class="form-control" placeholder="<?=$this->tag->_('Username or Email');?>" data-parsley-minlength="4" required />
                                        <i class="icon-user"></i>
                                    </span>
                                </label>
                            </div>

                            <div class="form-group">
                                <label class="block clearfix">
                                    <span class="block input-icon input-icon-right">
                                        <input type="password" name="password" class="form-control" placeholder="<?=$this->tag->_('Password');?>" data-parsley-minlength="6"  data-parsley-maxlength="26" required />
                                        <i class="icon-lock"></i>
                                    </span>
                                </label>
                            </div>


                            <div class="social-or-login">
                                <span class="bigger-110">
                                    <?=$this->tag->_('Your %adapterKey% account will be connected after login', array(
                                        'adapterKey' => $token['adapterKey'],
                                    ))?>
                                </span>
                            </div>

                            <div class="space"></div>

                            <div class="clearfix">

                                <button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
                                    <i class="icon-exchange"></i>
                                    <?=$this->tag->_('Login');?> 
                                </button>
                            </div>

                            <div class="space-4"></div>
                        </fieldset>
                    </form>

                </div><!-- /#auth-tab-login -->
            </div><!-- /tab-content -->
        </div><!-- /widget-main -->

        <div class="toolbar clearfix">
            <div>
                <a href="/admin" class="forgot-password-link">
                    <i class="icon-arrow-left"></i>
                    <?=$this->tag->_('Login With Password');?> 
                </a>
            </div>
        </div>

    </div><!-- /widget-body -->
</div><!-- /login-box -->
