<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/post" class="active">Post List</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
                Post List
                <a href="/admin/post/create" class="btn btn-sm"><i class="icon-pencil align-top bigger-125"></i> Write New</a>
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> Posts 
            </div>

            <div class="table-responsive dataTables_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-inline">
                            <div class="form-group">
                                <input type="text" name="q" placeholder="Keyword" class="input-small">
                            </div>
                            <span>
                                <label for="filter-from-limit">Display</label> 
                            </span>
                            <div class="form-group">
                                <select id="filter-from-limit" size="1" name="limit"><option selected="selected" value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select>
                            </div>
                            <button class="btn btn-info btn-sm" type="submit">
                                <i class="icon-key bigger-110"></i>
                                Filter 
                            </button>
                        </form>

                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-1">
                    <thead>
                        <tr>
                            <th class="center">
                                <label>
                                    <input type="checkbox" class="ace">
                                    <span class="lbl"></span>
                                </label>
                            </th>
                            <th class="hidden-480">ID</th>
                            <th>Title</th>
                            <th class="hidden-480">Status</th>
                            <th>User</th>
                            <th>
                                <i class="icon-time bigger-110 hidden-480"></i>
                                Update
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        <?foreach($pager->items as $item):?>
                        <tr>
                            <td class="center">
                                <label>
                                    <input type="checkbox" class="ace" value="<?=$item->id?>">
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td class="hidden-480"><?=$item->id?></td>
                            <td>
                                <a href="/admin/post/edit/<?=$item->id?>"><?=$item->title?></a>
                            </td>
                            <td class="hidden-480">
                                <?$status = array(
                                    'draft' => 'label-info',
                                    'pending' => 'label-warning',
                                    'deleted' => 'label',
                                    'published' => 'label-success',
                                )?>
                                <span class="label label-sm <?=$status[$item->status]?>"><?=$item->status?></span>
                            </td>
                            <td><?=$item->User->username?></td>
                            <td><?=$this->tag->datetime($item->createdAt)?></td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-xs btn-success ajax-form-sumbit" data-ajax-form="1" date-method="put" data-form-action="/admin/post/status/<?=$item->id?>" data-callback="window.location.reload();">
                                        <input type="hidden" data-name="status" value="published" >
                                        <i class="icon-ok bigger-120"></i>
                                    </button>

                                    <a class="btn btn-xs btn-info" href="/admin/post/edit/<?=$item->id?>">
                                        <i class="icon-edit bigger-120"></i>
                                    </a>

                                    <button class="btn btn-xs btn-warning ajax-form-sumbit" data-ajax-form="1" date-method="put" data-form-action="/admin/post/status/<?=$item->id?>" data-callback="window.location.reload();">
                                        <input type="hidden" data-name="status" value="pending" >
                                        <i class="icon-eye-close bigger-120"></i>
                                    </button>

                                    <button class="btn btn-xs btn-danger ajax-form-sumbit" data-ajax-form="1" date-method="delete" data-form-action="/admin/post/delete/<?=$item->id?>" data-confirm="1" data-confirm-message="<?=sprintf('Item %s will be deleted, are you sure?', $item->title)?>" data-callback="form.closest('tr').hide();">
                                        <i class="icon-trash bigger-120"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6">
                        <span class="ui-pg-button ui-corner-all" title="" id="del_grid-table" data-original-title="Delete selected row"><div class="ui-pg-div"><span class="ui-icon icon-trash red"></span></div></span>
                    </div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/post',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->

        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->
