<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("eva_user_users/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("eva_user_users/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Status</th>
            <th>Flag</th>
            <th>ScreenName</th>
            <th>Salt</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Password</th>
            <th>OldPassword</th>
            <th>LastUpdateTime</th>
            <th>Gender</th>
            <th>Avatar</th>
            <th>Avatar</th>
            <th>Timezone</th>
            <th>RegisterTime</th>
            <th>LastLoginTime</th>
            <th>Language</th>
            <th>Setting</th>
            <th>InviteUserId</th>
            <th>OnlineStatus</th>
            <th>LastFreshTime</th>
            <th>ViewCount</th>
            <th>RegisterIp</th>
            <th>LastLoginIp</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $eva_user_user) { ?>
        <tr>
            <td><?php echo $eva_user_user->id ?></td>
            <td><?php echo $eva_user_user->username ?></td>
            <td><?php echo $eva_user_user->email ?></td>
            <td><?php echo $eva_user_user->mobile ?></td>
            <td><?php echo $eva_user_user->status ?></td>
            <td><?php echo $eva_user_user->flag ?></td>
            <td><?php echo $eva_user_user->screenName ?></td>
            <td><?php echo $eva_user_user->salt ?></td>
            <td><?php echo $eva_user_user->firstName ?></td>
            <td><?php echo $eva_user_user->lastName ?></td>
            <td><?php echo $eva_user_user->password ?></td>
            <td><?php echo $eva_user_user->oldPassword ?></td>
            <td><?php echo $eva_user_user->lastUpdateTime ?></td>
            <td><?php echo $eva_user_user->gender ?></td>
            <td><?php echo $eva_user_user->avatar_id ?></td>
            <td><?php echo $eva_user_user->avatar ?></td>
            <td><?php echo $eva_user_user->timezone ?></td>
            <td><?php echo $eva_user_user->registerTime ?></td>
            <td><?php echo $eva_user_user->lastLoginTime ?></td>
            <td><?php echo $eva_user_user->language ?></td>
            <td><?php echo $eva_user_user->setting ?></td>
            <td><?php echo $eva_user_user->inviteUserId ?></td>
            <td><?php echo $eva_user_user->onlineStatus ?></td>
            <td><?php echo $eva_user_user->lastFreshTime ?></td>
            <td><?php echo $eva_user_user->viewCount ?></td>
            <td><?php echo $eva_user_user->registerIp ?></td>
            <td><?php echo $eva_user_user->lastLoginIp ?></td>
            <td><?php echo $this->tag->linkTo(array("eva_user_users/edit/" . $eva_user_user->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("eva_user_users/delete/" . $eva_user_user->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("eva_user_users/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("eva_user_users/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("eva_user_users/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("eva_user_users/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
