<div class="row">
    <div class="span9">

        <div id="main">

            <div class="row">

                <div class="span">
                    <div class="topnews view">
                        <ul class="topnews carousel">
                            <li class="item">
                            <a class="link" href="">
                                <img class="img" src="img/img01.png" alt=""/>
                                <h3 class="title">央行今日在施600亿元正回购操作，本周净回笼1080亿元流行</h3>
                            </a>
                            </li>
                        </ul>
                        <ul class="topnews list">
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link active" href="">测试连接sdf，。lk测试1254超长  超长，哈哈哈哈哈哈哈哈哈哈哈,he呵呵呵</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                            <li class="item"><a class="link" href="">测试连接sdf，。lk测试1254</a></li>
                        </ul>
                    </div>
                </div><!--span end -->

                <div class="span">

                    <div class="market chart tabpanel type4">
                        <ul class="tabbar">
                            <li class="tab"><a class="link active" href="">黄金</a></li>
                            <li class="tab"><a class="link" href="">白银</a></li>
                            <li class="tab"><a class="link" href="">美元指数</a></li>
                            <li class="tab"><a class="link" href="">标普500</a></li>
                            <li class="tab"><a class="link" href="">石油</a></li>

                            <button class="button" data-toggle="stare-modal">盯盘模式</button>
                        </ul>
                        <ul class="content">
                            <li class="panel active">
                            <div class="toolbar">
                                <div class="button">1</div>
                                <div class="button">5</div>
                                <div class="button">15</div>
                                <div class="button active">30</div>
                                <div class="button">1H</div>
                                <div class="button">4H</div>
                                <div class="button">1D</div>
                                <div class="button">1W</div>
                                <div class="button">1M</div>
                            </div>
                            </li>
                            <li class="panel"></li>
                            <li class="panel"></li>
                            <li class="panel"></li>
                            <li class="panel"></li>
                        </ul>
                    </div>

                    <h2 class="main-title">实时新闻</h2>
                    <ul class="livenews list">

                        <li class="item">
                        <h3 class="date">2014年02月21日</h3>
                        <ul class="dropdown list">
                            <li class="livenews item">
                            <span class="icon"></span>
                            <span class="time">09:30</span>
                            <a class="link" href="">测试连接sdf，。lk测试1254超长</a>
                            </li>
                            <li class="livenews item">
                            <span class="icon"></span>
                            <span class="time">10:20</span>
                            <a class="link" href="">测试连接sdf，。lk测试1254超长  超长，哈哈哈哈哈哈哈哈哈哈哈,he呵呵呵</a>
                            </li>
                        </ul>
                        </li>
                        <li class="item">
                        <h3 class="date">2014年02月21日</h3>
                        <ul class="dropdown list">
                            <li class="livenews item">
                            <span class="icon"></span>
                            <span class="time">09:30</span>
                            <a class="link" href="">测试连接sdf，。lk测试1254超长</a>
                            </li>
                            <li class="livenews item">
                            <span class="icon"></span>
                            <span class="time">10:20</span>
                            <a class="link" href="">测试连接sdf，。lk测试1254超长  超长，哈哈哈哈哈哈哈哈哈哈哈,he呵呵呵wer换行？是否</a>
                            </li>
                        </ul>
                        </li>
                        <li class="item">
                        <h3 class="date">2014年02月21日</h3>
                        <ul class="dropdown list">
                            <li class="livenews item">
                            <span class="icon"></span>
                            <span class="time">09:30</span>
                            <a class="link" href="">测试连接sdf，。lk测试1254超长</a>
                            </li>
                            <li class="livenews item">
                            <span class="icon"></span>
                            <span class="time">10:20</span>
                            <a class="link" href="">测试连接sdf，。lk测试1254超长  超长，哈哈哈哈哈哈哈哈哈哈哈,he呵呵呵</a>
                            </li>
                        </ul>
                        </li>
                    </ul>

                </div><!--span end -->

            </div><!-- row end -->

            <div class="row">
                <h2 class="main-title">技术分析</h2>

                <div class="tabpanel type5 market-analysis">
                    <ul class="tabbar">
                        <li class="tab">
                        <a class="link active" href="">黄金</a>
                        </li>
                        <li class="tab">
                        <a class="link" href="">白银</a>
                        </li>
                        <li class="tab">
                        <a class="link" href="">美元指数</a>
                        </li>
                        <li class="tab">
                        <a class="link" href="">美债</a>
                        </li>
                        <li class="tab">
                        <a class="link" href="">原油</a>
                        </li>
                        <li class="tab">
                        <a class="link" href="">美国标股500</a>
                        </li>
                        <li class="tab">
                        <a class="link" href="">日经</a>
                        </li>
                    </ul>
                    <ul class="content">
                        <li class="panel active row">
                        <div class="span overview-data">
                            <span class="update-time">更新时间：</span>
                            <span class="close-price">昨收：</span>
                            <span class="open-price">今开：</span>
                            <h3 class="title">黄金：<span class="price"></span></h3>
                            <h3 class="advice">建议：<span class="text"></span></h3>
                            <div class="compare">
                                <h3 class="title">多空对比</h3>
                                <div class="row">
                                    <div class="bearish span left text-left">
                                        <span class="value">75%</span>
                                        <span class="label">看空</span>
                                    </div>
                                    <div class="bullish span right text-right">
                                        <span class="value">25%</span>
                                        <span class="label">看多</span>
                                    </div>
                                </div>
                                <div class="row indicator">
                                    <span class="span bearish" style="width: 75%;"></span>
                                    <span class="span bullish" style="width: 25%;"></span>
                                </div>
                            </div>
                        </div>
                        <div class="span realtime-data">
                            <div class="tabpanel type1">
                                <ul class="tabbar">
                                    <li class="label">时间范围：</li>
                                    <li class="tab"><a class="link" href="">5分钟</a></li>
                                    <li class="tab"><a class="link active" href="">15分钟</a></li>
                                    <li class="tab"><a class="link" href="">每小时</a></li>
                                    <li class="tab"><a class="link" href="">每日</a></li>
                                </ul>
                                <ul class="content">
                                    <li class="panel"></li>
                                    <li class="panel active">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="cell1">S3</th>
                                                <th class="cell1">S2</th>
                                                <th class="cell1">S1</th>
                                                <th class="pivot">枢轴点</th>
                                                <th class="cell1">R1</th>
                                                <th class="cell1">R2</th>
                                                <th class="cell1">R3</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td class="cell1">22600.35</td>
                                                <td class="cell1">22701.54</td>
                                                <td class="cell1">22701.54</td>
                                                <td class="pivot">22703.67</td>
                                                <td class="cell1">23701.54</td>
                                                <td class="cell1">23721.69</td>
                                                <td class="cell1">23901.04</td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    <span class="dash-line"></span>

                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                <td class="label">移动平均指数：</td>
                                                <td class="cell2">
                                                    <a class="link buy"  href="#">购买<span class="value">(6)</span></a>
                                                </td>
                                                <td class="cell2">
                                                    <a class="link sell" href="#">出售<span class="value">(3)</span></a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">指标：</td>
                                                <td class="cell2">
                                                    <a class="link buy"  href="#">购买<span class="value">(6)</span></a>
                                                </td>
                                                <td class="cell2">
                                                    <a class="link sell" href="#">出售<span class="value">(3)</span></a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    </li>
                                    <li class="panel"></li>
                                    <li class="panel"></li>
                                </ul>
                            </div>
                        </div>
                        </li>
                        <li class="panel"></li>
                        <li class="panel"></li>
                    </ul>
                </div>

            </div><!-- row end -->

            <div class="row">
                <div class="span left">
                    <h2 class="main-title">机构金评</h2>
                    <div class="economic-evaluation tabpanel type2">
                        <ul class="tabbar">
                            <li class="tab"><a class="link active" href="">黄金</a></li>
                            <li class="tab"><a class="link " href="">白银</a></li>
                            <li class="tab"><a class="link " href="">布油</a></li>
                            <li class="tab"><a class="link " href="">美元指数</a></li>
                        </ul>
                        <ul class="content">
                            <li class="panel active">
                            <ul class="economic-evaluation list">
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                                <li class="item">
                                <a class="link row" href="">
                                    <span class="span title">测试长度随机是uzu文字和诉讼对方是否发送方式地方</span>
                                    <span class="span author">詹姆斯蒂芬</span>
                                    <span class="span time">22/41/2014</span>
                                </a>
                                </li>
                            </ul>
                            </li>
                            <li class="panel "></li>
                            <li class="panel "></li>
                            <li class="panel "></li>
                        </ul>
                    </div>
                </div>
                <div class="span right">
                    <h2 class="main-title">投资教程</h2>
                    <ul class="investment-tutorial list">
                        <li class="item">
                        <a class="link row" href="">
                            <span class="span index">1</span>
                            <span class="span title">基础知识</span>
                        </a>
                        </li>
                        <li class="item">
                        <a class="link row" href="">
                            <span class="span index">2</span>
                            <span class="span title">投资介绍</span>
                        </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div><!--main end -->
    </div><!--span9 end -->
    <div id="sidebar" class="span3" >
        <h2 class="title">财经日历</h2>
        <ul class="finance-calendar list">
            <li class="item">
            <span class="time">05:45am</span>
            <a class="link" href="">日本第一季度GDP平均指数初值</a>
            <span class="meta">
                <span class="label">今值：</span>
                <span class="value">4.123%</span>
            </span>
            <span class="meta">
                <span class="label">预测：</span>
                <span class="value">-1.40B</span>
            </span>
            <span class="meta">
                <span class="label">前值：</span>
                <span class="value">2.394%</span>
            </span>
            </li>
            <li class="item">
            <span class="time">05:45am</span>
            <a class="link" href="">日本第一季度GDP平均指数初值,诶，说好的换行呢</a>
            <span class="meta">
                <span class="label">今值：</span>
                <span class="value">4.123%</span>
            </span>
            <span class="meta">
                <span class="label">预测：</span>
                <span class="value">-1.40B</span>
            </span>
            <span class="meta">
                <span class="label">前值：</span>
                <span class="value">2.394%</span>
            </span>
            </li>
            <li class="item">
            <span class="time">05:45am</span>
            <a class="link" href="">日本第一季度GDP平均指数初值</a>
            <span class="meta">
                <span class="label">今值：</span>
                <span class="value">4.123%</span>
            </span>
            <span class="meta">
                <span class="label">预测：</span>
                <span class="value">-1.40B</span>
            </span>
            <span class="meta">
                <span class="label">前值：</span>
                <span class="value">2.394%</span>
            </span>
            </li>
            <li class="item">
            <span class="time">05:45am</span>
            <a class="link" href="">日本第一季度GDP平均指数初值</a>
            <span class="meta">
                <span class="label">今值：</span>
                <span class="value">4.123%</span>
            </span>
            <span class="meta">
                <span class="label">预测：</span>
                <span class="value">-1.40B</span>
            </span>
            <span class="meta">
                <span class="label">前值：</span>
                <span class="value">2.394%</span>
            </span>
            </li>
        </ul>
        <div class="line type1"></div>
        <h2 class="title">黄金多空调查</h2>
        <div class="line type1"></div>
        <div id="gold-research">
            <div class="chart type1">

            </div>
            <div class="row">
                <div class="span4"><button class="button type1 pink">上涨</button></div>
                <div class="span4"><button class="button type1 gray">盘整</button></div>
                <div class="span4"><button class="button type1 green">下跌</button></div>
            </div>
        </div>
        <div class="line type1"></div>
        <h2 class="title">黄金兑换器</h2>
        <div class="line type1"></div>
        <form id="" class="form type1" action="">
            <div class="row">
                <div class="span6">
                    <input type="text" name=""/>
                </div>
                <div class="span6">
                    <select name="">
                        <option value ="rmb">人民币/克</option>
                        <option value ="usd">美元/盎司</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <input type="text" name=""/>
                </div>
                <div class="span6">
                    <select name="">
                        <option value ="">美元/盎司</option>
                        <option value ="">人民币/克</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <label for="">基于市场即时价格</label>
                </div>
                <div class="span6">
                    <button class="button" type="submit">计算</button>
                </div>
            </div>
        </form>
        <div class="line type1"></div>
        <div class="tabpanel type3">
            <ul class="tabbar">
                <li class="tab"><a class="link active" href="">ETF持仓</a></li>
                <li class="tab"><a class="link" href="">CFTC持仓</a></li>
                <li class="tab"><a class="link" href="">定盘价</a></li>
            </ul>
            <ul class="content">
                <li class="panel active">
                <div class="chart type2">

                </div>
                <div class="line type1"></div>
                <table class="table type2">
                    <thead>
                        <tr>
                            <th>时间</th>
                            <th>增仓量(吨)</th>
                            <th>增减(吨)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>2014.03.04</td>
                            <td>803.70398</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.03</td>
                            <td>804.00120</td>
                            <td>0.03</td>
                        </tr>
                        <tr>
                            <td>2014.03.02</td>
                            <td>803.70398</td>
                            <td>0.10</td>
                        </tr>
                    </tbody>
                </table>
                </li>
                <li class="panel"></li>
                <li class="panel"></li>
            </ul>
        </div>
    </div>
</div>
