<div class="row relative">
    <div class="span8">
        <div id="main">
            <div class="article page">
                <h2 class="title">路透：香港金管局要求银行收紧对中国内地企业的贷款</h2>
                <div class="info">
                    <span class="item author">James.Nga</span>
                    <span class="item time">2014年03月28日 14:12</span>
                    <span class="item tag">香港金融业/影子银行/铜融资</span>
                    <span class="item view-times">21256</span>
                    <span class="item source right">来源：华尔街见闻</span>
                </div>
                <div class="summary">
                    摘要：据国际清算银行（BIS）数据显示，外资银行在华（大陆）债权去年已达1万亿美元，而十年前这个数字还近乎为0。而香港是这些贷款最大的来源地，其发放的高达4300亿美元的贷款相当于香港GDP的165%。
                </div>
                <div class="content">
                    <img src="/img/article.jpg" alt=""/>
                    <p>
                        路透援引消息人士的话称，香港金管局已要求银行收紧对中国企业离岸贷款的审批流程。金管局尚未公布任何具体或官方指导方针，但近期一系列对话都在向银行施压，要求他们进一步改善流程和把控。
                    </p>
                    <p>
                        路透援引消息人士的话称，香港金管局已要求银行收紧对中国企业离岸贷款的审批流程。金管局尚未公布任何具体或官方指导方针，但近期一系列对话都在向银行施压，要求他们进一步改善流程和把控。
                    </p>
                    <p>
                        近年来香港的银行向大陆发放贷款数量从无到有，激增至4300亿美元，但大陆方面最近经济显示出下滑的迹象并且信贷违约风险突出，这使得香港银行业神经紧绷。
                    </p>
                    <p>
                        近年来香港的银行向大陆发放贷款数量从无到有，激增至4300亿美元，但大陆方面最近经济显示出下滑的迹象并且信贷违约风险突出，这使得香港银行业神经紧绷。
                    </p>
                    <p>
                        据国际清算银行（BIS）数据显示，外资银行在华（大陆）债权去年已达1万亿美元，而十年前这个数字还近乎为0。而香港是这些贷款最大的来源地，其发放的高达4300亿美元的贷款相当于香港GDP的165%。
                    </p>
                    <p>
                        据国际清算银行（BIS）数据显示，外资银行在华（大陆）债权去年已达1万亿美元，而十年前这个数字还近乎为0。而香港是这些贷款最大的来源地，其发放的高达4300亿美元的贷款相当于香港GDP的165%。
                    </p>
                </div>
                <div class="state">
                    本文内容仅供读者参考，并非投资建议。 转载请注明来源并加上本站链接，华尔街见闻将保留所有法律权益。
                    <br/>
                    版权采用 <span class="red">知识共享署名-非商业性使用 3.0</span> 未本地化版本许可协议 进行许可
                </div>
                <div class="toolbar">
                    <!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style_24x24">
                        <a class="jiathis_button_qzone"></a>
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_tqq"></a>
                        <a class="jiathis_button_renren"></a>
                        <a class="jiathis_button_kaixin001"></a>
                        <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank"></a>
                        <a class="jiathis_counter_style"></a>
                    </div>
                    <script type="text/javascript" >
                        var jiathis_config={
                            hideMore:false
                        }
                    </script>
                    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
                    <!-- JiaThis Button END -->
                    <a href="/" class="back">
                        返回黄金头条首页
                    </a>
                </div>
            </div>
            <div class="user-comments">
                <div class="title">评论（<span class="amount">5</span>）</div>
                <div class="content">
                    <form action="">
                        <textarea class="input" name="user-comment" rows="6"></textarea>
                        <input class="submit" type="submit" value="评论"/>
                    </form>
                    <ul class="list">
                        <li class="item">
                            <div class="row">
                                <div class="span">
                                    <img class="avatar" src="" alt=""/>
                                </div>
                                <div class="span">
                                    <h4 class="name">业界良心</h4>
                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                    <div class="row">
                                        <div class="time span">3分钟前</div>
                                        <div class="toolbar right">
                                        <span class="button">
                                            <i class="icon-thumbs-up"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            <i class="icon-thumbs-down"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            回复（<span>3</span>）
                                        </span>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="user-comments">
                                <div class="content">
                                    <form action="">
                                        <textarea class="input" name="user-comment" rows="3"></textarea>
                                        <input class="submit" type="submit" value="评论"/>
                                    </form>
                                    <ul class="list">
                                        <li class="item ">
                                            <div class="row">
                                                <div class="span">
                                                    <img class="avatar" src="" alt=""/>
                                                </div>
                                                <div class="span">
                                                    <h4 class="name">业界良心</h4>
                                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                                    <div class="time span">3分钟前</div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="item ">
                                            <div class="row">
                                                <div class="span">
                                                    <img class="avatar" src="" alt=""/>
                                                </div>
                                                <div class="span">
                                                    <h4 class="name">业界良心</h4>
                                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                                    <div class="time span">3分钟前</div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="row">
                                <div class="span">
                                    <img class="avatar" src="" alt=""/>
                                </div>
                                <div class="span">
                                    <h4 class="name">业界良心</h4>
                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                    <div class="row">
                                        <div class="time span">3分钟前</div>
                                        <div class="toolbar right">
                                        <span class="button">
                                            <i class="icon-thumbs-up"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            <i class="icon-thumbs-down"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            回复（<span>3</span>）
                                        </span>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="more">显示更多评论</div>
            </div>
        </div>
    </div>
    <div id="sidebar" class="span4">
        <h2 class="title">财经日历</h2>
        <div id="side-fcl" class="nano finance-calendar scrollable list type1" data-fcl-option="auto-scroll:true;">
            <div class="titlebar">
                据下次数据公布时间还有：<span class="clock"></span>
            </div>
            <ul class="nano-content content"></ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                <% var record = records[i]; %>
                <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                <% } %>
                <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                    <div class="row">
                        <div class="span3 meta">
                            <span class="time"><%= record.time %></span>
                        </div>
                        <div class="span8">
                            <a class="link" href=""><%= record.title %></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3 actual meta">
                            <span class="label">今值：</span>
                            <span class="value"><%= record.actual %></span>
                        </div>
                        <div class="span3 forecast meta">
                            <span class="label">预测：</span>
                            <span class="value"><%= record.forecast %></span>
                        </div>
                        <div class="span3 previous meta">
                            <span class="label">前值：</span>
                            <span class="value"><%= record.previous %></span>
                        </div>
                    </div>
                </li>
                <% } %>
            </script>
        </div>
    </div>
</div>