<div class="row relative">
    <div class="span9">

        <div id="main">

            <div class="row">

                <div class="span">
                    <div class="topnews view">
                        <ul class="topnews carousel">
                            <li class="item">
                                <a class="link" href="">
                                    <img class="img" src="img/img01.png" alt=""/>
                                    <h3 class="title">央行今日在施600亿元正回购操作，本周净回笼1080亿元流行</h3>
                                </a>
                            </li>
                        </ul>
                        <ul class="topnews list">
                            <li class="item"><a class="link" href="">上海证券报：高层或已特许部分城市松绑限购</a></li>
                            <li class="item"><a class="link active" href="">金融战首个牺牲品——俄铝录得2008年以来最惨重亏损 警告违约风险</a></li>
                            <li class="item"><a class="link" href="">欧洲竭力争取中国在乌克兰危机支持</a></li>
                            <li class="item"><a class="link" href="">报道：银监会首次下发地方同业规范文件 治理15万亿“异变”业务</a></li>
                            <li class="item"><a class="link" href="">穆迪将俄罗斯列入降级观察 称与乌克兰冲突削弱经济</a></li>
                            <li class="item"><a class="link" href="">神秘致电白宫，普京到底在打什么牌？</a></li>
                            <li class="item"><a class="link" href="">西方不亮东方亮 俄罗斯引资中投与中东基金</a></li>
                            <li class="item"><a class="link" href="">美国3月密歇根大学消费者信心指数终值不及预期，降至四个月新低</a></li>
                            <li class="item"><a class="link" href="">廉价信贷消失 中国房地产开发商“大洗牌”在即</a></li>
                            <li class="item"><a class="link" href="">美国2月个人支出创三个月最大，但前值下修，投行下调美一季度GDP预期</a></li>
                        </ul>
                    </div>
                </div><!--span end -->

                <div class="span">

                    <div class="market chart tabpanel type4">
                        <ul class="tabbar">
                            <li class="tab"><a class="link active" href="">黄金</a></li>
                            <li class="tab"><a class="link" href="">白银</a></li>
                            <li class="tab"><a class="link" href="">美元指数</a></li>
                            <li class="tab"><a class="link" href="">标普500</a></li>
                            <li class="tab"><a class="link" href="">石油</a></li>

                            <button class="button" data-toggle="stare-modal">盯盘模式</button>
                        </ul>
                        <ul class="content">
                            <li class="panel active">
                                <div class="toolbar">
                                    <div class="button">1</div>
                                    <div class="button">5</div>
                                    <div class="button">15</div>
                                    <div class="button active">30</div>
                                    <div class="button">1H</div>
                                    <div class="button">4H</div>
                                    <div class="button">1D</div>
                                    <div class="button">1W</div>
                                    <div class="button">1M</div>
                                </div>
                                <div class="chart">
                                <img width="440" height="206" src="/img/grid02.png" />
                                    <!--
                                        <iframe width="440" height="206" scrolling="no" frameborder="0" src="http://markets.wallstreetcn.com/embed/chart?symbol=USDCHF&amp;width=440&amp;height=206&amp;rows=50&amp;interval=5"></iframe>
                                    -->
                                </div>
                            </li>
                            <li class="panel">
                                <div class="toolbar">
                                    <div class="button">1</div>
                                    <div class="button">5</div>
                                    <div class="button">15</div>
                                    <div class="button active">30</div>
                                    <div class="button">1H</div>
                                    <div class="button">4H</div>
                                    <div class="button">1D</div>
                                    <div class="button">1W</div>
                                    <div class="button">1M</div>
                                </div>
                                <div class="chart">
                                <img width="440" height="206" src="/img/grid02.png" />
                                </div>
                            </li>
                            <li class="panel">
                                <div class="toolbar">
                                    <div class="button">1</div>
                                    <div class="button">5</div>
                                    <div class="button">15</div>
                                    <div class="button active">30</div>
                                    <div class="button">1H</div>
                                    <div class="button">4H</div>
                                    <div class="button">1D</div>
                                    <div class="button">1W</div>
                                    <div class="button">1M</div>
                                </div>
                                <div class="chart">
                                <img width="440" height="206" src="/img/grid02.png" />
                                </div>
                            </li>
                            <li class="panel">
                                <div class="toolbar">
                                    <div class="button">1</div>
                                    <div class="button">5</div>
                                    <div class="button">15</div>
                                    <div class="button active">30</div>
                                    <div class="button">1H</div>
                                    <div class="button">4H</div>
                                    <div class="button">1D</div>
                                    <div class="button">1W</div>
                                    <div class="button">1M</div>
                                </div>
                                <div class="chart">
                                <img width="440" height="206" src="/img/grid02.png" />
                                </div>
                            </li>
                            <li class="panel">
                                <div class="toolbar">
                                    <div class="button">1</div>
                                    <div class="button">5</div>
                                    <div class="button">15</div>
                                    <div class="button active">30</div>
                                    <div class="button">1H</div>
                                    <div class="button">4H</div>
                                    <div class="button">1D</div>
                                    <div class="button">1W</div>
                                    <div class="button">1M</div>
                                </div>
                                <div class="chart">
                                <img width="440" height="206" src="/img/grid02.png" />
                                </div>
                            </li>
                        </ul>
                    </div>

                    <h2 class="main-title">实时新闻</h2>

                    <div class="nano livenews scrollable list" data-scroll-config="scroll:y;pane:left;">
                        <ul class="nano-content content">
                            <li class="date">2014年03月21日</li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">06:29</span>
                                <a class="link" href="">穆迪：将俄罗斯BAA1国债评级列入可能调降的观察名单中。做出这一决定是因与乌克兰的冲突以及未来政策的不确定性导致俄罗斯经济增长力量减弱。如果评级检讨导致俄罗斯BAA1国债评级被调降，最可能的结果是调降一个级距。</a>
                            </li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">07:06</span>
                                <a class="link" href="">本周累计，道琼斯指数上涨0.1%，标普500指数下跌0.5%，纳斯达克指数重跌2.8%。纳斯达克指数录得自2012年10月12日以来最大单周跌幅。</a>
                            </li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">08:29</span>
                                <a class="link" href="">CFTC：截至到3月25日当周，美国10年期国债期货合约投机净空头增加6751手，至61765手。 </a>
                            </li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">08:36</span>
                                <a class="link" href="">“美联储通讯社”Hilsenrath：美国通胀连续22个月低于美联储目标水平，这能够使美联储官员暂时停下来，讨论是否继续削减QE，以及何时加息。 </a>
                            </li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">08:55</span>
                                <a class="link" href="">CFTC：截至到3月25日当周，WTI原油期货投机净多头持仓减少10399手合约，至340970手。</a>
                            </li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">09:12</span>
                                <a class="link" href="">布伦特原油收盘报108.07美元/桶，上涨0.24美元，涨幅0.22%。</a>
                            </li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">09:25</span>
                                <a class="link" href="">美国NYMEX 5月原油期货价格收盘上涨0.39美元，涨幅0.4%，报101.67美元/桶。本周累计上涨2.2%。 </a>
                            </li>
                            <li class="date">2014年03月20日</li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">08:33</span>
                                <a class="link" href="">巴克莱：由于上个月消费支出数据遭下修，将美国一季度GDP增速预期从2.4%调降至2.0%。</a>
                            </li>
                            <li class="item">
                                <span class="icon alert"></span>
                                <span class="time">09:17</span>
                                <a class="link" href="">波罗的海干散货指数下跌2.8%，至1373点。 </a>
                            </li>
                        </ul>
                        <!--livenews list end-->
                    </div>



                </div><!--span end -->

            </div><!-- row end -->

            <div class="row">
                <h2 class="main-title">技术分析</h2>

                <div class="tabpanel type5 market-analysis">
                    <ul class="tabbar">
                        <li class="tab">
                            <a class="link active" href="">黄金</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">白银</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">美元指数</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">美债</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">原油</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">美国标股500</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">日经</a>
                        </li>
                    </ul>
                    <ul class="content">
                        <li class="panel active row">
                            <div class="span overview-data">
                                <span class="update-time">更新时间：2014年3月3日05:52GMT</span>
                                <span class="close-price">昨收：1321.60</span>
                                <span class="open-price">今开：1332.60</span>
                                <h3 class="title">黄金：<span class="price">1332.60</span></h3>
                                <h3 class="advice">建议：<span class="text">中性</span></h3>
                                <div class="compare">
                                    <h3 class="title">多空对比</h3>
                                    <div class="row">
                                        <div class="bearish span left text-left">
                                            <span class="value">75%</span>
                                            <span class="label">看空</span>
                                        </div>
                                        <div class="bullish span right text-right">
                                            <span class="value">25%</span>
                                            <span class="label">看多</span>
                                        </div>
                                    </div>
                                    <div class="row indicator">
                                        <span class="span bearish" style="width: 75%;"></span>
                                        <span class="span bullish" style="width: 25%;"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="span realtime-data">
                                <div class="tabpanel type1">
                                    <ul class="tabbar">
                                        <li class="label">时间范围：</li>
                                        <li class="tab"><a class="link" href="">5分钟</a></li>
                                        <li class="tab"><a class="link active" href="">15分钟</a></li>
                                        <li class="tab"><a class="link" href="">每小时</a></li>
                                        <li class="tab"><a class="link" href="">每日</a></li>
                                    </ul>
                                    <ul class="content">
                                        <li class="panel"></li>
                                        <li class="panel active">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th class="cell1">S3</th>
                                                    <th class="cell1">S2</th>
                                                    <th class="cell1">S1</th>
                                                    <th class="pivot">枢轴点</th>
                                                    <th class="cell1">R1</th>
                                                    <th class="cell1">R2</th>
                                                    <th class="cell1">R3</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td class="cell1">22600.35</td>
                                                    <td class="cell1">22701.54</td>
                                                    <td class="cell1">22701.54</td>
                                                    <td class="pivot">22703.67</td>
                                                    <td class="cell1">23701.54</td>
                                                    <td class="cell1">23721.69</td>
                                                    <td class="cell1">23901.04</td>
                                                </tr>
                                                </tbody>
                                            </table>

                                            <span class="dash-line"></span>

                                            <table class="table">
                                                <tbody>
                                                <tr>
                                                    <td class="label">移动平均指数：</td>
                                                    <td class="cell2">
                                                        <a class="link buy"  href="#">购买<span class="value">(6)</span></a>
                                                    </td>
                                                    <td class="cell2">
                                                        <a class="link sell" href="#">出售<span class="value">(3)</span></a>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="label">指标：</td>
                                                    <td class="cell2">
                                                        <a class="link buy"  href="#">购买<span class="value">(6)</span></a>
                                                    </td>
                                                    <td class="cell2">
                                                        <a class="link sell" href="#">出售<span class="value">(3)</span></a>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>

                                        </li>
                                        <li class="panel"></li>
                                        <li class="panel"></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="panel"></li>
                        <li class="panel"></li>
                    </ul>
                </div>

            </div><!-- row end -->

            <div class="row">
                <div class="span left">
                    <h2 class="main-title">机构金评</h2>
                    <div class="economic-evaluation tabpanel type2">
                        <ul class="tabbar">
                            <li class="tab"><a class="link active" href="">黄金</a></li>
                            <li class="tab"><a class="link " href="">白银</a></li>
                            <li class="tab"><a class="link " href="">布油</a></li>
                            <li class="tab"><a class="link " href="">美元指数</a></li>
                        </ul>
                        <ul class="content">
                            <li class="panel active">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">全球继续维持量化宽松</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/16 13:25</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">全球继续维持量化宽松</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/16 13:25</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">全球继续维持量化宽松</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/16 13:25</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">全球继续维持量化宽松</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/16 13:25</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="span right">
                    <h2 class="main-title">投资教程</h2>
                    <ul class="investment-tutorial list">
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">1</span>
                                <span class="span title">基础知识</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">2</span>
                                <span class="span title">投资介绍</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">3</span>
                                <span class="span title">基本分析</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">4</span>
                                <span class="span title">技术分析</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">5</span>
                                <span class="span title">风险技巧</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">6</span>
                                <span class="span title">开户交易</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">7</span>
                                <span class="span title">规章制度</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div><!--main end -->
    </div><!--span9 end -->
    <div id="sidebar" class="span3" >
        <h2 class="title">财经日历</h2>
        <div class="nano finance-calendar scrollable list">
            <ul class="nano-content content">
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">05:45am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">日本第一季度GDP平均指数初值</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">4.123%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">-1.40B</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">2.394%</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">10:22am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">密歇根大学消费者信心预期初值</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">95.4</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">94</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">93.6</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">10:30am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">盖屋同意（月度环比）</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">-8.3%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">-3.5%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">7.1%</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">11:20am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">意大利消费者物价指数（月度环比)P</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">-0.1%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">0.1%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">0.2%</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">14:20pm</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">东京核心消费者物价指数（同比）</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">0.9%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">0.8%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">0.7%</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">05:45am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">日本第一季度GDP平均指数初值</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">4.123%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">-1.40B</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">2.394%</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">10:22am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">密歇根大学消费者信心预期初值</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">95.4</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">94</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">93.6</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">10:30am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">盖屋同意（月度环比）</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">-8.3%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">-3.5%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">7.1%</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">11:20am</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">意大利消费者物价指数（月度环比)P</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">-0.1%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">0.1%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">0.2%</span>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="time">14:20pm</span>
                        </div>
                        <div class="span width-180">
                            <a class="link" href="">东京核心消费者物价指数（同比）</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span meta width-80">
                            <span class="label">今值：</span>
                            <span class="value">0.9%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">预测：</span>
                            <span class="value">0.8%</span>
                        </div>
                        <div class="span meta width-80">
                            <span class="label">前值：</span>
                            <span class="value">0.7%</span>
                        </div>
                    </div>
                </li>

            </ul>
        </div>

        <div class="line type1"></div>
        <h2 class="title">黄金多空调查</h2>
        <div class="line type1"></div>
        <div id="gold-research">
            <div class="chart type1" >
                <img width="220" height="150" style="margin-left: 10px;" src="/img/grid03.png" />
            </div>
            <div class="row">
                <div class="span4"><button class="button type1 pink">上涨</button></div>
                <div class="span4"><button class="button type1 gray">盘整</button></div>
                <div class="span4"><button class="button type1 green">下跌</button></div>
            </div>
        </div>
        <div class="line type1"></div>
        <h2 class="title">黄金兑换器</h2>
        <div class="line type1"></div>
        <form id="" class="form type1" action="">
            <div class="row">
                <div class="span6">
                    <input type="text" name=""/>
                </div>
                <div class="span6">
                    <select name="">
                        <option value ="rmb">人民币/克</option>
                        <option value ="usd">美元/盎司</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <input type="text" name=""/>
                </div>
                <div class="span6">
                    <select name="">
                        <option value ="">美元/盎司</option>
                        <option value ="">人民币/克</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <label for="">基于市场即时价格</label>
                </div>
                <div class="span6">
                    <button class="button" type="submit">计算</button>
                </div>
            </div>
        </form>
        <div class="line type1"></div>
        <div class="tabpanel type3">
            <ul class="tabbar">
                <li class="tab"><a class="link active" href="">ETF持仓</a></li>
                <li class="tab"><a class="link" href="">CFTC持仓</a></li>
                <li class="tab"><a class="link" href="">定盘价</a></li>
            </ul>
            <ul class="content">
                <li class="panel active">
                    <div class="chart type2">
                        <img width="270" height="230" src="/img/grid01.png" />
                    </div>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead>
                        <tr>
                            <th>时间</th>
                            <th>增仓量(吨)</th>
                            <th>增减(吨)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>2014.03.04</td>
                            <td>803.70398</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.03</td>
                            <td>804.00120</td>
                            <td>0.03</td>
                        </tr>
                        <tr>
                            <td>2014.03.02</td>
                            <td>803.70398</td>
                            <td>0.10</td>
                        </tr>
                        </tbody>
                    </table>
                </li>
                <li class="panel">
                    <div class="chart type2">
                        <img width="270" height="230" src="/img/grid01.png" />
                    </div>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead>
                        <tr>
                            <th>时间</th>
                            <th>增仓量(吨)</th>
                            <th>增减(吨)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>2014.03.04</td>
                            <td>803.70398</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.03</td>
                            <td>804.00120</td>
                            <td>0.03</td>
                        </tr>
                        <tr>
                            <td>2014.03.02</td>
                            <td>803.70398</td>
                            <td>0.10</td>
                        </tr>
                        </tbody>
                    </table>
                </li>
                <li class="panel">
                    <div class="chart type2">
                        <img width="270" height="230" src="/img/grid01.png" />
                    </div>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead>
                        <tr>
                            <th>时间</th>
                            <th>增仓量(吨)</th>
                            <th>增减(吨)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>2014.03.04</td>
                            <td>803.70398</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.03</td>
                            <td>804.00120</td>
                            <td>0.03</td>
                        </tr>
                        <tr>
                            <td>2014.03.02</td>
                            <td>803.70398</td>
                            <td>0.10</td>
                        </tr>
                        </tbody>
                    </table>
                </li>
            </ul>
        </div>
        <div class="line type1"></div>
    </div>
</div>

<div id="modal">
    <div id="stare-modal" class="panel">

        <div class="row">
            <div class="span ">
                <div class="tabpanel type4">
                    <ul class="tabbar">
                        <li class="tab"><a class="link active" href="">黄金</a></li>
                        <li class="tab"><a class="link" href="">白银</a></li>
                        <li class="tab"><a class="link" href="">美元指数</a></li>
                        <li class="tab"><a class="link" href="">标普500</a></li>
                        <li class="tab"><a class="link" href="">石油</a></li>
                        <li class="tab"><a class="link" href="">美债</a></li>
                    </ul>
                    <ul class="content">
                        <li class="panel active">
                            <div class="row">
                                <div class="span left">
                                    <div class="toolbar type1">
                                        <div class="button left">K线图</div>
                                        <div class="button right">分时图</div>
                                    </div>
                                </div>
                                <div class="span right">
                                    <div class="toolbar type2">
                                        <div class="button">1</div>
                                        <div class="button">5</div>
                                        <div class="button">15</div>
                                        <div class="button">30</div>
                                        <div class="button active">1H</div>
                                        <div class="button">4H</div>
                                        <div class="button">1D</div>
                                        <div class="button">1W</div>
                                        <div class="button">1M</div>
                                    </div>
                                </div>
                            </div>
                            <div class="chart">
                                <img width="617" height="195" src="/img/grid04.png" />
                            </div>
                        </li>
                        <li class="panel"></li>
                        <li class="panel"></li>
                        <li class="panel"></li>
                        <li class="panel"></li>
                        <li class="panel"></li>
                    </ul>
                </div><!-- tabpanel end -->
                <div class="head type5">
                    <h2 class="title">实时新闻</h2>
                    <div class="toolbar">
                        <label class="checkbox " for="livenews-auto-refresh"><i class="icon-refresh"></i> 自动刷新 <input id="livenews-auto-refresh" type="checkbox" value="true"></label>
                        <label class="checkbox " for="livenews-voice-alert"><i class="icon-volume-up"></i> 声音提醒 <input id="livenews-voice-alert" type="checkbox" value="true"></label>
                        <label class="checkbox " for="livenews-all-shrink"><i class="icon-double-angle-up"></i> 全部收起 <input id="livenews-all-shrink" type="checkbox" value="true"></label>
                    </div>
                </div>
                <div class="nano scrollable livenews list">
                    <ul class="nano-content content">
                        <li class="date">2014年03月21日</li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">06:29</span>
                            <a class="link" href="">穆迪：将俄罗斯BAA1国债评级列入可能调降的观察名单中。做出这一决定是因与乌克兰的冲突以及未来政策的不确定性导致俄罗斯经济增长力量减弱。如果评级检讨导致俄罗斯BAA1国债评级被调降，最可能的结果是调降一个级距。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">07:06</span>
                            <a class="link" href="">本周累计，道琼斯指数上涨0.1%，标普500指数下跌0.5%，纳斯达克指数重跌2.8%。纳斯达克指数录得自2012年10月12日以来最大单周跌幅。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:29</span>
                            <a class="link" href="">CFTC：截至到3月25日当周，美国10年期国债期货合约投机净空头增加6751手，至61765手。 </a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:36</span>
                            <a class="link" href="">“美联储通讯社”Hilsenrath：美国通胀连续22个月低于美联储目标水平，这能够使美联储官员暂时停下来，讨论是否继续削减QE，以及何时加息。 </a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:55</span>
                            <a class="link" href="">CFTC：截至到3月25日当周，WTI原油期货投机净多头持仓减少10399手合约，至340970手。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">09:12</span>
                            <a class="link" href="">布伦特原油收盘报108.07美元/桶，上涨0.24美元，涨幅0.22%。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">09:25</span>
                            <a class="link" href="">美国NYMEX 5月原油期货价格收盘上涨0.39美元，涨幅0.4%，报101.67美元/桶。本周累计上涨2.2%。 </a>
                        </li>
                        <li class="date">2014年03月20日</li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:33</span>
                            <a class="link" href="">巴克莱：由于上个月消费支出数据遭下修，将美国一季度GDP增速预期从2.4%调降至2.0%。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">09:17</span>
                            <a class="link" href="">波罗的海干散货指数下跌2.8%，至1373点。 </a>
                        </li>
                    </ul>
                </div><!--livenews list end-->
            </div> <!-- span end -->
            <div class="span right">
                <div class="head type5">
                    <h2 class="title">财经日历</h2>
                    <div class="toolbar">
                        <label class="checkbox " for="finance-calendar-auto-roll">自动滚动 <input id="finance-calendar-auto-roll" type="checkbox" value="true"></label>
                    </div>
                </div> <!--head end-->
                <div class="nano finance-calendar scrollable list">
                    <ul class="nano-content content">
                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">05:45am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">日本第一季度GDP平均指数初值</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利多金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">4.123%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">-1.40B</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">2.394%</span>
                                </div>
                            </div>
                        </li>

                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">10:22am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">密歇根大学消费者信心预期初值</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利多金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">95.4</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">94</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">93.6</span>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">05:45am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">美国 核心个人消费支出价格指数 (月度环比)</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利空金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">4.123%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">-1.40B</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">2.394%</span>
                                </div>
                            </div>
                        </li>

                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">11:20am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">意大利消费者物价指数（月度环比)P</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利多金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">-0.1%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">0.1%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">0.2%</span>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">05:45am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">美国 美联储公开市场委员会委员皮亚纳尔托(Pianalto)讲话</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利多金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">4.123%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">-1.40B</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">2.394%</span>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">05:45am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">日本第一季度GDP平均指数初值</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利多金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">4.123%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">-1.40B</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">2.394%</span>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">05:45am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">日本第一季度GDP平均指数初值</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利多金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">4.123%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">-1.40B</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">2.394%</span>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="row">
                                <div class="span2"><span class="time">05:45am</span></div>
                                <div class="span3">
                                    <span class="important" data-value="3"></span>
                                </div>
                                <div class="span7"><a class="link" href="">日本第一季度GDP平均指数初值</a></div>
                            </div>
                            <div class="row">
                                <div class="span2">
                                    <span class="profit good">
                                        利多金银
                                    </span>
                                </div>
                                <div class="span3">
                                    <span class="label">今值：</span>
                                    <span class="value">4.123%</span>
                                </div>
                                <div class="span3">
                                    <span class="label">预测：</span>
                                    <span class="value">-1.40B</span>
                                </div>
                                <div class="span3">
                                    <span class="label">前值：</span>
                                    <span class="value">2.394%</span>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div> <!--finance-calendar scrollable list end-->
                <div class="head type5">
                    <h2 class="title">技术分析</h2>
                </div> <!--head end-->
                <div class="tabpanel type5 market-analysis">
                    <ul class="tabbar">
                        <li class="tab">
                            <a class="link active" href="">黄金</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">白银</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">美元指数</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">美债</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">原油</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">美国标股500</a>
                        </li>
                        <li class="tab">
                            <a class="link" href="">日经</a>
                        </li>
                    </ul>
                    <ul class="content">
                        <li class="panel active">
                            <div class="overview-data">
                                <span class="update-time">更新时间：2014年3月3日05:52GMT</span>
                                <div class="row">
                                    <div class="span width-250">
                                        <h3 class="title">黄金：<span class="price">1332.60</span></h3>
                                    </div>
                                    <div class="span width-120">
                                        <span class="close-price">昨收：1321.60</span>
                                        <span class="open-price">今开：1322.03</span>
                                    </div>
                                </div>
                                <div class="line type1"></div>
                                <div class="row">
                                    <div class="span">
                                        <div class="compare">
                                            <h3 class="title">多空对比</h3>
                                            <div class="row">
                                                <div class="bearish span left text-left">
                                                    <span class="value">75%</span>
                                                    <span class="label">看空</span>
                                                </div>
                                                <div class="bullish span right text-right">
                                                    <span class="value">25%</span>
                                                    <span class="label">看多</span>
                                                </div>
                                            </div>
                                            <div class="row indicator">
                                                <span class="span bearish" style="width: 75%;"></span>
                                                <span class="span bullish" style="width: 25%;"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span width-120">
                                        <h3 class="advice">建议：<span class="text">中性</span></h3>
                                    </div>
                                </div>

                            </div>
                        </li>
                        <li class="panel"></li>
                        <li class="panel"></li>
                    </ul>
                </div>

            </div>
        </div>


        <div class="close"></div>
    </div>
</div>