<div class="row relative">
    <div class="span9">
        <div id="main">
            <div class="row">
                <div class="span">
                    <ul class="topnews carousel">
                        <li class="item">
                            <a class="link" href="">
                                <img class="img" src="/img/img01.png" alt=""/>
                                <h3 class="title">央行今日在施600亿元正回购操作，本周净回笼1080亿元流行</h3>
                            </a>
                        </li>
                    </ul>
                    <ul class="topnews list">
                        <li class="item"><a class="link" href="">上海证券报：高层或已特许部分城市松绑限购 <span class="time">14:22</span></a></li>
                        <li class="item"><a class="link active" href="">金融战首个牺牲品——俄铝录得2008年以来最惨重亏损 警告违约风险<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">欧洲竭力争取中国在乌克兰危机支持<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">报道：银监会首次下发地方同业规范文件 治理15万亿“异变”业务<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">穆迪将俄罗斯列入降级观察 称与乌克兰冲突削弱经济<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">神秘致电白宫，普京到底在打什么牌？<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">西方不亮东方亮 俄罗斯引资中投与中东基金<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">美国3月密歇根大学消费者信心指数终值不及预期，降至四个月新低<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">廉价信贷消失 中国房地产开发商“大洗牌”在即<span class="time">14:22</span></a></li>
                        <li class="item"><a class="link" href="">美国2月个人支出创三个月最大，但前值下修，投行下调美一季度GDP预期<span class="time">14:22</span></a></li>
                    </ul>
                </div><!--span end -->
                <div class="span">
                    <div id="chart" class="market chart">
                        <ul class="titlebar">
                            <a data-efc-target="#chart" data-efc-symbol="XAUUSD" class="link active" href="">黄金</a>
                            <a data-efc-target="#chart" data-efc-symbol="XAGUSD" class="link" href="">白银</a>
                            <a data-efc-target="#chart" data-efc-symbol="USDollarIndex" class="link" href="">美元指数</a>
                            <a data-efc-target="#chart" data-efc-symbol="SPX500" class="link" href="">标普500</a>
                            <a data-efc-target="#chart" data-efc-symbol="UKOil" class="link" href="">石油</a>

                            <button class="button" data-toggle="stare-modal">盯盘模式</button>
                        </ul>
                        <div class="content">
                            <div class="toolbar">
                                <div data-efc-target="#chart" data-efc-interval="1"  class="button">1</div>
                                <div data-efc-target="#chart" data-efc-interval="5"  class="button">5</div>
                                <div data-efc-target="#chart" data-efc-interval="15" class="button">15</div>
                                <div data-efc-target="#chart" data-efc-interval="30" class="button active">30</div>
                                <div data-efc-target="#chart" data-efc-interval="1H" class="button">1H</div>
                                <div data-efc-target="#chart" data-efc-interval="4H" class="button">4H</div>
                                <div data-efc-target="#chart" data-efc-interval="1D" class="button">1D</div>
                                <div data-efc-target="#chart" data-efc-interval="1W" class="button">1W</div>
                                <div data-efc-target="#chart" data-efc-interval="MN" class="button">1M</div>
                            </div>
                            <div class="chart">
                                <iframe width="440" height="206" scrolling="no" frameborder="0" src="http://markets.wallstreetcn.com/embed/chart?symbol=XAUUSD&theme=dark&width=440&height=206&rows=50&interval=30"></iframe>
                            </div>
                        </div>
                    </div><!-- market chart end -->
                    <h2 class="main-title">实时新闻</h2>
                    <div id="main-livenews" class="nano livenews scrollable list" data-scroll-config="scroll:y;pane:left;">
                        <ul class="nano-content content"></ul>
                        <script type="text/template" data-template>
                            <% for(var i=0; i<records.length; i++) { %>
                                <% var record = records[i]; %>
                                <% if (i == 0 && record.day != day) { %>
                                    <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                        <h3 class="label"><%= record.date %></h3>
                                        <i data-toggle="shrink" class="icon-custom-toggle"></i>
                                    </li>
                                <% } else if (i > 0 && record.day != records[i-1].day) { %>
                                    <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                        <h3 class="label"><%= record.date %></h3>
                                        <i data-toggle="shrink" class="icon-custom-toggle"></i>
                                    </li>
                                <% } %>
                                <li class="item <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                    <span class="icon" data-type="<%= record.icon %>"></span>
                                    <span class="time"><%= record.time %></span>
                                    <a class="link" href=""><%= record.title %></a>
                                </li>
                            <% } %>
                        </script>
                    </div> <!--livenews list end-->
                </div><!--span end -->
            </div><!-- row end -->

            <div class="row">
                <h2 class="main-title">技术分析</h2>

                <div id="analysis" class="market-analysis">
                    <div class="titlebar">
                        <a data-ma-target="#analysis" data-ma-symbol="XAUUSD" class="link active" href="">黄金</a>
                        <a data-ma-target="#analysis" data-ma-symbol="XAGUSD" class="link" href="">白银</a>
                        <a data-ma-target="#analysis" data-ma-symbol="USDollarIndex" class="link" href="">美元指数</a>
                        <a data-ma-target="#analysis" data-ma-symbol="US10Year" class="link" href="">美债</a>
                        <a data-ma-target="#analysis" data-ma-symbol="USOil" class="link" href="">原油</a>
                        <a data-ma-target="#analysis" data-ma-symbol="SPX500" class="link" href="">美国标股500</a>
                        <a data-ma-target="#analysis" data-ma-symbol="JPN225" class="link" href="">日经</a>
                    </div>
                    <div class="content row">

                        <script type="text/template" data-template-target="#analysis .datum">
                            <div data-trend="<%= trend %>">
                                <span class="update-time"><%= updateTime %></span>
                                <span class="close-price">昨收：<%= prevClose %></span>
                                <span class="open-price">今开：<%= open %></span>
                                <h3 class="title"><%= title %>：<span class="price"><%= price %></span></h3>
                            </div>
                        </script>

                        <div class="datum"></div>

                        <div class="span overview">

                            <h3 class="advice">建议：<span class="text">中性</span></h3>
                            <div class="compare">
                                <h3 class="title">多空对比</h3>
                                <div class="row">
                                    <div class="bearish span left text-left">
                                        <span class="value">50%</span>
                                        <span class="label">看空</span>
                                    </div>
                                    <div class="bullish span right text-right">
                                        <span class="value">50%</span>
                                        <span class="label">看多</span>
                                    </div>
                                </div>
                                <div class="row indicator">
                                    <span class="span bearish" style="width: 50%;"></span>
                                    <span class="span bullish" style="width: 50%;"></span>
                                </div>
                            </div>

                        </div>
                        <div class="span realtime-data">
                            <div class="tabpanel type1">
                                <nav class="tabbar">
                                    <a class="label">时间范围：</a>
                                    <a class="tab" href="">5分钟</a>
                                    <a class="tab active" href="">15分钟</a>
                                    <a class="tab" href="">每小时</a>
                                    <a class="tab" href="">每日</a>
                                </nav>
                                <ul class="content">
                                    <li class="panel"></li>
                                    <li class="panel active">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th class="cell1">S3</th>
                                                <th class="cell1">S2</th>
                                                <th class="cell1">S1</th>
                                                <th class="pivot">枢轴点</th>
                                                <th class="cell1">R1</th>
                                                <th class="cell1">R2</th>
                                                <th class="cell1">R3</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td class="cell1">22600.35</td>
                                                <td class="cell1">22701.54</td>
                                                <td class="cell1">22701.54</td>
                                                <td class="pivot">22703.67</td>
                                                <td class="cell1">23701.54</td>
                                                <td class="cell1">23721.69</td>
                                                <td class="cell1">23901.04</td>
                                            </tr>
                                            </tbody>
                                        </table>

                                        <span class="dash-line"></span>

                                        <table class="table">
                                            <tbody>
                                            <tr>
                                                <td class="label">移动平均指数：</td>
                                                <td class="cell2">
                                                    <a class="link buy"  href="#">购买<span class="value">(6)</span></a>
                                                </td>
                                                <td class="cell2">
                                                    <a class="link sell" href="#">出售<span class="value">(3)</span></a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">指标：</td>
                                                <td class="cell2">
                                                    <a class="link buy"  href="#">购买<span class="value">(6)</span></a>
                                                </td>
                                                <td class="cell2">
                                                    <a class="link sell" href="#">出售<span class="value">(3)</span></a>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>

                                    </li>
                                    <li class="panel"></li>
                                    <li class="panel"></li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>

            </div><!-- row end -->

            <div class="row">
                <div class="span left">
                    <h2 class="main-title">机构金评</h2>
                    <div class="economic-evaluation tabpanel type2">
                        <nav class="tabbar">
                            <a class="tab active" href="">黄金</a>
                            <a class="tab " href="">白银</a>
                            <a class="tab " href="">布油</a>
                            <a class="tab " href="">美元指数</a>
                        </nav>
                        <ul class="content">
                            <li class="panel active">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>
                                    <!--
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">全球继续维持量化宽松</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/16 13:25</span>
                                        </a>
                                    </li>
                                    -->
                                </ul>
                            </li>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>

                                </ul>
                            </li>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>

                                </ul>
                            </li>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势会受市场消息影响</span>
                                            <span class="span author">Peter Hug</span>
                                            <span class="span time">14/02/28 16:18</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月27日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/28 09:33</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金白银能否重拾涨势？</span>
                                            <span class="span author">Admin</span>
                                            <span class="span time">14/02/27 15:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">交易员需谨慎小心</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/27 07:49</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2月26日黄金白银止蚀买/卖盘价位</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/25 08:21</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">越多证据显示原材料商品市场已经筑底</span>
                                            <span class="span author">威科夫</span>
                                            <span class="span time">14/02/23 10:11</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">黄金走势起伏不断</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/23 12:03</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a class="link row" href="">
                                            <span class="span title">2014年商品市场会否迎来新一轮牛市周期？</span>
                                            <span class="span author">布莱希特</span>
                                            <span class="span time">14/02/18 10:52</span>
                                        </a>
                                    </li>

                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="span right">
                    <h2 class="main-title">投资教程</h2>
                    <ul class="investment-tutorial list">
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">1</span>
                                <span class="span title">基础知识</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">2</span>
                                <span class="span title">投资介绍</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">3</span>
                                <span class="span title">基本分析</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">4</span>
                                <span class="span title">技术分析</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">5</span>
                                <span class="span title">风险技巧</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">6</span>
                                <span class="span title">开户交易</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="">
                                <span class="span index">7</span>
                                <span class="span title">规章制度</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>

        </div><!--main end -->
    </div><!--span9 end -->
    <div id="sidebar" class="span3" >
        <h2 class="title">财经日历</h2>
        <div id="side-fcl" class="nano finance-calendar scrollable list">
            <ul class="nano-content content">
                <li class="more"></li>
            </ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                    <% var record = records[i]; %>
                    <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                        <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                    <% } %>
                    <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                        <div class="row">
                            <div class="span meta width-80">
                                <span class="time"><%= record.time %></span>
                            </div>
                            <div class="span width-180">
                                <a class="link" href=""><%= record.title %></a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="span actual meta width-80">
                                <span class="label">今值：</span>
                                <span class="value"><%= record.actual %></span>
                            </div>
                            <div class="span forecast meta width-80">
                                <span class="label">预测：</span>
                                <span class="value"><%= record.forecast %></span>
                            </div>
                            <div class="span previous meta width-80">
                                <span class="label">前值：</span>
                                <span class="value"><%= record.previous %></span>
                            </div>
                        </div>
                    </li>
                <% } %>
            </script>
        </div><!-- finance-calendar list end -->
        <div class="line type1"></div>
        <h2 class="title">黄金多空调查</h2>
        <div class="line type1"></div>
        <div id="gold-research">
            <div class="chart type1" >
                <img width="220" height="150" style="margin-left: 10px;" src="/img/grid03.png" />
            </div>
            <div class="row">
                <div class="span4"><button class="button type1 pink">上涨</button></div>
                <div class="span4"><button class="button type1 gray">盘整</button></div>
                <div class="span4"><button class="button type1 green">下跌</button></div>
            </div>
        </div>
        <div class="line type1"></div>
        <h2 class="title">黄金兑换器</h2>
        <div class="line type1"></div>
        <form id="gold-price-converter" class="form type1">
            <div class="row">
                <div class="span6">
                    <input type="text" name="input"/>
                </div>
                <div class="span6">
                    <select name="input-type">
                        <option value ="CNY">人民币/克</option>
                        <option value ="USD">美元/盎司</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <input type="text" name="result" readonly/>
                </div>
                <div class="span6">
                    <select name="result-type">
                        <option value ="USD">美元/盎司</option>
                        <option value ="CNY">人民币/克</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <label>基于市场即时价格</label>
                </div>
                <div class="span6">
                    <input type="button" class="button submit" value="计算">
                </div>
            </div>
        </form>
        <div class="line type1"></div>
        <div class="tabpanel type3">
            <nav class="tabbar">
                <a class="tab active" href="">ETF持仓</a>
                <a class="tab" href="">CFTC持仓</a>
                <a class="tab" href="">定盘价</a>
            </nav>
            <ul class="content">
                <li class="panel active">
                    <div class="chart type2">
                        <img width="270" height="230" src="/img/grid01.png" />
                    </div>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead>
                        <tr>
                            <th>时间</th>
                            <th>增仓量(吨)</th>
                            <th>增减(吨)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>2014.03.04</td>
                            <td>803.70398</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.03</td>
                            <td>804.00120</td>
                            <td>0.03</td>
                        </tr>
                        <tr>
                            <td>2014.03.02</td>
                            <td>803.70398</td>
                            <td>0.10</td>
                        </tr>
                        </tbody>
                    </table>
                </li>
                <li class="panel">
                    <div class="chart type2">
                        <img width="270" height="230" src="/img/grid01.png" />
                    </div>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead>
                        <tr>
                            <th>时间</th>
                            <th>增仓量(吨)</th>
                            <th>增减(吨)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>2014.03.04</td>
                            <td>803.70398</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.03</td>
                            <td>804.00120</td>
                            <td>0.03</td>
                        </tr>
                        <tr>
                            <td>2014.03.02</td>
                            <td>803.70398</td>
                            <td>0.10</td>
                        </tr>
                        </tbody>
                    </table>
                </li>
                <li class="panel">
                    <div class="chart type2">
                        <img width="270" height="230" src="/img/grid01.png" />
                    </div>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead>
                        <tr>
                            <th>时间</th>
                            <th>增仓量(吨)</th>
                            <th>增减(吨)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>2014.03.04</td>
                            <td>803.70398</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.03</td>
                            <td>804.00120</td>
                            <td>0.03</td>
                        </tr>
                        <tr>
                            <td>2014.03.02</td>
                            <td>803.70398</td>
                            <td>0.10</td>
                        </tr>
                        </tbody>
                    </table>
                </li>
            </ul>
        </div>
        <div class="line type1"></div>
    </div>
</div>

<div id="modal">
    <div id="stare-modal" class="panel">

        <div class="row content">
            <div class="span ">
                <div id="modal-chart" class="market chart">
                    <div class="titlebar">
                        <a data-efc-target="#modal-chart" data-efc-symbol="XAUUSD" class="link active" href="">黄金</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="XAGUSD" class="link" href="">白银</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="USDollarIndex" class="link" href="">美元指数</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="SPX500INDEX" class="link" href="">标普500</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="UKOil" class="link" href="">石油</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="US10Year" class="link" href="">美债</a>
                        <div class="button" data-toggle="hide" data-hide-target="#modal-chart>.content" data-expand-target="#stare-livenews"><i class="icon-custom"></i></div>
                    </div>
                    <div class="content">
                        <div class="toolbar row">
                            <div data-efc-target="#modal-chart" data-efc-type="k" class="button">K线图</div>
                            <div data-efc-target="#modal-chart" data-efc-type="t" class="button">分时图</div>
                            <div class="line vertical"></div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1"  class="button">1</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="5"  class="button">5</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="15" class="button">15</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="30" class="button active">30</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1H" class="button">1H</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="4H" class="button">4H</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1D" class="button">1D</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1W" class="button">1W</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="MN" class="button">1M</div>
                            <div class="line vertical"></div>
                        </div>
                        <div class="chart">
                            <iframe width="672" height="195" scrolling="no" frameborder="0" src="http://markets.wallstreetcn.com/embed/chart?symbol=XAUUSD&theme=dark&width=672&height=195&rows=50&interval=30"></iframe>
                        </div>
                    </div>
                </div><!-- market chart end -->
                <div class="head type5">
                    <h2 class="title">实时新闻</h2>
                    <div class="toolbar">
                        <!--<label class="checkbox " for="livenews-auto-refresh"><i class="icon-refresh"></i> 自动刷新 <input id="livenews-auto-refresh" type="checkbox" value="true"></label>-->
                        <label class="checkbox " for="livenews-voice-alert"><i class="icon-volume-up"></i> 声音提醒 <input id="livenews-voice-alert" type="checkbox" value="true"></label>
                        <label class="checkbox " for="livenews-all-shrink"><i class="icon-double-angle-up"></i> 全部收起 <input id="livenews-all-shrink" type="checkbox" value="true"></label>
                    </div>
                </div>
                <div id="stare-livenews" class="nano scrollable livenews list">
                    <ul class="nano-content content">
                        <!--
                        <li class="date">2014年03月21日</li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">06:29</span>
                            <a class="link" href="">穆迪：将俄罗斯BAA1国债评级列入可能调降的观察名单中。做出这一决定是因与乌克兰的冲突以及未来政策的不确定性导致俄罗斯经济增长力量减弱。如果评级检讨导致俄罗斯BAA1国债评级被调降，最可能的结果是调降一个级距。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">07:06</span>
                            <a class="link" href="">本周累计，道琼斯指数上涨0.1%，标普500指数下跌0.5%，纳斯达克指数重跌2.8%。纳斯达克指数录得自2012年10月12日以来最大单周跌幅。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:29</span>
                            <a class="link" href="">CFTC：截至到3月25日当周，美国10年期国债期货合约投机净空头增加6751手，至61765手。 </a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:36</span>
                            <a class="link" href="">“美联储通讯社”Hilsenrath：美国通胀连续22个月低于美联储目标水平，这能够使美联储官员暂时停下来，讨论是否继续削减QE，以及何时加息。 </a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:55</span>
                            <a class="link" href="">CFTC：截至到3月25日当周，WTI原油期货投机净多头持仓减少10399手合约，至340970手。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">09:12</span>
                            <a class="link" href="">布伦特原油收盘报108.07美元/桶，上涨0.24美元，涨幅0.22%。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">09:25</span>
                            <a class="link" href="">美国NYMEX 5月原油期货价格收盘上涨0.39美元，涨幅0.4%，报101.67美元/桶。本周累计上涨2.2%。 </a>
                        </li>
                        <li class="date">2014年03月20日</li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">08:33</span>
                            <a class="link" href="">巴克莱：由于上个月消费支出数据遭下修，将美国一季度GDP增速预期从2.4%调降至2.0%。</a>
                        </li>
                        <li class="item">
                            <span class="icon alert"></span>
                            <span class="time">09:17</span>
                            <a class="link" href="">波罗的海干散货指数下跌2.8%，至1373点。 </a>
                        </li>
                        -->

                        <script type="text/template" data-template>
                            <% for(var i=0; i<records.length; i++) { %>
                                <% var record = records[i]; %>
                                <% if (i == 0 && record.day != day) { %>
                                    <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                        <h3 class="label"><%= record.date %></h3>
                                        <i data-toggle="shrink" class="icon-custom-toggle"></i>
                                    </li>
                                <% } else if (i > 0 && record.day != records[i-1].day) { %>
                                    <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                        <h3 class="label"><%= record.date %></h3>
                                        <i data-toggle="shrink" class="icon-custom-toggle"></i>
                                    </li>
                                <% } %>
                                <li class="item <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                    <span class="icon" data-type="<%= record.icon %>"></span>
                                    <span class="time"><%= record.time %></span>
                                    <a class="link" href=""><%= record.title %></a>
                                </li>
                            <% } %>
                        </script>

                    </ul>
                </div><!--livenews list end-->
            </div> <!-- span end -->
            <div class="span right">
                <div class="head type5">
                    <h2 class="title">财经日历</h2>
                    <div class="toolbar">
                        <label class="checkbox " for="finance-calendar-auto-scroll">自动滚动 <input id="finance-calendar-auto-scroll" type="checkbox" checked value="true"></label>
                    </div>
                </div> <!--head end-->
                <div id="stare-fcl" class="nano finance-calendar scrollable list">
                    <div class="titlebar">
                        据下次数据公布时间还有：<span class="clock"></span>
                    </div>
                    <ul class="nano-content content">
                        <li class="more"></li>
                    </ul>
                    <script type="text/template" data-template>
                        <% for(var i=0; i<records.length; i++) { %>
                            <% var record = records[i]; %>
                            <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                                <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                            <% } %>
                            <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                                <div class="row">
                                    <span class="span time"><%= record.time %></span>
                                    <span class="span important" data-value="<%= record.importance %>"><%= record.stars %></span>
                                    <a class="span title link" href=""><%= record.title %></a>
                                </div>
                                <div class="row">
                                    <span class="span profit good"></span>
                                    <div class="span price actual">
                                        <span class="label">今值：</span>
                                        <span class="value"><%= record.actual %></span>
                                    </div>
                                    <div class="span price forecast">
                                        <span class="label">预测：</span>
                                        <span class="value"><%= record.forecast %></span>
                                    </div>
                                    <div class="span price previous">
                                        <span class="label">前值：</span>
                                        <span class="value"><%= record.previous %></span>
                                    </div>
                                </div>
                            </li>
                        <% } %>
                    </script>
                </div> <!--finance-calendar scrollable list end-->
                <div class="head type5 ">
                    <h2 class="title">技术分析</h2>
                    <div class="button" data-toggle="hide" data-hide-target="#modal-analysis" data-expand-target="#stare-fcl"><i class="icon-custom"></i></div>
                </div> <!--head end-->
                <div id="modal-analysis" class="market-analysis">
                    <div class="titlebar">
                        <a data-ma-target="#modal-analysis" data-ma-symbol="XAUUSD" class="link active" href="">黄金</a>
                        <a data-ma-target="#modal-analysis" data-ma-symbol="XAGUSD" class="link" href="">白银</a>
                        <a data-ma-target="#modal-analysis" data-ma-symbol="USDollarIndex" class="link" href="">美元指数</a>
                        <a data-ma-target="#modal-analysis" data-ma-symbol="US10Year" class="link" href="">美债</a>
                        <a data-ma-target="#modal-analysis" data-ma-symbol="USOil" class="link" href="">原油</a>
                        <a data-ma-target="#modal-analysis" data-ma-symbol="JPN225" class="link" href="">日经</a>
                    </div>
                    <div class="content">

                        <script type="text/template" data-template-target="#modal-analysis .datum">

                            <div data-trend="<%= trend %>">
                                <span class="update-time">更新时间：<%= updateTime %></span>
                                <div class="row">
                                    <div class="span width-250">
                                        <h3 class="title"><%= title %>：<span class="price"><%= price %></span></h3>
                                    </div>
                                    <div class="span width-120">
                                        <span class="close-price">昨收：<%= prevClose %></span>
                                        <span class="open-price">今开：<%= open %></span>
                                    </div>
                                </div>
                            </div>
                        </script>

                        <div class="datum"></div>

                        <div class="overview">

                            <div class="line type1"></div>
                            <div class="row">
                                <div class="span">
                                    <div class="compare">
                                        <h3 class="title">多空对比</h3>
                                        <div class="row">
                                            <div class="bearish span left text-left">
                                                <span class="value">50%</span>
                                                <span class="label">看空</span>
                                            </div>
                                            <div class="bullish span right text-right">
                                                <span class="value">50%</span>
                                                <span class="label">看多</span>
                                            </div>
                                        </div>
                                        <div class="row indicator">
                                            <span class="span bearish" style="width: 50%;"></span>
                                            <span class="span bullish" style="width: 50%;"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="span width-120">
                                    <h3 class="advice">建议：<span class="text">中性</span></h3>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>


        <div class="close"></div>
    </div>
</div>