<?$this->placeholder->block('title')->set('黄金头条')?>

<div class="row relative">
    <div class="span9">
        <div id="main">
            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 1 ,'limit' => 11));$posts = $pager->items;?>
            <div class="row">
                <div class="span">
                    <?$post = $posts->getFirst();?>
                    <?if($post):?>
                    <ul class="topnews carousel">
                        <li class="item">
                        <a class="link" href="/post/<?=$post->slug?>">
                            <img class="img" src="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_250,w_340') : '/img/article.jpg'?>" alt=""/>
                            <h3 class="title"><?=$this->escaper->escapeHtml($post->title)?></h3>
                        </a>
                        </li>
                    </ul>
                    <?endif?>
                    <ul class="topnews list">
                        <?foreach($posts as $key => $post):?>
                        <?if($key > 0):?>
                        <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtml($post->title)?> <span class="time"><?=$this->tag->datetime($post->createdAt, 'H:i')?></span></a></li>
                        <?endif?>
                        <?endforeach?>
                        <a class="main-more" href="/news">更多 &gt;&gt;</a>
                    </ul>
                </div><!--span end -->
                <div class="span">
                    <div id="chart" class="market chart">
                        <div class="titlebar">
                            <a data-efc-target="#chart" data-efc-symbol="XAUUSD" class="link active" href="">黄金</a>
                            <a data-efc-target="#chart" data-efc-symbol="XAGUSD" class="link" href="">白银</a>
                            <a data-efc-target="#chart" data-efc-symbol="USDollarIndex" class="link" href="">美元指数</a>
                            <a data-efc-target="#chart" data-efc-symbol="SPX500INDEX" class="link" href="">标普500</a>
                            <a data-efc-target="#chart" data-efc-symbol="UKOil" class="link" href="">石油</a>
                            <a class="link more" href="/market">更多</a>
                            <button class="button" data-toggle="stare-modal" onClick="ga('send', 'event', 'open', 'click', 'index_popup');">进入盯盘模式</button>
                        </div>
                        <div class="content">
                            <div class="toolbar">
                                <div data-efc-target="#chart" data-efc-interval="1"  class="button">1</div>
                                <div data-efc-target="#chart" data-efc-interval="5"  class="button active">5</div>
                                <div data-efc-target="#chart" data-efc-interval="15" class="button">15</div>
                                <div data-efc-target="#chart" data-efc-interval="30" class="button">30</div>
                                <div data-efc-target="#chart" data-efc-interval="1H" class="button">1H</div>
                                <div data-efc-target="#chart" data-efc-interval="4H" class="button">4H</div>
                                <div data-efc-target="#chart" data-efc-interval="1D" class="button">1D</div>
                                <div data-efc-target="#chart" data-efc-interval="1W" class="button">1W</div>
                                <div data-efc-target="#chart" data-efc-interval="MN" class="button">1M</div>
                            </div>
                            <div class="chart">
                                <iframe width="440" height="206" src="<?=$this->escaper->escapeHtmlAttr('http://markets.wallstreetcn.com/embed/hs?symbol=XAUUSD&chartTheme=dark&type=area&bgTheme=dark&width=440&height=206&rows=50&interval=5&newsUrl=http%3a%2f%2fapi.goldtoutiao.com%2fv2%2fpost%3fcid%3d' . $this->tag->config('wscngold', 'chartNewsCategoryId'))?>"></iframe>
                            </div>
                        </div>
                    </div><!-- market chart end -->
                    <h2 class="main-title">
                        <a href="/livenews">实时新闻</a>
                    </h2>
                    <div id="main-livenews" class="nano livenews scrollable list" data-scroll-config="scroll:y;pane:left;">
                        <ul class="nano-content content"></ul>
                        <script type="text/template" data-template>
                            <% for(var i=0; i<records.length; i++) { %>
                                <% var record = records[i]; %>
                                <% if (i == 0 && record.day != day) { %>
                                    <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                        <h3 class="label"><%= record.date %></h3>
                                        <i data-toggle="shrink" class="icon-custom-toggle"></i>
                                    </li>
                                <% } else if (i > 0 && record.day != records[i-1].day) { %>
                                    <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                        <h3 class="label"><%= record.date %></h3>
                                        <i data-toggle="shrink" class="icon-custom-toggle"></i>
                                    </li>
                                <% } %>
                                <li class="item <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                                    <span class="icon" data-type="<%= record.icon %>"></span>
                                    <span class="time"><%= record.time %></span>
                                    <a class="link" href="" data-nid="<%= record.nid %>"><%= record.title %></a>
                                </li>
                            <% } %>
                        </script>
                        <div class="loader">
                            <img class="indicator" src="/img/loader.gif" width="100" height="100" alt=""/>
                        </div>
                    </div> <!--livenews list end-->
                    <a class="main-more" href="/livenews">更多 &gt;&gt;</a>
                </div><!--span end -->
            </div><!-- row end -->

            <div class="row">
                <h2 class="main-title">
                    <a href="/techanalysis">技术分析</a>
                </h2>
                <div id="main-analysis" class="market-analysis" data-rtq data-rtq-option="overview: true;">
                    <div class="titlebar">
                        <a  data-rtq-symbol="XAUUSD" class="link active" href="/techanalysis/XAUUSD">黄金</a>
                        <a  data-rtq-symbol="XAGUSD" class="link" href="/techanalysis/XAGUSD">白银</a>
                        <a  data-rtq-symbol="USDollarIndex" class="link" href="/techanalysis/USDollarIndex">美元指数</a>
                        <a  data-rtq-symbol="US10Year" class="link" href="/techanalysis/US10Year">美债</a>
                        <a  data-rtq-symbol="USOil" class="link" href="/techanalysis/USOil">原油</a>
                        <a  data-rtq-symbol="SPX500INDEX" class="link" href="/techanalysis/SPX500INDEX">美国标普500</a>
                        <a  data-rtq-symbol="JPN225INDEX" class="link" href="/techanalysis/JPN225INDEX">日经</a>
                    </div>
                    <div class="content">
                        <script type="text/template" data-rtq-template>
                            <div data-trend="<%= trend %>">
                                <span class="update-time"><%= updateTime %></span>
                                <h3 class="title">
                                    <a href="/techanalysis/<%= symbol %>"><%= title %></a>：
                                    <span class="price"><%= price %></span>
                                </h3>
                                <span class="close-price">昨收：<%= prevClose %></span>
                                <span class="open-price">今开：<%= open %></span>
                            </div>
                        </script>
                        <div class="datum" data-rtq-dom>
                            <div data-trend="">
                                <span class="update-time">N/A</span>
                                <h3 class="title">N/A：<span class="price">N/A</span></h3>
                                <span class="close-price">昨收：N/A</span>
                                <span class="open-price">今开：N/A</span>
                            </div>
                        </div>
                        <div class="overview">
                            <div class="toolbar">
                                <a class="label">时间范围：</a>
                                <a class="nav" data-rtq-interval="5m" href="">5分钟</a>
                                <a class="nav" data-rtq-interval="15m" href="">15分钟</a>
                                <a class="nav active" data-rtq-interval="1h" href="">每小时</a>
                                <a class="nav" data-rtq-interval="1d" href="">每日</a>
                                <a class="nav" data-rtq-interval="mn" href="">每月</a>
                            </div>
                            <script type="text/template" data-overview-template>
                                <% var buy = parseInt(data.movingAverages.conclusion.buy) + parseInt(data.summary.datas.TechnicalIndicators.buy); %>
                                <% var sell= parseInt(data.movingAverages.conclusion.sell) + parseInt(data.summary.datas.TechnicalIndicators.sell); %>
                                <% var sum = buy + sell; %>
                                <% buy = (buy * 100 / sum).toFixed(2) + '%'; %>
                                <% sell = (sell * 100 / sum).toFixed(2) + '%'; %>
                                <% var advice = data.summary.conclusion.action; %>
                                <% var adviceClass = '' ; %>
                                <% if (advice.indexOf('买') > -1) {adviceClass = 'text-green';} else if (advice.indexOf('卖') > -1) {adviceClass = 'text-red';}%>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="cell1">S3</th>
                                        <th class="cell1">S2</th>
                                        <th class="cell1">S1</th>
                                        <th class="pivot">枢轴点</th>
                                        <th class="cell1">R1</th>
                                        <th class="cell1">R2</th>
                                        <th class="cell1">R3</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td class="cell1"><%= data.pivotPoints.datas.Classic.s3 %></td>
                                        <td class="cell1"><%= data.pivotPoints.datas.Classic.s2 %></td>
                                        <td class="cell1"><%= data.pivotPoints.datas.Classic.s1 %></td>
                                        <td class="pivot"><%= data.pivotPoints.datas.Classic.pivotPoints %></td>
                                        <td class="cell1"><%= data.pivotPoints.datas.Classic.r1 %></td>
                                        <td class="cell1"><%= data.pivotPoints.datas.Classic.r2 %></td>
                                        <td class="cell1"><%= data.pivotPoints.datas.Classic.r3 %></td>
                                    </tr>
                                    </tbody>
                                </table>
                                <span class="dash-line"></span>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <td class="label">
                                            <a href="/techanalysis/<%= symbol %>">移动平均指数：</a>
                                        </td>
                                        <td class="cell2">
                                            <span class="text-green">买入</span><span class="value">(<%= data.summary.datas.MovingAverages.buy %>)</span>
                                        </td>
                                        <td class="cell2">
                                            <span class="text-red">卖出</span><span class="value">(<%= data.summary.datas.MovingAverages.sell %>)</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <a href="/techanalysis/<%= symbol %>">指标：</a>
                                        </td>
                                        <td class="cell2">
                                            <span class="text-green">买入</span><span class="value">(<%= data.summary.datas.TechnicalIndicators.buy %>)</span>
                                        </td>
                                        <td class="cell2">
                                            <span class="text-red">卖出</span><span class="value">(<%= data.summary.datas.TechnicalIndicators.sell %>)</span>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div data-analysis-result>
                                    <h3 class="advice">建议：<span class="text <%= adviceClass %>"><%= advice %></span></h3>
                                    <div class="compare">
                                        <h3 class="title">多空对比</h3>
                                        <div class="row">
                                            <div class="bullish span left text-left">
                                                <span class="value">
                                                    <%= buy %>
                                                </span>
                                                <span class="label">看多</span>
                                            </div>
                                            <div class="bearish span right text-right">
                                                <span class="value">
                                                    <%= sell %>
                                                </span>
                                                <span class="label">看空</span>
                                            </div>
                                        </div>
                                        <div class="row indicator">
                                            <span class="span bullish" style="width: <%= buy %>;"></span>
                                            <span class="span bearish" style="width: <%= sell %>;"></span>
                                        </div>
                                    </div>
                                </div>
                            </script>
                            <div class="content" data-overview-dom>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="cell1">S3</th>
                                        <th class="cell1">S2</th>
                                        <th class="cell1">S1</th>
                                        <th class="pivot">枢轴点</th>
                                        <th class="cell1">R1</th>
                                        <th class="cell1">R2</th>
                                        <th class="cell1">R3</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td class="cell1">N/A</td>
                                        <td class="cell1">N/A</td>
                                        <td class="cell1">N/A</td>
                                        <td class="pivot">N/A</td>
                                        <td class="cell1">N/A</td>
                                        <td class="cell1">N/A</td>
                                        <td class="cell1">N/A</td>
                                    </tr>
                                    </tbody>
                                </table>
                                <span class="dash-line"></span>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <td class="label">移动平均指数：</td>
                                        <td class="cell2">
                                            <a class="link buy"  href="#">买入<span class="value">(N/A)</span></a>
                                        </td>
                                        <td class="cell2">
                                            <a class="link sell" href="#">卖出<span class="value">(N/A)</span></a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">指标：</td>
                                        <td class="cell2">
                                            <a class="link buy"  href="#">买入<span class="value">(N/A)</span></a>
                                        </td>
                                        <td class="cell2">
                                            <a class="link sell" href="#">卖出<span class="value">(N/A)</span></a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div data-analysis-result>
                                    <h3 class="advice">建议：<span class="text">N/A</span></h3>
                                    <div class="compare">
                                        <h3 class="title">多空对比</h3>
                                        <div class="row">
                                            <div class="bullish span left text-left">
                                                <span class="value">N/A</span>
                                                <span class="label">看多</span>
                                            </div>
                                            <div class="bearish span right text-right">
                                                <span class="value">N/A</span>
                                                <span class="label">看空</span>
                                            </div>
                                        </div>
                                        <div class="row indicator">
                                            <span class="span bullish" style="width: 50%;"></span>
                                            <span class="span bearish" style="width: 50%;"></span>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- data-overview-dom end -->
                        </div>  <!-- main-analysis overview end-->
                    </div> <!-- main-analysis content end-->
                </div> <!-- main-analysis end-->
            </div><!-- row end -->

            <div class="row">
                <div class="span left">
                    <h2 class="main-title">
                        <a href="/news/list?cid=8">机构金评</a>
                    </h2>
                    <div class="economic-evaluation tabpanel type2">
                        <nav class="tabbar">
                            <a class="tab active" href="">黄金</a>
                            <a class="tab " href="">白银</a>
                            <a class="tab " href="">布油</a>
                            <a class="tab " href="">美元指数</a>
                        </nav>
                        <ul class="content">
                            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 9, 'limit' => 8));$posts = $pager->items?>
                            <li class="panel active">
                                <ul class="economic-evaluation list">
                                    <?foreach($posts as $post):?>
                                    <li class="item">
                                    <a class="link row" href="/post/<?=$post->slug?>">
                                        <span class="span title"><?=$this->escaper->escapeHtml($post->title)?></span>
                                        <span class="span author"><?=$post->username ? $post->username : '黄金头条'?></span>
                                        <span class="span time"><?=$this->tag->datetime($post->createdAt, 'y/m/d H:i')?></span>
                                        </a>
                                    </li>
                                    <?endforeach?>
                                </ul>
                            </li>
                            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 10, 'limit' => 8));$posts = $pager->items?>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <?foreach($posts as $post):?>
                                    <li class="item">
                                    <a class="link row" href="/post/<?=$post->slug?>">
                                        <span class="span title"><?=$this->escaper->escapeHtml($post->title)?></span>
                                        <span class="span author"><?=$post->username ? $post->username : '黄金头条'?></span>
                                        <span class="span time"><?=$this->tag->datetime($post->createdAt, 'y/m/d H:i')?></span>
                                        </a>
                                    </li>
                                    <?endforeach?>
                                </ul>
                            </li>
                            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 11, 'limit' => 8));$posts = $pager->items?>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <?foreach($posts as $post):?>
                                    <li class="item">
                                    <a class="link row" href="/post/<?=$post->slug?>">
                                        <span class="span title"><?=$this->escaper->escapeHtml($post->title)?></span>
                                        <span class="span author"><?=$post->username ? $post->username : '黄金头条'?></span>
                                        <span class="span time"><?=$this->tag->datetime($post->createdAt, 'y/m/d H:i')?></span>
                                        </a>
                                    </li>
                                    <?endforeach?>
                                </ul>
                            </li>
                            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 12, 'limit' => 8));$posts = $pager->items?>
                            <li class="panel ">
                                <ul class="economic-evaluation list">
                                    <?foreach($posts as $post):?>
                                    <li class="item">
                                    <a class="link row" href="/post/<?=$post->slug?>">
                                        <span class="span title"><?=$this->escaper->escapeHtml($post->title)?></span>
                                        <span class="span author"><?=$post->username ? $post->username : '黄金头条'?></span>
                                        <span class="span time"><?=$this->tag->datetime($post->createdAt, 'y/m/d H:i')?></span>
                                        </a>
                                    </li>
                                    <?endforeach?>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="span right">
                    <h2 class="main-title">
                        <a href="/tutorial">投资教室</a>
                    </h2>
                    <ul class="investment-tutorial list">
                        <li class="item">
                            <a class="link row" href="/tutorial">
                                <span class="span index">1</span>
                                <span class="span title">基础知识</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="/tutorial/huangjinbiaojiafangfa">
                                <span class="span index">2</span>
                                <span class="span title">投资介绍</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="/tutorial/jinkuangkaicai">
                                <span class="span index">3</span>
                                <span class="span title">基本分析</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="/tutorial/daoqiongsililun">
                                <span class="span index">4</span>
                                <span class="span title">技术分析</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="/tutorial/fengxianguanli">
                                <span class="span index">5</span>
                                <span class="span title">风险管理</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="/tutorial/shiwuhuangjintouzi">
                                <span class="span index">6</span>
                                <span class="span title">投资技巧</span>
                            </a>
                        </li>
                        <li class="item">
                            <a class="link row" href="/tutorial/yizhanhouxiaoniushi">
                                <span class="span index">7</span>
                                <span class="span title">历史牛熊</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>

        </div><!--main end -->
    </div><!--span9 end -->
    <div id="sidebar" class="span3" >
        <h2 class="title">
            <a href="/calendar">财经日历</a>
        </h2>
        <div id="side-fcl" class="nano finance-calendar scrollable list">
            <ul class="nano-content content">
                <li class="more"></li>
            </ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                    <% var record = records[i]; %>
                    <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                        <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                    <% } %>
                    <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                        <div class="row">
                            <div class="span meta width-80">
                                <span class="time"><%= record.time %></span>
                            </div>
                            <div class="span width-180">
                                <a class="link" href="/calendar"><%= record.country %>&nbsp;&nbsp;<%= record.title %></a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="span actual meta width-80">
                                <span class="label">今值：</span>
                                <span class="value"><%= record.actual %></span>
                            </div>
                            <div class="span forecast meta width-80">
                                <span class="label">预测：</span>
                                <span class="value"><%= record.forecast %></span>
                            </div>
                            <div class="span previous meta width-80">
                                <span class="label">前值：</span>
                                <span class="value"><%= record.previous %></span>
                            </div>
                        </div>
                    </li>
                <% } %>
            </script>
            <div class="loader">
                <img class="indicator" src="/img/loader.gif" width="100" height="100" alt=""/>
            </div>
        </div><!-- finance-calendar list end -->

        <!--
        <div class="line type1"></div>
        <h2 class="title">黄金多空调查</h2>
        <div class="line type1"></div>
        <div id="gold-research">
            <div id="gold-research-chart">
            </div>
            <div class="row">
                <div class="span4"><button data-action="rise" class="button type1 pink" >上涨</button></div>
                <div class="span4"><button data-action="fall" class="button type1 green">下跌</button></div>
                <div class="span4"><button data-action="dull" class="button type1 gray" >盘整</button></div>
            </div>
        </div>
        -->

        <div class="line type1"></div>
        <h2 class="title">黄金兑换器</h2>
        <div class="line type1"></div>
        <form id="gold-price-converter" class="form type1">
            <div class="row">
                <div class="span6">
                    <input type="text" name="input"/>
                </div>
                <div class="span6">
                    <select name="input-type">
                        <option value ="CNY">人民币/克</option>
                        <option value ="USD">美元/盎司</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <input type="text" name="result" readonly/>
                </div>
                <div class="span6">
                    <select name="result-type" disabled>
                        <option value ="USD">美元/盎司</option>
                        <option value ="CNY">人民币/克</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <label>基于市场即时价格</label>
                </div>
                <div class="span6">
                    <input type="button" class="button submit" value="计算">
                </div>
            </div>
        </form>
        <div class="line type1"></div>
        <div class="tabpanel type3">
            <nav class="tabbar">
                <a class="tab active" href="">ETF持仓</a>
                <a class="tab" data-tab-action="cftc" href="">CFTC持仓</a>
                <a class="tab" href="">定盘价</a>
            </nav>
            <ul class="content">
                <li class="panel active" data-etf data-etf-option="symbol: GOLD; chart: true; size: 3">
                    <div class="chart type2" data-etf-dom="chart"></div>
                    <script type="text/template" data-etf-template="data">
                        <% for (var i = 0, l = data.length; i < l; i++) { %>
                        <tr>
                            <td><%= data[i].date %></td>
                            <td><%= data[i].etf_ton %></td>
                            <td><%= data[i].change %></td>
                        </tr>
                        <% } %>
                    </script>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead> <tr> <th>时间</th> <th>净持仓量(吨)</th> <th>增减(吨)</th> </tr> </thead>
                        <tbody data-etf-dom="data"></tbody>
                    </table>
                </li>
                <!--chart-width: 270; chart-height: 240;-->
                <li class="panel" data-cftc data-cftc-option="symbol: GOLD; chart: true; size: 3;">
                    <div class="chart type2" data-cftc-dom="chart"></div>
                    <script type="text/template" data-cftc-template="data">
                        <% for (var i = 0, l = data.length; i < l; i++) { %>
                        <tr>
                            <td><%= data[i].date %></td>
                            <td><%= data[i].nc_diff %></td>
                            <td><%= data[i].nc_change %></td>
                        </tr>
                        <% } %>
                    </script>
                    <div class="line type1"></div>
                    <table class="table type2">
                        <thead> <tr> <th>时间</th> <th>非商业性多空净持仓</th> <th>净持仓较上周变化</th> </tr> </thead>
                        <tbody data-cftc-dom="data"></tbody>
                    </table>
                </li>
                <li class="panel" data-fix-price data-fix-price-option="size: 9; withSilver:false;">
                    <script type="text/template" data-fix-price-template>
                        <% var i, l = data.length; %>
                        <% for (i = 0; i < l; i ++) { %>
                        <tr class="item">
                            <td class="cell1"><%= data[i].date %></td>
                            <td class="cell1"><%= data[i].gold_am %></td>
                            <td class="cell1"><%= data[i].gold_pm %></td>
                        </tr>
                        <% } %>
                    </script>
                    <table class="table type2">
                        <thead>
                        <tr class="head">
                            <th colspan="3">黄金伦敦历史定盘价(美元/盎司）</th>
                        </tr>
                        <tr class="label">
                            <th>日期</th>
                            <th>上午定价</th>
                            <th>下午定价</th>
                        </tr>
                        </thead>
                        <tbody data-fix-price-dom></tbody>
                    </table>
                </li>
            </ul>
        </div>
        <div class="line type1"></div>
    </div>
</div>

<div id="modal">
    <div id="stare-modal" class="panel">

        <div class="row content">
            <div class="span ">
                <div id="modal-chart" class="market chart">
                    <div class="titlebar">
                        <a data-efc-target="#modal-chart" data-efc-symbol="XAUUSD" class="link active" href="">黄金</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="XAGUSD" class="link" href="">白银</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="USDollarIndex" class="link" href="">美元指数</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="SPX500INDEX" class="link" href="">标普500</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="UKOil" class="link" href="">石油</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="US10Year" class="link" href="">美债</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="AUTD" class="link" href="">黄金t+d</a>
                        <a data-efc-target="#modal-chart" data-efc-symbol="AGTD" class="link" href="">白银t+d</a>
                        <!--<a class="more" href="/market">更多</a>-->
                        <a data-efc-target="#modal-chart" data-efc-symbol="TTYXAGUSD" class="link last-of-type" href="">天通银</a>
                        <div class="button" data-toggle="hide" data-hide-target="#modal-chart>.content" data-expand-target="#stare-livenews"><i class="icon-custom"></i></div>
                    </div>
                    <div class="content">
                        <div class="toolbar row">
                            <div data-efc-target="#modal-chart" data-efc-type="candlestick" class="button">K线图</div>
                            <div data-efc-target="#modal-chart" data-efc-type="area" class="button active">分时图</div>
                            <div class="line vertical"></div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1"  class="button">1</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="5"  class="button active">5</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="15" class="button">15</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="30" class="button">30</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1H" class="button">1H</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="4H" class="button">4H</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1D" class="button">1D</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="1W" class="button">1W</div>
                            <div data-efc-target="#modal-chart" data-efc-interval="MN" class="button">1M</div>
                            <div class="line vertical"></div>
                        </div>
                        <div class="chart">
                            <iframe id="stare-iframe" width="672" height="195" data-src="<?=$this->escaper->escapeHtmlAttr('http://markets.wallstreetcn.com/embed/hs?symbol=XAUUSD&chartTheme=dark&type=area&bgTheme=dark&width=672&height=195&rows=50&interval=5&newsUrl=http%3a%2f%2fapi.goldtoutiao.com%2fv2%2fpost%3fcid%3d' . $this->tag->config('wscngold', 'chartNewsCategoryId'))?>"></iframe>
                        </div>
                    </div>
                </div><!-- market chart end -->
                <div class="head type5">
                    <h2 class="title">实时新闻</h2>
                    <div class="toolbar">
                        <!--<label class="checkbox " for="livenews-auto-refresh"><i class="icon-refresh"></i> 自动刷新 <input id="livenews-auto-refresh" type="checkbox" value="true"></label>-->
                        <label class="checkbox " for="livenews-voice-alert">
                            <i class="icon-volume-up"></i> 声音提醒
                            <input id="livenews-voice-alert" data-action="livenews-alert" data-target="#stare-livenews" type="checkbox">
                        </label>
                        <label class="checkbox " for="livenews-all-shrink">
                            <i class="icon-double-angle-up"></i> 全部收起
                            <input id="livenews-all-shrink" data-action="livenews-all-shrink" data-target="#stare-livenews" type="checkbox">
                        </label>
                    </div>
                </div>
                <div id="stare-livenews" class="nano scrollable livenews list">
                    <ul class="nano-content content"></ul>
                    <script type="text/template" data-template>
                        <% for(var i=0; i<records.length; i++) { %>
                        <% var record = records[i]; %>
                        <% if (i == 0 && record.day != day) { %>
                        <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                            <h3 class="label"><%= record.date %></h3>
                            <i data-toggle="shrink" class="icon-custom-toggle"></i>
                        </li>
                        <% } else if (i > 0 && record.day != records[i-1].day) { %>
                        <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                            <h3 class="label"><%= record.date %></h3>
                            <i data-toggle="shrink" class="icon-custom-toggle"></i>
                        </li>
                        <% } %>
                        <li class="item <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                            <span class="icon" data-type="<%= record.icon %>"></span>
                            <span class="time"><%= record.time %></span>
                            <a class="link" href="" data-nid="<%= record.nid %>"><%= record.title %></a>
                        </li>
                        <% } %>
                    </script>
                    <div class="loader">
                        <img class="indicator" src="/img/loader.gif" width="100" height="100" alt=""/>
                    </div>
                </div><!--livenews list end-->
            </div> <!-- span end -->
            <div class="span right">
                <div class="head type5">
                    <h2 class="title">财经日历</h2>
                    <div class="toolbar">
                        <label class="checkbox " for="finance-calendar-auto-scroll">自动滚动 <input id="finance-calendar-auto-scroll" type="checkbox" checked value="true"></label>
                    </div>
                </div> <!--head end-->
                <div id="stare-fcl" class="nano finance-calendar scrollable list" data-fcl-option="time-format: HH:mm a">
                    <div class="titlebar">
                        据 <a href="" data-action="scroll-fixed">下次数据</a> 公布时间还有：<span class="clock"></span>
                    </div>
                    <ul class="nano-content content">
                        <li class="more"></li>
                    </ul>
                    <script type="text/template" data-template>
                        <% for(var i=0; i<records.length; i++) { %>
                            <% var record = records[i]; %>
                            <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                                <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                            <% } %>
                            <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                                <div class="row relative">
                                    <div class="span time text-white"><%= record.time %></div>
                                    <div class="span country"><%= record.country %></div>
                                    <a class="span title link" href=""><%= record.title %></a>
                                </div>
                                <div class="row relative">
                                    <div class="span important" data-value="<%= record.importance %>"><%= record.stars %></div>
                                    <div class="span price actual">
                                        <span class="label">今值：</span>
                                        <span class="value"><%= record.actual %></span>
                                    </div>
                                    <div class="span price forecast">
                                        <span class="label">预测：</span>
                                        <span class="value"><%= record.forecast %></span>
                                    </div>
                                    <div class="span price previous">
                                        <span class="label">前值：</span>
                                        <span class="value"><%= record.previous %></span>
                                    </div>
                                </div>
                                <div class="decorate"></div>
                            </li>
                        <% } %>
                    </script>
                    <div class="loader">
                        <img class="indicator" src="/img/loader.gif" width="100" height="100" alt=""/>
                    </div>
                </div> <!--finance-calendar scrollable list end-->
                <div class="head type5 ">
                    <h2 class="title">技术分析</h2>
                    <div class="button dir-up" data-toggle="hide" data-hide-target="#modal-analysis" data-expand-target="#stare-fcl"><i class="icon-custom"></i></div>
                </div> <!--head end-->
                <div id="modal-analysis" class="market-analysis" data-rtq data-rtq-option="overview: true; default-interval: 1h;">
                    <div class="titlebar">
                        <a  data-rtq-symbol="XAUUSD" class="link active" href="">黄金</a>
                        <a  data-rtq-symbol="XAGUSD" class="link" href="">白银</a>
                        <a  data-rtq-symbol="USDollarIndex" class="link" href="">美元指数</a>
                        <a  data-rtq-symbol="US10Year" class="link" href="">美债</a>
                        <a  data-rtq-symbol="USOil" class="link" href="">原油</a>
                        <a  data-rtq-symbol="JPN225INDEX" class="link" href="">日经</a>
                    </div>
                    <div class="content">

                        <script type="text/template" data-rtq-template>
                            <div data-trend="<%= trend %>">
                                <span class="update-time">更新时间：<%= updateTime %></span>
                                <div class="row">
                                    <div class="span width-250">
                                        <h3 class="title">
                                            <a href="/techanalysis/<%= symbol %>"><%= title %></a>
                                            ：<span class="price"><%= price %></span>
                                        </h3>
                                    </div>
                                    <div class="span width-120">
                                        <span class="close-price">昨收：<%= prevClose %></span>
                                        <span class="open-price">今开：<%= open %></span>
                                    </div>
                                </div>
                            </div>
                        </script>
                        <script type="text/template" data-overview-template>
                            <% var buy = parseInt(data.movingAverages.conclusion.buy) + parseInt(data.summary.datas.TechnicalIndicators.buy); %>
                            <% var sell= parseInt(data.movingAverages.conclusion.sell) + parseInt(data.summary.datas.TechnicalIndicators.sell); %>
                            <% var sum = buy + sell; %>
                            <% buy = (buy * 100 / sum).toFixed(2) + '%'; %>
                            <% sell = (sell * 100 / sum).toFixed(2) + '%'; %>
                            <% var advice = data.summary.conclusion.action; %>
                            <% var adviceClass = '' ; %>
                            <% if (advice.indexOf('买') > -1) {adviceClass = 'text-green';} else if (advice.indexOf('卖') > -1) {adviceClass = 'text-red';}%>
                            <div class="line type1"></div>
                            <div class="row">
                                <div class="span">
                                    <div class="compare">
                                        <h3 class="title">多空对比</h3>
                                        <div class="row">
                                            <div class="bullish span left text-left">
                                                <span class="value"><%= buy %></span>
                                                <span class="label">看多</span>
                                            </div>
                                            <div class="bearish span right text-right">
                                                <span class="value"><%= sell %></span>
                                                <span class="label">看空</span>
                                            </div>
                                        </div>
                                        <div class="row indicator">
                                            <span class="span bullish" style="width: <%= buy %>;"></span>
                                            <span class="span bearish" style="width: <%= sell %>;"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="span width-120">
                                    <h3 class="advice">建议：<span class="text <%= adviceClass %>"><%= advice %></span></h3>
                                </div>
                            </div>
                        </script>

                        <div class="datum" data-rtq-dom>
                            <div data-trend="">
                                <span class="update-time">更新时间：N/A</span>
                                <div class="row">
                                    <div class="span width-250">
                                        <h3 class="title">N/A：<span class="price">N/A</span></h3>
                                    </div>
                                    <div class="span width-120">
                                        <span class="close-price">昨收：N/A</span>
                                        <span class="open-price">今开：N/A</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="overview" data-overview-dom>

                            <div class="line type1"></div>
                            <div class="row">
                                <div class="span">
                                    <div class="compare">
                                        <h3 class="title">多空对比</h3>
                                        <div class="row">
                                            <div class="bullish span left text-left">
                                                <span class="value">N/A</span>
                                                <span class="label">看多</span>
                                            </div>
                                            <div class="bearish span right text-right">
                                                <span class="value">N/A</span>
                                                <span class="label">看空</span>
                                            </div>
                                        </div>
                                        <div class="row indicator">
                                            <span class="span bullish" style="width: 50%;"></span>
                                            <span class="span bearish" style="width: 50%;"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="span width-120">
                                    <h3 class="advice">建议：<span class="text">N/A</span></h3>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>


        <div class="close"></div>
    </div>
</div>
