<div class="row relative">
    <div class="span8 min-height-1000">
        <ul class="menu tree" data-tree>
            <li data-tree-branch >
            <div class="item" data-toggle="sub-menu">
                <span class="text">基础知识</span>
                <i class="icon-custom-toggle"></i>
            </div>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">黄金概述</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金概念</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金金融地位演变史</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">影响金价因素</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">国际黄金市场介绍</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">国际黄金市场介绍</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">世界黄金储备情况与分布</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金市场参与者</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">中国的黄金市场</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">上海黄金交易所</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            </li>


            <li data-tree-branch >
            <div class="item" data-toggle="sub-menu">
                <span class="text">黄金投资介绍</span>
                <i class="icon-custom-toggle"></i>
            </div>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">品种介绍</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金标价方法</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金投资特点</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金投资与其他投资的区别</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text"><a href="">全球主要黄金市场交易时间表</a></span>
                </div>
                </li>
            </ul>
            </li>


            <li data-tree-branch >
            <div class="item" data-toggle="sub-menu">
                <span class="text">基本面分析</span>
                <i class="icon-custom-toggle"></i>
            </div>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">供给分析</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">金矿开采</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">央行售金</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">再生金</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">需求分析</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">工业需求</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">饰金需求</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">投资需求</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text"><a href="">美元与黄金</a></span>
                </div>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text"><a href="">通货膨胀与利率</a></span>
                </div>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text"><a href="">原油与大宗商品市场</a></span>
                </div>
                </li>
            </ul>
            </li>



            <li data-tree-branch >
            <div class="item" data-toggle="sub-menu">
                <span class="text">技术分析</span>
                <i class="icon-custom-toggle"></i>
            </div>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">技术分析的基本理论</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">道琼斯理论</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">艾略特波浪理论</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">图形分析</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">K线理论</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">中继形态</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">趋势线</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">移动平均线</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">平滑异同移动平均线</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">相对强弱指标</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">布林带</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">随机指标</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            </li>



            <li data-tree-branch >
            <div class="item" data-toggle="sub-menu">
                <span class="text">投资风险和技巧</span>
                <i class="icon-custom-toggle"></i>
            </div>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">风险管理和心态控制</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">风险管理</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">投资者常见心理误区</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            <ul class="sub-menu">
                <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">投资技巧</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">实物黄金投资</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金首饰投资</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">纸黄金投资</a></span>
                    </li>
                    <li class="item" data-tree-leaf>
                    <span class="text">- <a href="#">黄金期权投资</a></span>
                    </li>
                </ul>
                </li>
            </ul>
            </li>
        </ul>
        <div class="tutorial page">

            <h1><?=$post->title?></h1>

            <div class="content">
                <?=$post->getContentHtml()?>
            </div>
        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>

<script type="text/javascript" src="/vendor/js/pinyin.js"></script>
<script>
    $('.menu.tree a').each(function(){
            var link = $(this);
            var slug = pinyin(link.text(), {
                    style: pinyin.STYLE_NORMAL,
                    heteronym: true
            });
            slug = jQuery.map(slug, function( n, i ) {
                    return n[0];
            });
            slug = slug.join('');
            link.attr('href', '/tutorial/' + slug);
    });
</script>
