<div class="row relative">
    <div class="span8 min-height-1000">
        <ul class="menu tree" data-tree>
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">基础知识</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">黄金概述</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金概念</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金金融地位演变史</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">影响金价因素</a>
                            </li>
                        </ul>
                    </li>
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">国际黄金市场介绍</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">国际黄金市场介绍</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">世界黄金储备情况与分布</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金市场参与者</a>
                            </li>
                        </ul>
                    </li>
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">中国的黄金市场</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">上海黄金交易所</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- 基础知识 end -->
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">黄金投资介绍</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">品种介绍</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金标价方法</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金投资特点</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金投资与其他投资的区别</a>
                            </li>
                        </ul>
                    </li>
                    <li class="item" data-tree-leaf>
                        <a class="text" href="#">全球主要黄金市场交易时间表</a>
                    </li>
                </ul>
            </li>
            <!-- 黄金投资介绍 end -->
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">基本面分析</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">供给分析</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">金矿开采</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">央行售金</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">再生金</a>
                            </li>
                        </ul>
                    </li>
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">需求分析</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">工业需求</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">饰金需求</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">投资需求</a>
                            </li>
                        </ul>
                    </li>
                    <li class="item" data-tree-leaf>
                        <a class="text" href="#">美元与黄金</a>
                    </li>
                    <li class="item" data-tree-leaf>
                        <a class="text" href="#">通货膨胀与利率</a>
                    </li>
                    <li class="item" data-tree-leaf>
                        <a class="text" href="#">原油与大宗商品市场</a>
                    </li>
                </ul>
            </li>
            <!-- 基本面分析 end -->
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">技术分析</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">技术分析的基本理论</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">道琼斯理论</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">艾略特波浪理论</a>
                            </li>
                        </ul>
                    </li>
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">图形分析</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">K线理论</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">中继形态</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">趋势线</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">移动平均线</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">平滑异同移动平均线</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">相对强弱指标</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">布林带</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">随机指标</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- 技术分析 end -->
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">风险管理</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">风险管理和心态控制</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">风险管理</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">投资者常见心理误区</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- 投资风险 end -->
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">投资技巧</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">投资技巧</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">实物黄金投资</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金首饰投资</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">纸黄金投资</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">黄金期权投资</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- 投资技巧 end -->
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">历史牛熊</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">历史牛熊</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">一战后小牛市</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">布雷顿森林体系下的黄金</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">二战后布雷顿森林体系崩溃</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">七十年代大牛市</a>
                            </li>
                            <li class="item" data-tree-leaf>
                                <a class="text" href="#">大牛市后的20年熊市调整</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- 投资技巧 end -->
        </ul>

        <div class="tutorial page">

            <h1><?=$post->title?></h1>

            <div class="content">
                <?=$post->getContentHtml()?>
            </div>
        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>

<script type="text/javascript" src="/vendor/js/pinyin.js"></script>
<script>
    $('.menu.tree a').each(function(){
            var link = $(this);
            var slug = pinyin(link.text(), {
                    style: pinyin.STYLE_NORMAL,
                    heteronym: true
            });
            slug = jQuery.map(slug, function( n, i ) {
                    return n[0];
            });
            slug = slug.join('');
            link.attr('href', '/tutorial/' + slug);
    });
    /**
     * 投资教室导航高亮
     */
    if (/\/tutorial(\/)?$/.test(location.pathname)) {
        var $defaultActive = $('.menu.tree a[href="/tutorial/huangjingainian"]');
        $defaultActive.parents('[data-tree-branch]').addClass('active');
        $defaultActive.parent().addClass('active');
    } else {
        $('.menu.tree a[href]').each(function(){
            if (this.href == location.href) {
                var $this = $(this);
                $this.parents('[data-tree-branch]').addClass('active');
                $this.parent().addClass('active');
                //跳出循环
                return false;
            }
        });
    }
</script>
