<div class="row relative">
    <div class="span8 min-height-1000">
        <ul class="menu tree" data-tree>
            <li class="item" data-tree-leaf>
                <span class="text">基础知识</span>
            </li>
            <li class="item" data-tree-leaf>
                <span class="text">黄金投资介绍</span>
            </li>
            <li class="item" data-tree-leaf>
                <span class="text">基础面分析</span>
            </li>
            <li data-tree-branch >
                <div class="item" data-toggle="sub-menu">
                    <span class="text">技术面分析</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                        <span class="text">投资风险和技巧</span>
                    </li>
                    <li data-tree-branch>
                        <div class="item" data-toggle="sub-menu">
                            <span class="text">风险管理和心态控制</span>
                            <i class="icon-custom-toggle"></i>
                        </div>
                        <ul class="sub-menu">
                            <li class="item" data-tree-leaf>
                                <span class="text">- 风险管理</span>
                            </li>
                            <li class="item" data-tree-leaf>
                                <span class="text">- 投资者的误区</span>
                            </li>
                            <li class="item" data-tree-leaf>
                                <span class="text">- 投资技巧</span>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li data-tree-branch>
                <div class="item" data-toggle="sub-menu">
                    <span class="text">开户交易</span>
                    <i class="icon-custom-toggle"></i>
                </div>
                <ul class="sub-menu">
                    <li class="item" data-tree-leaf>
                        <span class=" text">投资风险</span>
                    </li>
                    <li class="item" data-tree-leaf>
                        <span class=" text">投资技巧</span>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="tutorial page">
            <h1>投资风险和技巧</h1>
            <h2>风险管理和心态控制</h2>
            <h3 class="title">（一）风险管理</h3>
            <h4>1、什么是风险和风险管理</h4>
            <p>
                风险管理是一项有目的的管理活动，只有目标明确，才能起到有效的作用。否则，风险管理就会流于形式，没有实际意义，也无法评价其效果。
            </p>
            <p>
                风险管理的目标就是要以最小的成本获取最大的安全保障。因此，它不仅仅只是一个安全生产问题，还包括识别风险、评估风险和处理风险，涉及财务、安全、生产、设备、物流、技术等多个方面，是一套完整的方案，也是一个系统工程。
            </p>
            <h4>2、黄金投资市场的风险特征</h4>
            <h5>a.投资市场的广泛性</h5>
            <p>
                风险管理目标与风险管理主体(如生产企业或建设工程的业主)总体目标的一致性。
            </p>
            <h4>b.投资风险存在的客观性</h4>
            <p>
                风险管理的目标就是要以最小的成本获取最大的安全保障。因此，它不仅仅只是一个安全生产问题，还包括识别风险、评估风险和处理风险，涉及财务、安全、生产、设备、物流、技术等多个方面，是一套完整的方案，也是一个系统工程。
            </p>
        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
