<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="#">Home</a>
        </li>

        <li>
        <a href="#">Forms</a>
        </li>
        <li class="active">Dropzone File Upload</li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">
    <div class="page-header">
        <h1>
            Dropzone.js
            <small>
                <i class="icon-double-angle-right"></i>
                Drag &amp; drop file upload with image preview
            </small>
        </h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->

            <div id="dropzone">
                <form action="/upload" class="dropzone">
                    <div class="fallback">
                        <input name="file" type="file" multiple="" />
                    </div>
                </form>
            </div><!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->


<script src="/assets/js/dropzone.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
            try {
                    $(".dropzone").dropzone({
                            paramName: "file", // The name that will be used to transfer the file
                            maxFilesize: 1, // MB

                            addRemoveLinks : true,
                            dictDefaultMessage :
                            '<span class="bigger-150 bolder"><i class="icon-caret-right red"></i> Drop files</span> to upload \
                            <span class="smaller-80 grey">(or click)</span> <br /> \
                            <i class="upload-icon icon-cloud-upload blue icon-3x"></i>'
                            ,
                            dictResponseError: 'Error while uploading file!',

                            //change the previewTemplate to use Bootstrap progress bars
                            previewTemplate: "<div class=\"dz-preview dz-file-preview\">\n  <div class=\"dz-details\">\n    <div class=\"dz-filename\"><span data-dz-name></span></div>\n    <div class=\"dz-size\" data-dz-size></div>\n    <img data-dz-thumbnail />\n  </div>\n  <div class=\"progress progress-small progress-striped active\"><div class=\"progress-bar progress-bar-success\" data-dz-uploadprogress></div></div>\n  <div class=\"dz-success-mark\"><span></span></div>\n  <div class=\"dz-error-mark\"><span></span></div>\n  <div class=\"dz-error-message\"><span data-dz-errormessage></span></div>\n</div>"
                    });
                } catch(e) {
                    alert('Dropzone.js does not support older browsers!');
            }
    });
</script>
