<div class="row relative">
    <div id="market" class="span8" data-rtq data-rtq-option="update-time-format: HH:mm:ss; format-price: true;" >
        <div class="content">
            <ul class="menu first-item" data-market>
                <li class="item active" data-rtq-symbol="XAUUSD" data-efc-symbol="XAUUSD"
                    data-efc-target="#market [data-chart]">
                    <span class="text">黄金</span>
                </li>
                <li class="item" data-rtq-symbol="XAGUSD" data-efc-symbol="XAGUSD"
                    data-efc-target="#market [data-chart]">
                    <span class="text">白银</span>
                </li>
                <li class="item" data-rtq-symbol="USDollarIndex" data-efc-symbol="USDollarIndex"
                    data-efc-target="#market [data-chart]">
                    <span class="text">美元指数</span>
                </li>
                <li class="item" data-rtq-symbol="US10Year" data-efc-symbol="US10Year"
                    data-efc-target="#market [data-chart]" >
                    <span class="text">美债</span>
                </li>
                <li class="item" data-rtq-symbol="USOil" data-efc-symbol="USOil"
                    data-efc-target="#market [data-chart]">
                    <span class="text">原油</span>
                </li>
                <li class="item" data-rtq-symbol="SPX500INDEX" data-efc-symbol="SPX500INDEX"
                    data-efc-target="#market [data-chart]">
                    <span class="text">标普500</span>
                </li>
                <li class="item" data-rtq-symbol="JPN225INDEX" data-efc-symbol="JPN225INDEX"
                    data-efc-target="#market [data-chart]">
                    <span class="text">日经</span>
                </li>
                <li class="item" data-rtq-symbol="UKOil" data-efc-symbol="UKOil"
                    data-efc-target="#market [data-chart]">
                    <span class="text">布油</span>
                </li>
                <li class="item" data-rtq-symbol="Copper" data-efc-symbol="Copper"
                    data-efc-target="#market [data-chart]">
                    <span class="text">铜</span>
                </li>
                <li class="item" data-rtq-symbol="AUTD" data-efc-symbol="Copper"
                    data-efc-target="#market [data-chart]">
                    <span class="text">黄金t+d</span>
                </li>
                <li class="item" data-rtq-symbol="AGTD" data-efc-symbol="Copper"
                    data-efc-target="#market [data-chart]">
                    <span class="text">白银t+d</span>
                </li>
                <li class="item" data-rtq-symbol="TTYXAGUSD" data-efc-symbol="Copper"
                    data-efc-target="#market [data-chart]">
                    <span class="text">天通银</span>
                </li>
                <li class="item" data-rtq-symbol="AU9999" data-efc-symbol="Copper"
                    data-efc-target="#market [data-chart]">
                    <span class="text">黄金9999</span>
                </li>
                <li class="item" data-rtq-symbol="AU9995" data-efc-symbol="Copper"
                    data-efc-target="#market [data-chart]">
                    <span class="text">黄金9995</span>
                </li>
            </ul>
            <script type="text/template" data-rtq-template>
                <div data-trend="<%= trend %>">
                    <h2 class="title"><%= title %></h2>
                    <h3>
                        <span class="price"><%= price %></span>
                        <span class="diff"><%= diff %></span>
                        <span class="diff-pct">(<%= diffPercent %>)</span>
                    </h3>
                    <div class="meta"><%= updateTime %> - 实时数据 CFD. USD 货币 ( <a href="/post/risk">免责声明</a> )</div>
                    <div data-price>
                        <span class="label">昨收：</span><span class="value"><%= prevClose %></span>
                        <span class="label">开盘：</span><span class="value"><%= open %></span>
                        <span class="label">每日涨幅：</span><span class="value"><%= low %> - <%= high %></span>
                    </div>
                </div>
            </script>
            <div data-info data-rtq-dom>
                <h2 class="title">N/A</h2>
                <h3>
                    <span class="price">N/A</span>
                    <span class="diff">N/A</span>
                    <span class="diff-pct">(N/A)</span>
                </h3>
                <div class="meta">N/A ( <a href="/post/risk">免责声明</a> )</div>
                <div data-price>
                    <span class="label">昨收：</span><span class="value">N/A</span>
                    <span class="label">开盘：</span><span class="value">N/A</span>
                    <span class="label">每日涨幅：</span><span class="value">N/A - N/A</span>
                </div>
            </div>
            <div data-chart>
                <div class="toolbar">
                    <div data-efc-target="#market [data-chart]" data-efc-type="candlestick" class="button">K线图</div>
                    <div data-efc-target="#market [data-chart]" data-efc-type="area" class="button active">分时图</div>
                    <div class="line vertical"></div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1"  class="button">1</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="5"  class="button active">5</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="15" class="button">15</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="30" class="button">30</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1H" class="button">1H</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="4H" class="button">4H</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1D" class="button">1D</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1W" class="button">1W</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="MN" class="button">1M</div>
                </div>
                <iframe class="chart" width="590" height="270" 
                    src="<?=$this->escaper->escapeHtmlAttr('http://markets.wallstreetcn.com/embed/hs?symbol=XAUUSD&chartTheme=dark&type=area&bgTheme=dark&width=590&height=270&rows=50&interval=5&newsUrl=http%3a%2f%2fapi.goldtoutiao.com%2fv2%2fpost%3fcid%3d' . $this->tag->config('wscngold', 'chartNewsCategoryId'))?>"></iframe>
            </div>
        </div>
        <div class="content tabpanel">
            <ul class="menu" data-market>
                <li data-toggle="tab" data-tab-index="1" class="tab item active">
                    <span class="text">ETF持仓</span>
                </li>
                <li data-toggle="tab" data-tab-index="2" data-tab-action="cftc" class="tab item" >
                    <span class="text">CFTC持仓</span>
                </li>
                <li data-toggle="tab" data-tab-index="3" class="tab item" >
                    <span class="text">定盘价</span>
                </li>
            </ul>
            <div data-quote>
                <div data-tab-index="1" class="panel active" data-type="etf" data-etf data-etf-option="symbol: GOLD; chart: true;">
                    <div class="chart" data-etf-dom="chart"></div>
                    <script type="text/template" data-etf-template="data">
                        <% for (var i = 0, l = data.length; i < l; i++) { %>
                        <tr>
                            <td><%= data[i].date %></td>
                            <td><%= data[i].etf_oz %></td>
                            <td><%= data[i].etf_ton %></td>
                            <td><%= data[i].price %></td>
                            <td><%= data[i].change %></td>
                        </tr>
                        <% } %>
                    </script>
                    <div class="line"></div>
                    <table class="table">
                        <thead> <tr> <th>日期</th> <th>持仓量（盎司）</th> <th>持仓量（吨）</th> <th>总价值（美元）</th> <th>增减（吨）</th> </tr> </thead>
                        <tbody data-etf-dom="data"></tbody>
                    </table>
                </div>
                <!--chart-width: 560; chart-height: 180;-->
                <div data-tab-index="2" class="panel" data-type="cftc" data-cftc data-cftc-option="symbol: GOLD; chart: true; ">
                    <div class="chart" data-cftc-dom="chart"></div>
                    <script type="text/template" data-cftc-template="data">
                        <% for (var i = 0, l = data.length; i < l; i++) { %>
                        <tr>
                            <td><%= data[i].date %></td>
                            <td><%= data[i].nc_high %></td>
                            <td><%= data[i].nc_low %></td>
                            <td><%= data[i].nc_diff %></td>
                            <td><%= data[i].nc_change %></td>
                            <td><%= data[i].c_high %></td>
                            <td><%= data[i].c_low %></td>
                            <td><%= data[i].op %></td>
                            <td><%= data[i].op_change %></td>
                        </tr>
                        <% } %>
                    </script>
                    <div class="line"></div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th rowspan="2">日期</th>
                            <th colspan="4">非商业性</th>
                            <th colspan="2">商业性</th>
                            <th rowspan="2" class="cell2">未平仓合约</th>
                            <th rowspan="2">未平仓净变化（与上周比）</th>
                        </tr>
                        <tr>
                            <th class="cell1">多头持仓</th><th class="cell1">空头持仓</th><th class="cell2">多空净持仓</th><th>净持仓变化（与上周比）</th>
                            <th class="cell1">多头持仓</th><th class="cell1">空头持仓</th>
                        </tr>

                        </thead>
                        <tbody data-cftc-dom="data"></tbody>
                    </table>
                </div>
                <div data-tab-index="3" class="panel" data-type="fixing" data-fix-price data-fix-price-option="today: true;">
                    <table class="table">
                        <thead class="head">
                        <tr>
                            <th class="cell1">
                                <div class="line double vr right"></div>
                            </th>
                            <th class="cell2">
                                今日黄金定盘价
                            </th>
                            <th class="cell3">
                                <div class="line double vr left"></div>
                                今日白银定盘价
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th class="cell1" rowspan="2">
                                <div class="line double vr right"></div>
                                <div class="label">伦敦定价</div>
                                <div class="text">美元/盎司</div>
                            </th>
                            <td class="cell2">
                                <span class="label">上午定价</span>
                                <span class="price" data-fix-price-value="today-am-gold">- -</span>
                            </td>
                            <td class="cell3" rowspan="2">
                                <div class="line double vr left"></div>
                                <span class="price" data-fix-price-value="today-silver">- -</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="cell2">
                                <div class="line double hr top"></div>
                                <span class="label">下午定价</span>
                                <span class="price" data-fix-price-value="today-pm-gold">- -</span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <script type="text/template" data-fix-price-template>
                        <% var i, l = data.length; %>
                        <% for (i = 0; i < l; i ++) { %>
                        <tr class="item">
                            <td class="cell1"><%= data[i].date %></td>
                            <td class="cell1"><%= data[i].gold_am %></td>
                            <td class="cell1"><%= data[i].gold_pm %></td>
                            <td class="cell2"><div class="line double vr left"></div><%= data[i].silver %></td>
                        </tr>
                        <% } %>
                    </script>
                    <table class="list">
                        <thead>
                        <tr class="head">
                            <th colspan="3">黄金伦敦历史定盘价(美元/盎司）</th>
                            <th class="cell2"><div class="line double vr left"></div>白银伦敦历史定盘价(美元/盎司）</th>
                        </tr>
                        <tr class="label">
                            <th>日期</th>
                            <th>上午定价</th>
                            <th>下午定价</th>
                            <th class="cell2"><div class="line double vr left"></div>定价</th>
                        </tr>
                        </thead>
                        <tbody data-fix-price-dom></tbody>
                        <!--<li class="pagingbar">
                            <div class="button active">1</div>
                            <div class="button">2</div>
                            <div class="button">3</div>
                            <div class="button">4</div>
                            <div class="button">5</div>
                            <div class="button">6</div>
                            <div class="button">7</div>
                            <div class="button">8</div>
                            <div class="button">9</div>
                            <div class="button">10</div>
                            <div class="button" data-action="next-page">下一页 <i class="icon-caret-right"></i></div>
                        </li>-->
                    </table>
                </div>
            </div>
        </div>
        <!--
        <div class="content">
            <ul class="menu" data-market>
                <li class="item active" data-efc-symbol="" data-efc-target="">
                    <span class="text">涨跌榜</span>
                </li>
            </ul>
            <div data-rank>

            </div>
        </div>
        -->
    </div>
    <div id="sidebar" class="span4">
        <div class="title">央行利率</div>
        <ul class="list bank-rate">
            <li class="item row head">
                <div class="span title">央行</div>
                <div class="span rate">利率</div>
                <div class="span date">下次会议</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-us" title="美联储"></span> 美联储</div>
                <div class="span rate">0.00%-0.25%</div>
                <div class="span date">5月01日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-eu" title="欧洲央行"></span> 欧洲央行</div>
                <div class="span rate">0.25%</div>
                <div class="span date">4月03日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-gb" title="英国央行"></span> 英国央行</div>
                <div class="span rate">0.50%</div>
                <div class="span date">4月10日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-jp" title="日本央行"></span> 日本央行</div>
                <div class="span rate">0.10%</div>
                <div class="span date">4月08日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-au" title="澳大利亚联储"></span> 澳大利亚联储</div>
                <div class="span rate">2.5%</div>
                <div class="span date">4月01日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-ch" title="瑞士央行"></span> 瑞士央行</div>
                <div class="span rate">0.00%-0.25%</div>
                <div class="span date">6月19日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-ca" title="加拿大央行"></span> 加拿大央行</div>
                <div class="span rate">1.00%</div>
                <div class="span date">4月16日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-hk" title="香港金融管理局"></span> 香港金融管理局</div>
                <div class="span rate">0.34%</div>
                <div class="span date"></div>
            </li>
        </ul>
        <div class="line type1"></div>
    </div>
</div>
