<div class="row relative">
    <div id="market" class="span8">
        <div class="content">
            <ul class="menu first-item" data-market>
                <li class="item active" data-efc-symbol="XAUUSD" data-efc-target="#market [data-chart]">
                    <span class="text">黄金</span>
                </li>
                <li class="item" data-efc-symbol="XAGUSD" data-efc-target="#market [data-chart]">
                    <span class="text">白银</span>
                </li>
                <li class="item" data-efc-symbol="USDollarIndex" data-efc-target="#market [data-chart]">
                    <span class="text">美元指数</span>
                </li>
                <li class="item" data-efc-symbol="US10Year" data-efc-target="#market [data-chart]">
                    <span class="text">美债</span>
                </li>
                <li class="item" data-efc-symbol="USOil" data-efc-target="#market [data-chart]">
                    <span class="text">原油</span>
                </li>
                <li class="item" data-efc-symbol="SPX500" data-efc-target="#market [data-chart]">
                    <span class="text">标普500</span>
                </li>
                <li class="item" data-efc-symbol="JPN225" data-efc-target="#market [data-chart]">
                    <span class="text">日经</span>
                </li>
                <li class="item" data-efc-symbol="UKOil" data-efc-target="#market [data-chart]">
                    <span class="text">布油</span>
                </li>
                <li class="item" data-efc-symbol="Copper" data-efc-target="#market [data-chart]">
                    <span class="text">铜</span>
                </li>
            </ul>
            <div data-info>
                <h2 class="title">黄金 - Apr 14 (GCJ4)</h2>
                <h3>
                    <span class="price">1,327.19</span>
                    <span class="diff">-4.01</span>
                    <span class="diff-pct">(-0.35%)</span>
                </h3>
                <div class="meta">10:28:06 - 实时数据 CFD. USD 货币 ( 免责声明 )</div>
                <div data-price>
                    <span class="label">昨收：</span><span class="value">1,359.00</span>
                    <span class="label">开盘：</span><span class="value">1,357.00</span>
                    <span class="label">每日涨幅：</span><span class="value">1,355.30 - 1,360.10</span>
                </div>
            </div>
            <div data-chart>
                <div class="toolbar">
                    <div data-efc-target="#market [data-chart]" data-efc-type="k" class="button active">K线图</div>
                    <div data-efc-target="#market [data-chart]" data-efc-type="t" class="button">分时图</div>
                    <div class="line vertical"></div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1"  class="button">1</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="5"  class="button">5</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="15" class="button">15</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="30" class="button active">30</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1H" class="button">1H</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="4H" class="button">4H</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1D" class="button">1D</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="1W" class="button">1W</div>
                    <div data-efc-target="#market [data-chart]" data-efc-interval="MN" class="button">1M</div>
                </div>
                <iframe class="chart" width="590" height="270" scrolling="no" frameborder="0"
                        src="http://markets.wallstreetcn.com/embed/chart?symbol=XAUUSD&theme=dark&width=590&height=270&rows=50&interval=30"></iframe>
            </div>
        </div>
        <div class="content tabpanel">
            <ul class="menu" data-market>
                <li data-toggle="tab" data-tab-index="1" class="tab item active">
                    <span class="text">ETF持仓</span>
                </li>
                <li data-toggle="tab" data-tab-index="2" class="tab item" >
                    <span class="text">CFTC持仓</span>
                </li>
                <li data-toggle="tab" data-tab-index="3" class="tab item" >
                    <span class="text">定盘价</span>
                </li>
            </ul>
            <div data-quote>
                <div data-tab-index="1" class="panel active" data-type="etf">
                    <div class="chart"></div>
                    <div class="line"></div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>日期</th>
                            <th>持仓量（盎司）</th>
                            <th>持仓量（吨）</th>
                            <th>总价值（美元）</th>
                            <th>增减（吨）</th>
                        </tr>
                        <tbody>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        </tbody>
                        </thead>
                    </table>
                </div>
                <div data-tab-index="2" class="panel" data-type="cftc">
                    <div class="chart"></div>
                    <div class="line"></div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>日期</th>
                            <th>持仓量（盎司）</th>
                            <th>持仓量（吨）</th>
                            <th>总价值（美元）</th>
                            <th>增减（吨）</th>
                        </tr>
                        <tbody>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        <tr>
                            <td>2014.03.25</td>
                            <td>2654235.42</td>
                            <td>819.67</td>
                            <td>35656511252.15</td>
                            <td>0.00</td>
                        </tr>
                        </tbody>
                        </thead>
                    </table>
                </div>
                <div data-tab-index="3" class="panel" data-type="fixing">
                    <table class="table">
                        <thead class="head">
                        <tr>
                            <th class="cell1">
                                <div class="line double vr right"></div>
                            </th>
                            <th class="cell2">
                                今日黄金定盘价
                            </th>
                            <th class="cell3">
                                <div class="line double vr left"></div>
                                今日白银定盘价
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th class="cell1" rowspan="2">
                                <div class="line double vr right"></div>
                                <div class="label">伦敦定价</div>
                                <div class="text">美元/盎司</div>
                            </th>
                            <td class="cell2">
                                <span class="label">上午定价</span>
                                <span class="price">1294.00</span>
                            </td>
                            <td class="cell3" rowspan="2">
                                <div class="line double vr left"></div>
                                <span class="price">19.9700</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="cell2">
                                <div class="line double hr top"></div>
                                <span class="label">下午定价</span>
                                <span class="price">1291.75</span>
                            </td>
                        </tr>
                        </tbody>
                    </table>

                    <ul class="list">
                        <li class="head">
                            <div class="cell1">黄金伦敦历史定盘价(美元/盎司）</div>
                            <div class="cell2">白银伦敦历史定盘价(美元/盎司）</div>
                        </li>
                        <li class="label">
                            <div class="cell1">
                                <div class="row">
                                    <div class="span4">日期</div>
                                    <div class="span4">上午定价</div>
                                    <div class="span4">下午定价</div>
                                </div>
                            </div>
                            <div class="cell2">
                                定价
                            </div>
                        </li>
                        <li class="item">
                            <div class="cell1">
                                <div class="row">
                                    <div class="span4">2014-04-25</div>
                                    <div class="span4">1294.00</div>
                                    <div class="span4">1291.75</div>
                                </div>
                            </div>
                            <div class="cell2">
                                19.9700
                            </div>
                        </li>
                        <li class="item">
                            <div class="cell1">
                                <div class="row">
                                    <div class="span4">2014-04-25</div>
                                    <div class="span4">1294.00</div>
                                    <div class="span4">1291.75</div>
                                </div>
                            </div>
                            <div class="cell2">
                                19.9700
                            </div>
                        </li>
                        <li class="item">
                            <div class="cell1">
                                <div class="row">
                                    <div class="span4">2014-04-25</div>
                                    <div class="span4">1294.00</div>
                                    <div class="span4">1291.75</div>
                                </div>
                            </div>
                            <div class="cell2">
                                19.9700
                            </div>
                        </li>
                        <li class="item">
                            <div class="cell1">
                                <div class="row">
                                    <div class="span4">2014-04-25</div>
                                    <div class="span4">1294.00</div>
                                    <div class="span4">1291.75</div>
                                </div>
                            </div>
                            <div class="cell2">
                                19.9700
                            </div>
                        </li>
                        <li class="pagingbar">
                            <div class="button active">1</div>
                            <div class="button">2</div>
                            <div class="button">3</div>
                            <div class="button">4</div>
                            <div class="button">5</div>
                            <div class="button">6</div>
                            <div class="button">7</div>
                            <div class="button">8</div>
                            <div class="button">9</div>
                            <div class="button">10</div>
                            <div class="button" data-action="next-page">下一页 <i class="icon-caret-right"></i></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--
        <div class="content">
            <ul class="menu" data-market>
                <li class="item active" data-efc-symbol="" data-efc-target="">
                    <span class="text">涨跌榜</span>
                </li>
            </ul>
            <div data-rank>

            </div>
        </div>
        -->
    </div>
    <div id="sidebar" class="span4">
        <div class="title">央行利率</div>
        <ul class="list bank-rate">
            <li class="item row head">
                <div class="span title">央行</div>
                <div class="span rate">利率</div>
                <div class="span date">下次会议</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-us" title="美联储"></span> 美联储</div>
                <div class="span rate">0.00%-0.25%</div>
                <div class="span date">5月01日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-eu" title="欧洲央行"></span> 欧洲央行</div>
                <div class="span rate">0.25%</div>
                <div class="span date">4月03日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-gb" title="英国央行"></span> 英国央行</div>
                <div class="span rate">0.50%</div>
                <div class="span date">4月10日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-jp" title="日本央行"></span> 日本央行</div>
                <div class="span rate">0.10%</div>
                <div class="span date">4月08日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-au" title="澳大利亚联储"></span> 澳大利亚联储</div>
                <div class="span rate">2.5%</div>
                <div class="span date">4月01日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-ch" title="瑞士央行"></span> 瑞士央行</div>
                <div class="span rate">0.00%-0.25%</div>
                <div class="span date">6月19日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-ca" title="加拿大央行"></span> 加拿大央行</div>
                <div class="span rate">1.00%</div>
                <div class="span date">4月16日</div>
            </li>
            <li class="item row">
                <div class="span title"><span class="flag flag-hk" title="香港金融管理局"></span> 香港金融管理局</div>
                <div class="span rate">0.34%</div>
                <div class="span date"></div>
            </li>
        </ul>
        <div class="line type1"></div>
    </div>
</div>