<div class="row relative">
    <div class="span8">
        <ul class="menu" data-livenews>
            <li class="item active" data-lnl-type="all" data-lnl-target="#livenews">
                <span class="icon" data-type="all"></span>全部
            </li>
            <li class="item" data-lnl-type="chart" data-lnl-target="#livenews">
                <span class="icon" data-type="chart"></span>行情
            </li>
            <li class="item" data-lnl-type="alert" data-lnl-target="#livenews">
                <span class="icon" data-type="alert"></span>提醒
            </li>
            <!--<li class="item" data-lnl-type="common" data-lnl-target="#livenews">
                <span class="icon" data-type="common"></span>报道
            </li>-->
            <li class="item" data-lnl-type="chart_pie" data-lnl-target="#livenews">
                <span class="icon" data-type="chart_pie"></span>数据
            </li>
            <li class="item" data-lnl-type="rumor" data-lnl-target="#livenews">
                <span class="icon" data-type="rumor"></span>传言
            </li>
            <li class="item" data-lnl-type="warning" data-lnl-target="#livenews">
                <span class="icon" data-type="warning"></span>重磅消息
            </li>
        </ul>
        <div id="livenews" class="livenews list type0 min-height-1000" data-lnl-option="scrollable:false; date-format:YYYY年M月D日，dddd; time-format:LT;">
            <div class="head">
                <span class="text left">直播中 <i class="icon-refresh"></i></span>
                <span class="clock"></span>
                <label class="checkbox right" for="livenews-voice-alert"><i class="icon-volume-up"></i> 声音提醒 <input id="livenews-voice-alert" type="checkbox" value="true"></label>
            </div>
            <ul class="content"></ul>
            <script type="text/template" data-date-template>
                <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                    <h3 class="label"><%= record.date %></h3>
                </li>
            </script>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                    <% var record = records[i]; %>
                    <% if (i == 0 && record.day != day) { %>
                        <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                            <h3 class="label"><%= record.date %></h3>
                        </li>
                    <% } else if (i > 0 && record.day != records[i-1].day) { %>
                        <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                            <h3 class="label"><%= record.date %></h3>
                        </li>
                    <% } %>
                    <% if (i < records.length-1 && (record.day != records[i+1].day)) { %>
                        <li class="item last-of-day <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                    <% } else { %>
                        <li class="item <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                    <% } %>
                        <div class="row">
                            <span class="time left"><%= record.time %></span>
                            <span class="icon right" data-type="<%= record.icon %>"></span>
                        </div>
                        <p class="details"><%= record.title %></p>
                    </li>
                <% } %>
            </script>
            <div class="loader">
                <img class="indicator" src="/img/loader.gif" width="100" height="100" alt=""/>
            </div>
            <div class="toolbar paging"></div>
        </div><!--livenews list end-->
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
