<div class="row relative">
    <div class="span8">
        <ul class="menu" data-livenews>
            <li class="item active" data-lnl-type="all" data-lnl-target="#livenews">
                <span class="icon" data-type="all"></span>全部
            </li>
            <li class="item" data-lnl-type="chart" data-lnl-target="#livenews">
                <span class="icon" data-type="chart"></span>行情
            </li>
            <li class="item" data-lnl-type="alert" data-lnl-target="#livenews">
                <span class="icon" data-type="alert"></span>提醒
            </li>
            <!--<li class="item" data-lnl-type="common" data-lnl-target="#livenews">
                <span class="icon" data-type="common"></span>报道
            </li>-->
            <li class="item" data-lnl-type="chart_pie" data-lnl-target="#livenews">
                <span class="icon" data-type="chart_pie"></span>数据
            </li>
            <li class="item" data-lnl-type="rumor" data-lnl-target="#livenews">
                <span class="icon" data-type="rumor"></span>传言
            </li>
            <li class="item" data-lnl-type="warning" data-lnl-target="#livenews">
                <span class="icon" data-type="warning"></span>重磅消息
            </li>
        </ul>
        <div id="livenews" class="livenews list type0" data-lnl-option="nano:false; date-format:YYYY年M月D日，dddd; time-format:LT;">
            <div class="head">
                <span class="text left">直播中 <i class="icon-refresh"></i></span>
                <span class="clock"></span>
                <label class="checkbox right" for="livenews-voice-alert"><i class="icon-volume-up"></i> 声音提醒 <input id="livenews-voice-alert" type="checkbox" value="true"></label>
            </div>
            <ul class="content">
                <!--
                <li class="date">
                    2014年3月20日，今天
                </li>
                <li class="item">
                    <div class="row">
                        <span class="time left">09:45</span>
                        <span class="icon right" data-type="common"></span>
                    </div>
                    <p class="details">中国石油化工股份有限公司上月和康菲石油旗下Phillips 66签署液化石油气（LPG）长期购销合同显示美国有望成为中国主要的液化石油气供应方之一。</p>
                </li>
                <li class="item">
                    <div class="row">
                        <span class="time left">09:45</span>
                        <span class="icon right" data-type="common"></span>
                    </div>
                    <div class="details">
                        <p>中国石油化工股份有限公司上月和康菲石油旗下Phillips 66签署液化石油气（LPG）长期购销合同显示美国有望成为中国主要的液化石油气供应方之一。</p>
                        <img src="/img/livenews.jpg" alt=""/>
                    </div>
                    <div class="row">
                        <span class="date left">2014年3月21日 12:35</span>
                        <span class="right" data-action="comment">评论（2）</span>
                    </div>
                    <div class="user-comments">
                        <div class="content">
                            <form action="">
                                <textarea class="input" name="user-comment" rows="4"></textarea>
                                <input class="submit" type="submit" value="评论"/>
                            </form>
                            <ul class="list">
                                <li class="item ">
                                    <div class="row">
                                        <div class="span">
                                            <img class="avatar" src="" alt=""/>
                                        </div>
                                        <div class="span">
                                            <h4 class="name">业界良心</h4>
                                            <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                            <div class="row">
                                                <div class="time span">3分钟前</div>
                                                <div class="toolbar right">
                                                    <span class="button">
                                                        <i class="icon-thumbs-up"></i>
                                                        <span class="value">5</span>
                                                    </span>
                                                    <span class="button">
                                                        <i class="icon-thumbs-down"></i>
                                                        <span class="value">5</span>
                                                    </span>
                                                    <span class="button">
                                                        回复（<span>3</span>）
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="item ">
                                    <div class="row">
                                        <div class="span">
                                            <img class="avatar" src="" alt=""/>
                                        </div>
                                        <div class="span">
                                            <h4 class="name">业界良心</h4>
                                            <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                            <div class="row">
                                                <div class="time span">3分钟前</div>
                                                <div class="toolbar right">
                                                    <span class="button">
                                                        <i class="icon-thumbs-up"></i>
                                                        <span class="value">5</span>
                                                    </span>
                                                    <span class="button">
                                                        <i class="icon-thumbs-down"></i>
                                                        <span class="value">5</span>
                                                    </span>
                                                    <span class="button">
                                                        回复（<span>3</span>）
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="item last-child">
                    <div class="row">
                        <span class="time left">09:45</span>
                        <span class="icon right" data-type="alert"></span>
                    </div>
                    <p class="details">中国石油化工股份有限公司上月和康菲石油旗下Phillips 66签署液化石油气（LPG）长期购销合同显示美国有望成为中国主要的液化石油气供应方之一。</p>
                </li>
                <li class="date">
                    2014年3月21日，昨天
                </li>
                <li class="item">
                    <div class="row">
                        <span class="time left">09:45</span>
                        <span class="icon right" data-type="alert"></span>
                    </div>
                    <p class="details">中国石油化工股份有限公司上月和康菲石油旗下Phillips 66签署液化石油气（LPG）长期购销合同显示美国有望成为中国主要的液化石油气供应方之一。</p>
                </li>
                -->
            </ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                    <% var record = records[i]; %>
                    <% if (i == 0 && record.day != day) { %>
                        <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                            <h3 class="label"><%= record.date %></h3>
                        </li>
                    <% } else if (i > 0 && record.day != records[i-1].day) { %>
                        <li class="date" data-date="<%= record.date %>" data-day="<%= record.day %>">
                            <h3 class="label"><%= record.date %></h3>
                        </li>
                    <% } %>
                    <% if (i < records.length-1 && (record.day != records[i+1].day)) { %>
                        <li class="item last-of-day <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                    <% } else { %>
                        <li class="item <%= record.format %> <%= record.color %>" data-nid="<%= record.nid %>" data-timestamp="<%= record.timestamp %>" data-date="<%= record.date %>" data-day="<%= record.day %>">
                    <% } %>
                        <div class="row">
                            <span class="time left"><%= record.time %></span>
                            <span class="icon right" data-type="<%= record.icon %>"></span>
                        </div>
                        <p class="details"><%= record.title %></p>
                    </li>
                <% } %>
            </script>
            <div class="loader">
                <img class="indicator" src="/img/loader.gif" width="100" height="100" alt=""/>
            </div>
            <div class="toolbar paging"></div>
        </div><!--livenews list end-->
    </div>
    <div id="sidebar" class="span4">
        <h2 class="title">财经日历</h2>
        <div id="side-fcl" class="nano finance-calendar scrollable list type1" data-fcl-option="auto-scroll:true;">
            <div class="titlebar">
                据下次数据公布时间还有：<span class="clock"></span>
            </div>
            <ul class="nano-content content"></ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                <% var record = records[i]; %>
                <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                <% } %>
                <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                    <div class="row">
                        <div class="span3 meta">
                            <span class="time"><%= record.time %></span>
                        </div>
                        <div class="span8">
                            <a class="link" href=""><%= record.title %></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3 actual meta">
                            <span class="label">今值：</span>
                            <span class="value"><%= record.actual %></span>
                        </div>
                        <div class="span3 forecast meta">
                            <span class="label">预测：</span>
                            <span class="value"><%= record.forecast %></span>
                        </div>
                        <div class="span3 previous meta">
                            <span class="label">前值：</span>
                            <span class="value"><%= record.previous %></span>
                        </div>
                    </div>
                </li>
                <% } %>
            </script>
        </div>
    </div>
</div>