<?$pagerBaseQuery = $pager->query;?>
<?if($pager->total_pages > 1):?>
<div class="toolbar paging">
    <?if($pager->current > 2):?>
    <a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->first), $pagerBaseQuery)?>"><i class="icon-double-angle-left"></i></a>
    <?endif?>
    <?if($pager->current > 1):?>
    <a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->before), $pagerBaseQuery)?>"><i class="icon-angle-left"></i></a>
    <?endif?>
    <?if(0 && $pager->prev_skip):?>
    <a class="button" href="javascript:;">...</a>
    <?endif?>
    <?if($pager->prev_range):?>
    <?foreach($pager->prev_range as $page):?>
    <a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $page), $pagerBaseQuery)?>"><?=$page?></a>
    <?endforeach?>
    <?endif?>
    <a class="button active" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->current), $pagerBaseQuery)?>"><?=$pager->current?></a>
    
    <?if($pager->next_range):?>
    <?foreach($pager->next_range as $page):?>
    <a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $page), $pagerBaseQuery)?>"><?=$page?></a>
    <?endforeach?>
    <?endif?>
    <?if(0 && $pager->next_skip):?>
    <a class="button" href="javascript:;">...</a>
    <?endif?>
    <?if($pager->next && $pager->current < $pager->last):?>
    <a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->next), $pagerBaseQuery)?>"><i class="icon-angle-right"></i></a>
    <?endif?>
    <?if($pager->current < $pager->last):?>
    <a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->last), $pagerBaseQuery)?>"><i class="icon-double-angle-right"></i></a>
    <?endif?>
</div>
<?endif?>
