<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title><?=$this->placeholder->block('title', '黄金头条');?></title>
        <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <![endif]-->
        <meta name="description" content="<?=$this->placeholder->block('description', '黄金头条');?>">
        <meta name="keywords" content="<?=$this->placeholder->block('keywords', '黄金头条');?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="/js/vendor/modernizr-2.6.2.min.js"></script>

        <link rel="stylesheet" href="/vendor/css/font-awesome.min.css">
        <link rel="stylesheet" href="/vendor/css/flags.css">

        <link rel="stylesheet" href="/css/normalize.css">
        <link rel="stylesheet" href="/css/main.css">

        <link rel="stylesheet" href="/css/datepicker.css">
        <link rel="stylesheet" href="/css/nanoscroller.css">
        <link rel="stylesheet" href="/css/style.css"/>
		<!--[if !IE]> -->
        <script type="text/javascript" src="/vendor/js/jquery-2.0.3.js"></script>
		<!-- <![endif]-->
		<!--[if IE]>
		<script type="text/javascript" src="/vendor/js/jquery-1.10.2.min.js"></script>
        <![endif]-->
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?32947acb2089fae0ab79345dd686bb4a";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
    </head>
    <body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-51287833-1', 'goldtoutiao.com');
  ga('send', 'pageview');
</script>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        
        <div id="header">
            <div class="banner container">
                <div class="row">
                    <h1 class="span3 title">
                        华尔街见闻-黄金头条
                        <a href="/"><img class="logo " src="/img/logo.png" alt=""/></a>
                    </h1>
                    <div class="span9 ad">
                        <script type="text/javascript" >BAIDU_CLB_SLOT_ID = "902869";</script>
                        <script type="text/javascript" src="http://cbjs.baidu.com/js/o.js"></script>
                    </div>
                </div>
            </div>
            <div class="toolbar">
                <div class="container">

                    <ul class="navbar left">
                        <li class="nav"><a class="link" data-active-url="^\/$" href="/">首页</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/news.*$" href="/news">市场新闻</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/livenews.*$" href="/livenews">实时新闻</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/market.*$" href="/market">行情中心</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/calendar.*$" href="/calendar">财经日历</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/techanalysis.*$" href="/techanalysis">技术分析</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/tutorial.*$" href="/tutorial">投资教室</a></li>
                        <li class="nav"><a class="link" data-active-url="^/post/messsageboard" href="/post/messageboard">留言板</a></li>
                    </ul>

                    <div class="right">
                        <form class="search left" action="/news/search">
                            <input class="left" type="text" name="q" />
                            <button class="right" type="submit">
                                <i class="icon-search"></i>
                            </button>
                        </form>
                        <div class="user right" data-popup="user-menu">
                        </div>
                    </div>
                </div>
            </div>
        </div><!--header end-->

        <div id="content" class="container">
            <?=$this->getContent()?>
        </div>

        <div id="footer">
            <div class="container">
                <div class="row">
                    <div class="span3 ">
                        <a href="/"><img class="logo" src="/img/logo.png" alt=""/></a>
                        <img class="qrcode" src="/img/qrcode.png" alt=""/>
                        <p class="copyright">
                        ©2010-2014 黄金头条<br>
                            www.goldtoutiao.com 沪ICP备XXXXXX号
                        </p>
                    </div>
                    <div class="span8 offset1">
                        <div class="row">
                            <div class="span3">
                                <h4 class="title">相关信息</h4>
                                <ul>
                                    <li><a class="link" href="/post/about">关于黄金头条</a></li>
                                    <li><a class="link" href="/post/terms">使用条款</a></li>
                                    <li><a class="link" href="/post/risk">风险披露</a></li>
                                    <li><a class="link" href="/post/copyrightstatement">版权声明</a></li>
                                </ul>
                            </div>
                            <div class="span3">
                                <h4 class="title">联系我们</h4>
                                <ul>
                                    <li><a class="link" href="/post/ad">广告投放</a></li>
                                    <li><a class="link" href="/post/business">商业合作</a></li>
                                    <li><a class="link" href="/post/contact">意见反馈</a></li>
                                </ul>
                            </div>
                            <div class="span3">
                                <h4 class="title">关注我们</h4>
                                <ul>
                                    <li><a class="link" href="http://weibo.com/u/3879517794" target="_blank">微博@黄金头条</a></li>
                                </ul>
                            </div>
                            <div class="span3">
                                <h4 class="title">网站导航</h4>
                                <ul>
                                    <li><a class="link" href="/news">市场新闻</a></li>
                                    <li><a class="link" href="/livenews">实时新闻</a></li>
                                    <li><a class="link" href="/market">行情中心</a></li>
                                    <li><a class="link" href="/calendar">财经日历</a></li>
                                    <li><a class="link" href="/techanalysis">技术分析</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <p>
                                风险提示：黄金头条致力于提供可信赖的消息与数据，但不对任何由于使用本网站内的数据、报价和图表信息可能会造成的损害负责，也不承担其赔偿责任。请对相关投资形式和金融市场的风险和交易的相关成本进行充分了解。贵金属交易涉及风险高，您应该谨慎考虑您的投资目的。该投资并不适合于所有投资者，您应该了解市场分析方法和自己的经验等级。黄金头条特此提醒本网站内的数据不一定是实时数据。所有的股票价格、指数、期货和外汇价格都不是由交易所提供而是由市场专家提供的，因此价格可能为实际价格，也可能与实际市场价格有相差，这意味着价格的指示并不适合用于交易。因此，黄金头条不承担任何按照此价格进行交易所可能蒙受的损失。
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--<script src="/vendor/js/html5shiv.min.js"></script>-->
        <script src="/vendor/js/underscore.min.js"></script>
        <script src="/vendor/js/moment.min.js"></script>
        <script src="/js/vendor/datepicker.js"></script>
        <script src="/js/vendor/jquery.jplayer.min.js"></script>
        <script src="/js/vendor/jquery.nanoscroller.js"></script>
        <script src="/js/vendor/raphael.js"></script>
        <script src="/js/vendor/highcharts.js"></script>

        <script src="/js/plugins.js"></script>

        <script src="/js/tool.js"></script>
        <script src="/js/raphael.chart.circle.js"></script>
        <script src="/js/paging.js"></script>
        <script src="/js/rtq.js"></script>
        <script src="/js/lnl.js"></script>
        <script src="/js/fcl.js"></script>
        <script src="/js/cftc.js"></script>
        <script src="/js/etf.js"></script>
        <script src="/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>

        <!--[if lt IE 9]>
            <script type="text/javascript" src="/js/vendor/firebug-lite.js"></script>
        <![endif]-->

    </body>
</html>
