<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>黄金头条</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" href="/vendor/css/font-awesome.min.css">

        <link rel="stylesheet" href="/css/normalize.css">
        <link rel="stylesheet" href="/css/main.css">

        <link rel="stylesheet" href="/css/datepicker.css">
        <link rel="stylesheet" href="/css/nanoscroller.css">
        <link rel="stylesheet" href="/css/style.css"/>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        
        <div id="header">
            <h1 class="title container">
                华尔街见闻-黄金头条
                <img class="logo " src="/img/logo.png" alt=""/>
                <img class="ad " src="/img/ad/ad01.png" alt=""/>
            </h1>
            <div class="toolbar">
                <div class="container">

                    <ul class="navbar left">
                        <li class="nav"><a class="link" data-active-url="^\/$" href="/">首页</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/news.*$" href="/news">市场新闻</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/livenews.*$" href="/livenews">实时新闻</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/market.*$" href="#">行情中心</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/calendar.*$" href="/calendar">财经日历</a></li>
                        <li class="nav"><a class="link" data-active-url="" href="#">技术分析</a></li>
                        <li class="nav"><a class="link" data-active-url="^\/tutorial.*$" href="/tutorial">投资教室</a></li>
                        <li class="nav"><a class="link" data-active-url="" href="#">留言板</a></li>
                    </ul>

                    <div class="right">
                        <form class="search left" action="/news/search">
                            <input class="left" type="text" name="q" />
                            <button class="right" type="submit">?</button>
                        </form>
                        <div class="user right" data-popup="user-menu">
                        </div>
                    </div>
                </div>
            </div>
        </div><!--header end-->

        <div id="content" class="container">
            <?=$this->getContent()?>
        </div>

        <div id="footer">
            <div class="container">
                <div class="row">
                    <div class="span3 ">
                        <img class="logo" src="/img/logo.png" alt=""/>
                        <img class="qrcode" src="/img/qrcode.png" alt=""/>
                        <p class="copyright">
                            2010-2014 华尔街见闻·黄金头条<br>
                            gold.wallstreetcn.com 沪ICP备13091121号
                        </p>
                    </div>
                    <div class="span8 offset1">
                        <div class="row">
                            <div class="span3">
                                <h4 class="title">相关信息</h4>
                                <ul>
                                    <li><a class="link" href="">关于华尔街见闻</a></li>
                                    <li><a class="link" href="">使用条款</a></li>
                                    <li><a class="link" href="">版权声明</a></li>
                                </ul>
                            </div>
                            <div class="span3">
                                <h4 class="title">联系我们</h4>
                                <ul>
                                    <li><a class="link" href="">广告投放</a></li>
                                    <li><a class="link" href="">商业合作</a></li>
                                    <li><a class="link" href="">意见反馈</a></li>
                                </ul>
                            </div>
                            <div class="span3">
                                <h4 class="title">关注我们</h4>
                                <ul>
                                    <li><a class="link" href="">微博@华尔街见闻</a></li>
                                    <li><a class="link" href="">腾讯微博</a></li>
                                    <li><a class="link" href="">RSS订阅</a></li>
                                    <li><a class="link" href="">邮件订阅</a></li>
                                </ul>
                            </div>
                            <div class="span3">
                                <h4 class="title">加入我们</h4>
                                <ul>
                                    <li><a class="link important" href="">全职岗位</a></li>
                                    <li><a class="link" href="">实习岗位</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <p class="friend-links">
                                <span class="title">友情链接：</span>
                                <a class="link" href="">
                                    hao123 | 新浪财经 | 腾讯财经 | 财经网 | 和讯网 | 一财网 | 华讯财经 | 东方财富网 | 金融界 | 证券之星 | 全景财经 | 看看新闻网 | 中国金融新闻网 | 中国金融信息网 | 中国金融网 | 中华网财经 | 环球外汇网 | 中金在线财经 | 外汇通 | 新财富 | 申银万国期货 | 中国国际期货有限公司 | 中证期货有限公司 | 卓创资讯 | 好买基金网 | 领峰贵金属 | 港股通 | 观察者网 | 丰华财经 | 中国金融理财网 | 隆众石化网 | 银行贷款 | 汇商网 | 瑞星安全网址导航 | 安全网址导航 | 360安全网址导航 | QQ导航 | 2345.com网址导航 | 114啦网址导航 | 抽屉新热榜 | 1616个人门户 | SVS金盛集团 | 头条新闻 | 第九课堂 | 高顿网校 | IBTIMES中文网 | 凤凰财经 | 网站排行榜 | 经济网 | TARGET致品网 | 商业见地网 | 大河网金融频道 | 汇金网 | 汇通网 | 她理财
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="/vendor/js/jquery-1.10.2.min.js"></script>
        <script src="/vendor/js/underscore.min.js"></script>
        <script src="/vendor/js/moment.min.js"></script>
        <script src="/js/vendor/datepicker.js"></script>
        <script src="/js/vendor/jquery.nanoscroller.js"></script>
        <script src="/js/vendor/raphael.js"></script>

        <script src="/js/plugins.js"></script>

        <script src="/js/tool.js"></script>
        <script src="/js/raphael.chart.circle.js"></script>
        <script src="/js/paging.js"></script>
        <script src="/js/mam.js"></script>
        <script src="/js/lnl.js"></script>
        <script src="/js/fcl.js"></script>
        <script src="/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>

        <!--[if lt IE 9]>
            <script type="text/javascript" src="/js/vendor/firebug-lite.js"></script>
        <![endif]-->

    </body>
</html>
