<div class="row relative">
    <div class="span8">
        <div id="main">
            <div class="article page">
                <h2 class="title"><?=$item->title?></h2>
                <div class="info">
                    <span class="item author"><?=$item->username ? $item->username : '黄金头条'?></span>
                    <span class="item time"><?=$this->tag->datetime($item->createdAt)?></span>
                    <span class="item tag"><?if($item->Tags):?>
                        <?foreach($item->Tags as $tag):?>    
                        <?=$tag->tagName?> /
                        <?endforeach?>    
                    <?endif?></span>
                    <!--
                    <span class="item view-times">21256</span>
                    -->
                    <span class="item source right">来源：<a href="<?=$item->sourceUrl ? $item->sourceUrl : '#'?>" target="_blank"><?=$item->sourceName ? $item->sourceName : '黄金头条'?></a></span>
                </div>
                <?if($item->summary):?>
                <div class="summary">
                    摘要：<?=$item->summary?>
                </div>
                <?endif?>
                <div class="content">
                    <?=$item->getContentHtml()?>
                </div>
                <div class="state">
                    本文内容仅供读者参考，并非投资建议。 转载请注明来源并加上本站链接，华尔街见闻将保留所有法律权益。
                    <br/>
                    版权采用 <span class="red">知识共享署名-非商业性使用 3.0</span> 未本地化版本许可协议 进行许可
                </div>
                <div class="toolbar">
                    <!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style_24x24">
                        <a class="jiathis_button_qzone"></a>
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_tqq"></a>
                        <a class="jiathis_button_renren"></a>
                        <a class="jiathis_button_kaixin001"></a>
                        <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank"></a>
                        <a class="jiathis_counter_style"></a>
                    </div>
                    <script type="text/javascript" >
                        var jiathis_config={
                            hideMore:false
                        }
                    </script>
                    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
                    <!-- JiaThis Button END -->
                    <a href="/" class="back">
                        返回黄金头条首页
                    </a>
                </div>
            </div>
            <div class="user-comments">
                <div class="title">评论（<span class="amount">5</span>）</div>
                <div class="content">
                    <form action="">
                        <textarea class="input" name="user-comment" rows="6"></textarea>
                        <input class="submit" type="submit" value="评论"/>
                    </form>
                    <ul class="list">
                        <li class="item">
                            <div class="row">
                                <div class="span">
                                    <img class="avatar" src="" alt=""/>
                                </div>
                                <div class="span">
                                    <h4 class="name">业界良心</h4>
                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                    <div class="row">
                                        <div class="time span">3分钟前</div>
                                        <div class="toolbar right">
                                        <span class="button">
                                            <i class="icon-thumbs-up"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            <i class="icon-thumbs-down"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            回复（<span>3</span>）
                                        </span>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="user-comments">
                                <div class="content">
                                    <form action="">
                                        <textarea class="input" name="user-comment" rows="3"></textarea>
                                        <input class="submit" type="submit" value="评论"/>
                                    </form>
                                    <ul class="list">
                                        <li class="item ">
                                            <div class="row">
                                                <div class="span">
                                                    <img class="avatar" src="" alt=""/>
                                                </div>
                                                <div class="span">
                                                    <h4 class="name">业界良心</h4>
                                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                                    <div class="time span">3分钟前</div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="item ">
                                            <div class="row">
                                                <div class="span">
                                                    <img class="avatar" src="" alt=""/>
                                                </div>
                                                <div class="span">
                                                    <h4 class="name">业界良心</h4>
                                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                                    <div class="time span">3分钟前</div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="row">
                                <div class="span">
                                    <img class="avatar" src="" alt=""/>
                                </div>
                                <div class="span">
                                    <h4 class="name">业界良心</h4>
                                    <p class="comment">从这个角度讲，对于不专业的投资者，采取定投方式进行财富管理是个不错的策略。说实话广告不能少,而且在90%的人不懂手机的情况下，输给花哨、炫丽舍得花大价钱做广告的三星是再正常不过了。</p>
                                    <div class="row">
                                        <div class="time span">3分钟前</div>
                                        <div class="toolbar right">
                                        <span class="button">
                                            <i class="icon-thumbs-up"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            <i class="icon-thumbs-down"></i>
                                            <span class="value">5</span>
                                        </span>
                                        <span class="button">
                                            回复（<span>3</span>）
                                        </span>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="more">显示更多评论</div>
            </div>
        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
