<?$this->placeholder->block('title')->set($this->escaper->escapeHtml($item->title))?>

<div class="row relative">
    <div class="span8">
        <div id="main">
            <div class="article page">
                <h2 class="title"><?=$this->escaper->escapeHtml($item->title)?></h2>
                <div class="info">
                    <span class="item author"><?=$item->username ? $item->username : '黄金头条'?></span>
                    <span class="item time"><?=$this->tag->datetime($item->createdAt)?></span>
                    <span class="item tag"><?if($item->tags):?>
                        <?foreach($item->tags as $tag):?>    
                        <?=$tag->tagName?> /
                        <?endforeach?>    
                    <?endif?></span>
                    <!--
                    <span class="item view-times">21256</span>
                    -->
                    <span class="item source right">来源：<a href="<?=$item->sourceUrl ? $item->sourceUrl : '#'?>" target="_blank"><?=$item->sourceName ? $item->sourceName : '黄金头条'?></a></span>
                </div>
                <?if($item->summary):?>
                <div class="summary">
                    摘要：<?=$item->summary?>
                </div>
                <?endif?>
                <div class="content">
                    <?=$item->getContentHtml()?>
                </div>
                <div class="state">
                    本文内容仅供读者参考，并非投资建议。 转载请注明来源并加上本站链接，黄金头条将保留所有法律权益。
                    <br/>
                    版权采用 <span class="red">知识共享署名-非商业性使用 3.0</span> 未本地化版本许可协议 进行许可
                </div>
                <div class="toolbar">
                    <!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style_24x24">
                        <a class="jiathis_button_qzone"></a>
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_tqq"></a>
                        <a class="jiathis_button_renren"></a>
                        <a class="jiathis_button_kaixin001"></a>
                        <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank"></a>
                        <a class="jiathis_counter_style"></a>
                    </div>
                    <script type="text/javascript" >
                        var jiathis_config={
                            hideMore:false
                        }
                    </script>
                    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
                    <!-- JiaThis Button END -->
                    <a href="/" class="back">
                        返回黄金头条首页
                    </a>
                </div>
            </div>


            <!---- comment begin -->
            <div class="user-comments" id="fos_comment_thread">

            </div>

            <script type="text/javascript">
                // thread id
                var fos_comment_thread_id = 'post_<?=$item->id ?>';

                // api base url to use for initial requests
                var fos_comment_thread_api_base_url = '/thread/';

                // Snippet for asynchronously loading the comments
                (function() {
                    var fos_comment_script = document.createElement('script');
                    fos_comment_script.async = true;
                    fos_comment_script.src = '/js/comments.js';
                    fos_comment_script.type = 'text/javascript';

                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(fos_comment_script);
                })();
            </script>
            <!---- comment end   -->

        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
