<div id="login-box" class="login-box visible widget-box no-border">
    <div class="widget-body">
        <div class="widget-main">
            <h4 class="header blue lighter bigger">
                <i class="icon-coffee green"></i>
                Please Confrim Information
            </h4>

            <div class="space-6"></div>

            <form action="/auth/register" method="POST">
                <fieldset>
                    <label class="block clearfix">
                        <span class="block input-icon input-icon-right">
                            <input type="email" name="email" class="form-control" placeholder="Email" />
                            <i class="icon-envelope"></i>
                        </span>
                    </label>

                    <label class="block clearfix">
                        <span class="block input-icon input-icon-right">
                            <input type="text" name="username" class="form-control" placeholder="Username" />
                            <i class="icon-user"></i>
                        </span>
                    </label>


            <div class="social-or-login center">
                <span class="bigger-110">Your account will be connected to <?=$token['adapterKey']?></span>
            </div>

                    <div class="space"></div>

                    <div class="clearfix">

                        <button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
                            <i class="icon-exchange"></i>
                            Connect
                        </button>
                    </div>

                    <div class="space-4"></div>
                </fieldset>
            </form>

        </div><!-- /widget-main -->


    </div><!-- /widget-body -->
</div><!-- /login-box -->
