<?
function getSuggest($input) {
    $input = strtolower($input);
    return strpos($input, 'buy') === false ? '出售' : '购买';
};
function getSuggestClass($input) {
    $input = strtolower($input);
    return strpos($input, 'buy') === false ? 'text-red' : 'text-green';
}
?>
<div class="row relative">
    <div class="span8">
        <div id="tech-analysis" class="min-height-1000">
            <div class="titlebar">
                <?foreach($quotes as $quoteinfo):?>
                <a class="nav" href="/techanalysis/<?=$quoteinfo->symbol?>" data-ma-target="#tech-analysis" data-symbol="<?=$quoteinfo->symbol?>" ><?=$quoteinfo->title?></a>
                <?endforeach?>
            </div>
            <script type="text/template" data-template-target="#tech-analysis .datum">
                <div data-trend="<%= trend %>">
                    <h3 class="title"><%= title %></h3>
                    <span class="update-time"><%= updateTime %></span>
                    <h4 class="row">
                        <span class="price"><%= price %></span>
                        <span class="diff"><%= diff %></span>
                        <span class="diff-pct"><%= diffPercent %></span>
                    </h4>
                    <div class="info row">
                        <span class="meta"></span>
                        <span class="label">昨收：</span>
                        <span class="value"><%= prevClose %></span>
                        <span class="label">开盘：</span>
                        <span class="value"><%= open %></span>
                        <div class="right">
                            <span class="label">每日幅度</span>
                            <span class="value"></span>
                        </div>
                    </div>
                </div>
            </script>
            <div class="datum">
                <div data-trend="up">
                    <h3 class="title"><?=$quote->title?></h3>
                    <h4 class="row">
                        <span class="price">N/A</span>
                        <span class="diff">N/A</span>
                        <span class="diff-pct">N/A</span>
                    </h4>
                    <div class="info row">
                        <span class="meta">N/A ( <a href="#">免责声明</a> )</span>
                        <span class="label">昨收：</span>
                        <span class="value">N/A</span>
                        <span class="label">开盘：</span>
                        <span class="value">N/A</span>
                        <div class="right">
                            <span class="label">每日幅度</span>
                            <span class="value">N/A - N/A</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tabpanel">
                <div class="tabbar">
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/1m">1分钟</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/5m">5分钟</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/15m">15分钟</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/30m">30分钟</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>">每小时</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/5h">5小时</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/1d">每日</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/mn">每月</a>
                </div>
                <ul class="content">
                    <li class="panel"></li>
                    <li class="panel"></li>
                    <li class="panel"></li>
                    <li class="panel"></li>
                    <li class="panel active">
                        <table class="table">
                            <tbody>
                            <tr>
                                <td class="text-bold">移动平均指数:</td>
                                <td class="text-red"><?=getSuggest($data['summary']['datas']['MovingAverages']['action'])?></td>
                                <td>购买（<?=$data['summary']['datas']['MovingAverages']['buy']?>）</td>
                                <td>出售（<?=$data['summary']['datas']['MovingAverages']['sell']?>）</td>
                            </tr>
                            <tr>
                                <td class="text-bold">技术指标:</td>
                                <td class="text-red"><?=getSuggest($data['summary']['datas']['TechnicalIndicators']['action'])?></td>
                                <td>购买（<?=$data['summary']['datas']['TechnicalIndicators']['buy']?>）</td>
                                <td>出售（<?=$data['summary']['datas']['TechnicalIndicators']['sell']?>）</td>
                            </tr>
                            <tr>
                                <td class="text-bold">建议:</td>
                                <td class="text-red"><?=getSuggest($data['summary']['conclusion']['action'])?></td>
                                <td></td>
                                <td></td>
                            </tr>
                            </tbody>
                        </table>
                        <h2 class="main-title">枢轴点</h2>
                        <table class="table">
                            <tbody>
                            <tr>
                                <td class="text-blue" colspan="8"><?=$this->tag->datetime($data['updateTime'])?></td>
                            </tr>
                            <tr>
                                <th>名称</th>
                                <th class="width-50 text-right">S1</th>
                                <th class="width-50 text-right">S2</th>
                                <th class="width-50 text-right">S3</th>
                                <th class="width-50 text-right text-blue">轴点</th>
                                <th class="width-50 text-right">R1</th>
                                <th class="width-50 text-right">R2</th>
                                <th class="width-50 text-right">R3</th>
                            </tr>
                            <?foreach($data['pivotPoints']['datas'] as $point):?>
                            <tr>
                                <td class="text-gray"><?=$point['name']?></td>
                                <td class="width-50 text-right"><?=$point['s1']?></td>
                                <td class="width-50 text-right"><?=$point['s2']?></td>
                                <td class="width-50 text-right"><?=$point['s3']?></td>
                                <td class="width-50 text-right text-blue"><?=$point['pivotPoints']?></td>
                                <td class="width-50 text-right"><?=$point['r1']?></td>
                                <td class="width-50 text-right"><?=$point['r2']?></td>
                                <td class="width-50 text-right"><?=$point['r3']?></td>
                            </tr>
                            <?endforeach?>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="span width-355">
                                <h2 class="main-title">技术指标</h2>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <td class="text-blue" colspan="3"><?=$this->tag->datetime($data['updateTime'])?></td>
                                    </tr>
                                    <tr>
                                        <th>符号</th>
                                        <th class="width-50 text-right">价值</th>
                                        <th class="width-50 text-right">操作</th>
                                    </tr>
                                    <?foreach($data['technicalIndicators']['datas'] as $point):?>
                                    <tr>
                                        <td><?=$point['symbol']?></td>
                                        <td class="width-50 text-right"><?=$point['value']?></td>
                                        <td class="width-50 text-right"><?=$point['action']?></td>
                                    </tr>
                                    <?endforeach?>
                                    <tr>
                                        <td  colspan="3">购买(<?=$data['technicalIndicators']['conclusion']['buy']?>) 出售(<?=$data['technicalIndicators']['conclusion']['sell']?>) 中性(<?=$data['technicalIndicators']['conclusion']['neutral']?>)</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">建议：<?=$data['technicalIndicators']['conclusion']['summary']?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="span width-355 right">
                                <h2 class="main-title">移动平均指数</h2>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <td class="text-blue" colspan="3"><?=$this->tag->datetime($data['updateTime'])?></td>
                                    </tr>
                                    <tr>
                                        <th>日期</th>
                                        <th class="width-50 text-right">标准</th>
                                        <th class="width-50 text-right">移动</th>
                                    </tr>
                                    <?foreach($data['movingAverages']['datas'] as $point):?>
                                    <tr>
                                        <td><?=$point['period']?></td>
                                        <td class="width-50 text-right"><?=$point['simpleValue']?>
                                            <br/><span class="text-green"><?=$point['simpleAction']?></span>
                                        </td>
                                        <td class="width-50 text-right"><?=$point['exponentialValue']?>
                                            <br/><span class="text-green"><?=$point['exponentialAction']?></span>
                                        </td>
                                    </tr>
                                    <?endforeach?>
                                    <tr>
                                        <td  colspan="3">购买(<?=$data['movingAverages']['conclusion']['buy']?>) 出售(<?=$data['movingAverages']['conclusion']['sell']?>) </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">建议：<?=$data['movingAverages']['conclusion']['summary']?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </li>
                    <li class="panel"></li>
                    <li class="panel"></li>
                    <li class="panel"></li>
                </ul>
            </div>
        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
