<?
function getSuggest($input) {
    return $input;
};
function getSuggestClass($input) {
    $input = strtolower($input);
    if(strpos($input, '买') !== false) {
        return 'text-green';
    } elseif (strpos($input, '卖') !== false) {
        return 'text-red';
    } else {
        return 'text-gray';
    }
}
?>
<div class="row relative">
    <div class="span8">
        <div id="tech-analysis" data-rtq data-rtq-option="update-time-format: HH:mm:ss; format-price: true; symbol-event: false; default-symbol: XAUUSD;" class="min-height-1000">
            <div class="titlebar">
                <?foreach($quotes as $quoteinfo):?>
                <a class="nav" href="/techanalysis/<?=$quoteinfo->symbol?>" data-rtq-symbol="<?=$quoteinfo->symbol?>" ><?=$quoteinfo->title?></a>
                <?endforeach?>
            </div>
            <script type="text/template" data-rtq-template>
                <div data-trend="<%= trend %>">
                    <h3 class="title"><%= title %></h3>
                    <p class="meta">数据来源：investing.com ( <a href="/post/risk">免责声明</a> )</p>
                    <div class="row relative price">
                        <h4 class="left">
                            <span class="current"><%= price %></span>
                            <span class="diff"><%= diff %></span>
                            <span class="diff-pct"><%= diffPercent %></span>
                        </h4>
                        <div class="absolute right bottom">
                            <span class="label">昨收：</span>
                            <span class="value"><%= prevClose %></span>
                            <span class="label">开盘：</span>
                            <span class="value"><%= open %></span>
                            <span class="label">每日幅度</span>
                            <span class="value"><%= low %> - <%= high %></span>
                        </div>
                    </div>
                </div>
            </script>
            <div class="datum" data-rtq-dom>
                <div data-trend="">
                    <h3 class="title"><?=$quote->title?></h3>
                    <p class="meta">N/A ( <a href="/post/risk">免责声明</a> )</p>
                    <div class="row relative price">
                        <h4 class="left">
                            <span class="current">N/A</span>
                            <span class="diff">N/A</span>
                            <span class="diff-pct">N/A</span>
                        </h4>
                        <div class="absolute right bottom">
                            <span class="label">昨收：</span>
                            <span class="value">N/A</span>
                            <span class="label">开盘：</span>
                            <span class="value">N/A</span>
                            <span class="label">每日幅度</span>
                            <span class="value">N/A - N/A</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tabpanel">
                <div class="tabbar">
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/1m">1分钟</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/5m">5分钟</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/15m">15分钟</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/30m">30分钟</a>
                    <a class="tab active" href="/techanalysis/<?=$quote->symbol?>">每小时</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/5h">5小时</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/1d">每日</a>
                    <a class="tab" href="/techanalysis/<?=$quote->symbol?>/mn">每月</a>
                </div>
                <ul class="content">
                    <?foreach($dataArray as $periodkey => $data):?>
                    <li class="panel <?=$periodkey == 'period1h' ? 'active' : ''?>">
                    <?if($data):?>
                        <table class="table">
                            <tbody>
                            <tr>
                                <td class="text-bold">建议:</td>
                                <td>
                                    <span class="<?=getSuggestClass($data['summary']['conclusion']['action'])?> with-bg">
                                        <?=getSuggest($data['summary']['conclusion']['action'])?>
                                    </span>
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="text-bold">移动平均指数:</td>
                                <td class="<?=getSuggestClass($data['summary']['datas']['MovingAverages']['action'])?>"><?=getSuggest($data['summary']['datas']['MovingAverages']['action'])?></td>
                                <td>购买（<?=$data['summary']['datas']['MovingAverages']['buy']?>）</td>
                                <td>出售（<?=$data['summary']['datas']['MovingAverages']['sell']?>）</td>
                            </tr>
                            <tr>
                                <td class="text-bold">技术指标:</td>
                                <td class="<?=getSuggestClass($data['summary']['datas']['TechnicalIndicators']['action'])?>"><?=getSuggest($data['summary']['datas']['TechnicalIndicators']['action'])?></td>
                                <td>购买（<?=$data['summary']['datas']['TechnicalIndicators']['buy']?>）</td>
                                <td>出售（<?=$data['summary']['datas']['TechnicalIndicators']['sell']?>）</td>
                            </tr>
                            </tbody>
                        </table>
                        <h2 class="main-title">枢轴点</h2>
                        <table class="table">
                            <tbody>
                            <tr>
                                <td class="text-blue" colspan="8"><?=$this->tag->datetime($data['updateTime'])?></td>
                            </tr>
                            <tr>
                                <th>名称</th>
                                <th class="width-50 text-right">S1</th>
                                <th class="width-50 text-right">S2</th>
                                <th class="width-50 text-right">S3</th>
                                <th class="width-50 text-right text-blue">轴点</th>
                                <th class="width-50 text-right">R1</th>
                                <th class="width-50 text-right">R2</th>
                                <th class="width-50 text-right">R3</th>
                            </tr>
                            <?foreach($data['pivotPoints']['datas'] as $point):?>
                            <tr>
                                <td class="text-gray"><?=$point['name']?></td>
                                <td class="width-50 text-right"><?=$point['s1']?></td>
                                <td class="width-50 text-right"><?=$point['s2']?></td>
                                <td class="width-50 text-right"><?=$point['s3']?></td>
                                <td class="width-50 text-right text-blue"><?=$point['pivotPoints']?></td>
                                <td class="width-50 text-right"><?=$point['r1']?></td>
                                <td class="width-50 text-right"><?=$point['r2']?></td>
                                <td class="width-50 text-right"><?=$point['r3']?></td>
                            </tr>
                            <?endforeach?>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="span width-355">
                                <h2 class="main-title">技术指标</h2>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <td class="text-blue" colspan="3"><?=$this->tag->datetime($data['updateTime'])?></td>
                                    </tr>
                                    <tr>
                                        <th>符号</th>
                                        <th class="width-50 text-right">价值</th>
                                        <th class="width-50 text-right">操作</th>
                                    </tr>
                                    <?foreach($data['technicalIndicators']['datas'] as $point):?>
                                    <tr>
                                        <td><?=$point['symbol']?></td>
                                        <td class="width-50 text-right"><?=$point['value']?></td>
                                        <td class="width-50 text-right <?=getSuggestClass($point['action'])?>"><?=$point['action']?></td>
                                    </tr>
                                    <?endforeach?>
                                    <tr>
                                        <td colspan="3">
                                            <?$buy = $data['technicalIndicators']['conclusion']['buy']; $sell = $data['technicalIndicators']['conclusion']['sell']; $nueutral = $data['technicalIndicators']['conclusion']['neutral']?>

                                            <div class="row">
                                                <div class="indicator text-left border-green" style="width: <?=$buy / ($buy + $sell + $nueutral) * 100?>%"><?=$buy?></div>
                                                <div class="indicator text-center border-gray" style="width: <?=$nueutral / ($buy + $sell + $nueutral) * 100?>%"><?=$nueutral?></div>
                                                <div class="indicator text-right border-red" style="width: <?=$sell / ($buy + $sell + $nueutral) * 100?>%"><?=$sell?></div>
                                            </div>
                                            <div class="indicator-info">
                                                <span class="icon bg-green"></span>
                                                <span class="text">买入</span>
                                                <span class="icon bg-gray"></span>
                                                <span class="text">中性</span>
                                                <span class="icon bg-red"></span>
                                                <span class="text">卖出</span>
                                                <div class="text-bold right">
                                                    <span class="text-gray">建议：</span>
                                                    <span class="<?=getSuggestClass($data['technicalIndicators']['conclusion']['summary'])?>"><?=$data['technicalIndicators']['conclusion']['summary']?></span>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="span width-355 right">
                                <h2 class="main-title">移动平均指数</h2>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <td class="text-blue" colspan="3"><?=$this->tag->datetime($data['updateTime'])?></td>
                                    </tr>
                                    <tr>
                                        <th>日期</th>
                                        <th class="width-50 text-right">标准</th>
                                        <th class="width-50 text-right">移动</th>
                                    </tr>
                                    <?foreach($data['movingAverages']['datas'] as $point):?>
                                    <tr>
                                        <td><?=$point['period']?></td>
                                        <td class="width-50 text-right">
                                            <div><?=$point['simpleValue']?></div>
                                            <div class="<?=getSuggestClass($point['simpleAction'])?>"><?=$point['simpleAction']?></div>
                                        </td>
                                        <td class="width-50 text-right">
                                            <div><?=$point['exponentialValue']?></div>
                                            <div class="<?=getSuggestClass($point['exponentialAction'])?>"><?=$point['exponentialAction']?></div>
                                        </td>
                                    </tr>
                                    <?endforeach?>
                                    <tr>
                                        <td colspan="3">
                                            <div class="row">
                                                <?$buy = $data['movingAverages']['conclusion']['buy']; $sell = $data['movingAverages']['conclusion']['sell'];?>
                                                <div class="indicator text-left border-green" style="width: <?=$buy / ($buy + $sell) * 100?>%"><?=$buy?></div>
                                                <div class="indicator text-right border-red" style="width: <?=$sell / ($buy + $sell) * 100?>%"><?=$sell?></div>
                                            </div>
                                            <div class="indicator-info">
                                                <span class="icon bg-green"></span>
                                                <span class="text">买入</span>
                                                <span class="icon bg-red"></span>
                                                <span class="text">卖出</span>
                                                <div class="text-bold right">
                                                    <span class="text-gray">建议：</span>
                                                    <span class="<?=getSuggestClass($data['movingAverages']['conclusion']['summary'])?>"><?=$data['movingAverages']['conclusion']['summary']?></span>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    <?endif?>
                    </li>
                    <?endforeach?>
                </ul>
            </div>
        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
