
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("users/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("users", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit users</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="mobile">Mobile</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("mobile", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("status")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="flag">Flag</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("flag", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="screenName">ScreenName</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("screenName", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="salt">Salt</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("salt", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="firstName">FirstName</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("firstName", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastName">LastName</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastName", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="oldPassword">OldPassword</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("oldPassword", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastUpdateTime">LastUpdateTime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastUpdateTime", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gender">Gender</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("gender")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar_id">Avatar</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar">Avatar</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="timezone">Timezone</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("timezone", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="registerTime">RegisterTime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("registerTime", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastLoginTime">LastLoginTime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastLoginTime", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="language">Language</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("language", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="setting">Setting</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("setting", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="inviteUserId">InviteUserId</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("inviteUserId", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="onlineStatus">OnlineStatus</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("onlineStatus")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastFreshTime">LastFreshTime</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastFreshTime", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="viewCount">ViewCount</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("viewCount", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="registerIp">RegisterIp</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("registerIp", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastLoginIp">LastLoginIp</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastLoginIp", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
