<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="#">Home</a>
        </li>

        <li>
        <a href="#">Forms</a>
        </li>
        <li class="active">Wysiwyg &amp; Markdown</li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">
    <div class="page-header">
        <h1>Wysiwyg &amp; Markdown Editor </h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->

            <h4 class="header green clearfix">
                Bootstrap Lightweight Editor
                <span class="block pull-right">
                    <small class="grey middle">Choose style: &nbsp;</small>

                    <span class="btn-toolbar inline middle no-margin">
                        <span data-toggle="buttons" class="btn-group no-margin">
                            <label class="btn btn-sm btn-yellow">
                                1
                                <input type="radio" value="1" />
                            </label>

                            <label class="btn btn-sm btn-yellow active">
                                2
                                <input type="radio" value="2" />
                            </label>

                            <label class="btn btn-sm btn-yellow">
                                3
                                <input type="radio" value="3" />
                            </label>
                        </span>
                    </span>
                </span>
            </h4>

            <div class="wysiwyg-editor" id="editor1"></div>

            <div class="hr hr-double dotted"></div>
            </div>

            <script type="text/javascript">
                var $path_assets = "assets";//this will be used in loading jQuery UI if needed!
            </script>

            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
