<div class="row relative">
    <div class="span8">
        <div id="main">
            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 1 ,'limit' => 11));$posts = $pager->items?>
            <?$post = $posts[0]; unset($posts[0]);?>
            <div class="row">
                <ul class="topnews carousel type1 left">
                    <li class="item">
                        <a class="link" href="/post/<?=$post->slug?>">
                            <img class="img" src="/img/img01.png" alt=""/>
                            <h3 class="title"><?=$post->title?></h3>
                        </a>
                    </li>
                </ul>
                <ul class="topnews list type1 right">
                    <li class="title"><h2>头条新闻</h2></li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$post->title?> <span class="time"><?=$this->tag->datetime($post->createdAt, 'H:m')?></span></a></li>
                    <?endforeach?>
                </ul>
            </div>
            <div class="row">
                <h2 class="main-title type1">编辑推荐</h2>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 2 ,'limit' => 3));$posts = $pager->items?>
                <ul class="recommend-news list">
                    <?foreach($posts as $post):?>
                    <li class="item">
                    <a class="link" href="/post/<?=$post->slug?>">
                        <img class="img" src="/img/img01.png" alt=""/>
                        <h3 class="title"><?=$post->title?></h3>
                        </a>
                        <p class="info">by <?=$post->username ? $post->username : '黄金头条'?> <?=$this->tag->datetime($post->createdAt)?></p>
                    </li>
                    <?endforeach?>
                </ul>
            </div>
            <div class="row">
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 3 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list left">
                    <li class="title">黄金要闻</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$post->title?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list">MORE &gt;&gt;</a></li>
                </ul>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 4 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list right">
                    <li class="title">白银要闻</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$post->title?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list">MORE &gt;&gt;</a></li>
                </ul>
            </div>
            <div class="row">
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 5 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list left">
                    <li class="title">机构分析</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$post->title?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list">MORE &gt;&gt;</a></li>
                </ul>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 6 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list right">
                    <li class="title">全球要闻</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$post->title?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list">MORE &gt;&gt;</a></li>
                </ul>
            </div>
        </div>

    </div>
    <div id="sidebar" class="span4">
        <h2 class="title">财经日历</h2>
        <div id="side-fcl" class="nano finance-calendar scrollable list type1" data-fcl-option="auto-scroll:true;">
            <div class="titlebar">
                据下次数据公布时间还有：<span class="clock"></span>
            </div>
            <ul class="nano-content content">
                <li class="more"></li>
            </ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                <% var record = records[i]; %>
                <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                <% } %>
                <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                    <div class="row">
                        <div class="span3 meta">
                            <span class="time"><%= record.time %></span>
                        </div>
                        <div class="span8">
                            <a class="link" href="/post/1"><%= record.title %></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3 actual meta">
                            <span class="label">今值：</span>
                            <span class="value"><%= record.actual %></span>
                        </div>
                        <div class="span3 forecast meta">
                            <span class="label">预测：</span>
                            <span class="value"><%= record.forecast %></span>
                        </div>
                        <div class="span3 previous meta">
                            <span class="label">前值：</span>
                            <span class="value"><%= record.previous %></span>
                        </div>
                    </div>
                </li>
                <% } %>
            </script>
        </div> <!-- side-fcl end -->
        <div class="line type1"></div>
    </div>
</div>
