<div class="row relative">
    <div class="span8">
        <div id="main">
            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 1 ,'limit' => 11));$posts = $pager->items?>
            <?$post = $posts->getFirst();?>
            <div class="row">
                <?if($post):?>
                <ul class="topnews carousel type1 left">
                    <li class="item">
                        <a class="link" href="/post/<?=$post->slug?>">
                            <img class="img" src="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_356,w_400') : '/img/article.jpg'?>" alt=""/>
                            <h3 class="title"><?=$this->escaper->escapeHtmlAttr($post->title)?></h3>
                        </a>
                    </li>
                </ul>
                <?endif?>
                <ul class="topnews list type1 right">
                    <li class="title"><h2>头条新闻</h2></li>
                    <?foreach($posts as $key => $post):?>
                    <?if($key > 0):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtmlAttr($post->title)?> <span class="time"><?=$this->tag->datetime($post->createdAt, 'H:m')?></span></a></li>
                    <?endif?>
                    <?endforeach?>
                </ul>
            </div>
            <div class="row">
                <h2 class="main-title type1">编辑推荐</h2>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 2 ,'limit' => 3));$posts = $pager->items?>
                <ul class="recommend-news list">
                    <?foreach($posts as $post):?>
                    <li class="item">
                    <a class="link" href="/post/<?=$post->slug?>">
                        <img class="img" src="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_150,w_230') : '/img/article.jpg'?>" alt=""/>
                        <h3 class="title"><?=$post->title?></h3>
                        </a>
                        <p class="info">by <?=$post->username ? $post->username : '黄金头条'?> <?=$this->tag->datetime($post->createdAt)?></p>
                    </li>
                    <?endforeach?>
                </ul>
            </div>
            <div class="row">
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 3, 'limit' => 7));$posts = $pager->items?>
                <ul class="news list left">
                    <li class="title">黄金要闻</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtmlAttr($post->title)?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list?cid=3">更多 &gt;&gt;</a></li>
                </ul>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 4 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list right">
                    <li class="title">白银要闻</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtmlAttr($post->title)?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list?cid=4">更多 &gt;&gt;</a></li>
                </ul>
            </div>
            <div class="row">
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 5 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list left">
                    <li class="title">投行观点</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtmlAttr($post->title)?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list?cid=5">更多 &gt;&gt;</a></li>
                </ul>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 6 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list right">
                    <li class="title">全球要闻</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtmlAttr($post->title)?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list?cid=6">更多 &gt;&gt;</a></li>
                </ul>
            </div>
            <!-- todo 新增栏目  修改cid -->
            <div class="row">
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 8 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list left">
                    <li class="title">机构金评</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtmlAttr($post->title)?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list?cid=5">更多 &gt;&gt;</a></li>
                </ul>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 13 ,'limit' => 7));$posts = $pager->items?>
                <ul class="news list right">
                    <li class="title">投资心得</li>
                    <?foreach($posts as $post):?>
                    <li class="item"><a class="link" href="/post/<?=$post->slug?>"><?=$this->escaper->escapeHtmlAttr($post->title)?></a></li>
                    <?endforeach?>
                    <li class="more"><a class="link" href="/news/list?cid=13">更多 &gt;&gt;</a></li>
                </ul>
            </div>
        </div>

    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
