<div class="row relative">
    <div class="span8">
        <div id="main">
            <div class="search-result list">
                <h2 class="title">市场新闻 
                    <?if(!empty($category)):?>
                    &gt; <span class="tag"><?=$category->categoryName?></span>
                    <?endif?>
                </h2>
                <ul class="content">
                <?$items = $pager->items;?>
                <?foreach($items as $item):?>
                    <li class="item">
                    <a class="title" href="/post/<?=$item->slug?>"><?=$item->title?></a>
                        <div class="info">
                            <span class="tag"><?=$item->username ? $item->username : '黄金头条'?></span>
                            <span class="time"><?=$this->tag->datetime($item->createdAt)?></span>
                            <?if($item->tags):?>
                            <span class="tag">
                                <?foreach($item->tags as $tag):?>
                                <?=$tag->tagName?>
                                <?endforeach?>
                            </span>
                            <?endif?>
                        </div>
                        <p class="summary">
                        <?if($item->summary):?>
                        <?=$item->getSummaryHtml()?>
                        <?endif?>
                        </p>
                    </li>
                <?endforeach?>
                </ul>
                <?$this->partial("partial/paginator", array(
                    'pagerUrl' => '/news/list',
                    'pager' => $pager,
                ))?>
            </div>
        </div>
    </div>
    <?$this->partial("partial/sidebar", array())?>
</div>
