<div class="row relative">
    <div class="span8">
        <div id="main">
            <div class="search-result list">
                <h2 class="title">市场新闻 
                    <?if(!empty($category)):?>
                    &gt; <span class="tag"><?=$category->categoryName?></span>
                    <?endif?>
                </h2>
                <ul class="content">
                <?$items = $pager->items;?>
                <?foreach($items as $item):?>
                    <li class="item">
                    <a class="title" href="/post/<?=$item->slug?>"><?=$item->title?></a>
                        <div class="info">
                            <span class="tag"><?=$item->username ? $item->username : '黄金头条'?></span>
                            <span class="time"><?=$this->tag->datetime($item->createdAt)?></span>
                            <?if($item->Tags):?>
                            <span class="tag">
                                <?foreach($item->Tags as $tag):?>
                                <?=$tag->tagName?>
                                <?endforeach?>
                            </span>
                            <?endif?>
                        </div>
                        <p class="summary">
                        <?if($item->summary):?>
                        <?=$item->getSummaryHtml()?>
                        <?endif?>
                        </p>
                    </li>
                <?endforeach?>
                </ul>
                <?$this->partial("partial/paginator", array(
                    'pagerUrl' => '/news/list',
                    'pager' => $pager,
                ))?>
            </div>
        </div>
    </div>
    <div id="sidebar" class="span4">
        <h2 class="title">财经日历</h2>
        <div id="side-fcl" class="nano finance-calendar scrollable list type1" data-fcl-option="auto-scroll:true;">
            <div class="titlebar">
                据下次数据公布时间还有：<span class="clock"></span>
            </div>
            <ul class="nano-content content">
                <li class="more"></li>
            </ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                <% var record = records[i]; %>
                <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                <% } %>
                <li id="<%= record.id %>" class="item" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                    <div class="row">
                        <div class="span3 meta">
                            <span class="time"><%= record.time %></span>
                        </div>
                        <div class="span8">
                            <a class="link" href=""><%= record.title %></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3 actual meta">
                            <span class="label">今值：</span>
                            <span class="value"><%= record.actual %></span>
                        </div>
                        <div class="span3 forecast meta">
                            <span class="label">预测：</span>
                            <span class="value"><%= record.forecast %></span>
                        </div>
                        <div class="span3 previous meta">
                            <span class="label">前值：</span>
                            <span class="value"><%= record.previous %></span>
                        </div>
                    </div>
                </li>
                <% } %>
            </script>
        </div>
        <div class="line type1"></div>
    </div>
</div>
