<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Admin</title>

		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- basic styles -->

		<link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="/assets/css/font-awesome.min.css" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="/assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<!-- page specific plugin styles -->

		<link rel="stylesheet" href="/assets/css/jquery-ui-1.10.3.custom.min.css" />

		<!-- fonts -->

		<link rel="stylesheet" href="/assets/css/ace-fonts.css" />

		<!-- ace styles -->

		<link rel="stylesheet" href="/assets/css/ace.min.css" />
		<link rel="stylesheet" href="/assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="/assets/css/ace-skins.min.css" />
		<link rel="stylesheet" href="/assets/css/dropzone.css" />
        <link rel="stylesheet" href="/assets/css/datepicker.css" />
        <link rel="stylesheet" href="/assets/css/bootstrap-timepicker.css" />
        <link rel="stylesheet" href="/vendor/js/select2/select2.css" />
        <link rel="stylesheet" href="/vendor/js/select2/select2-bootstrap.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="/assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->

		<script src="/assets/js/ace-extra.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="/assets/js/html5shiv.js"></script>
		<script src="/assets/js/respond.min.js"></script>
		<![endif]-->

		<!--[if !IE]> -->

		<script type="text/javascript">
			window.jQuery || document.write("<script src='/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='/assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if("ontouchend" in document) document.write("<script src='/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
		<script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/typeahead-bs2.min.js"></script>

		<!-- page specific plugin scripts -->

		<script src="/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
		<script src="/assets/js/jquery.ui.touch-punch.min.js"></script>
		<script src="/assets/js/markdown/markdown.min.js"></script>
		<script src="/assets/js/markdown/bootstrap-markdown.min.js"></script>
		<script src="/assets/js/jquery.hotkeys.min.js"></script>
		<script src="/assets/js/bootstrap-wysiwyg.min.js"></script>
		<script src="/assets/js/bootbox.min.js"></script>

		<!-- ace scripts -->

		<script src="/assets/js/ace-elements.min.js"></script>
		<script src="/assets/js/ace.min.js"></script>

		<!-- inline scripts related to this page -->
	</head>

	<body>
		<div class="navbar navbar-default" id="navbar">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-leaf"></i>
                            <?=$this->tag->_('EvaEngine');?>	
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">

						<li class="light-blue">
                        <?if(isset($authIdentity)):?>
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
                                <img class="nav-user-photo" src="<?=$this->tag->gravatar($authIdentity['email'])?>" alt="" />
								<span class="user-info">
									<small>Welcome,</small>
                                    <?=$authIdentity['username']?>
								</span>

								<i class="icon-caret-down"></i>
							</a>
                        <?endif?>

							<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                                <!--
								<li>
									<a href="#">
										<i class="icon-cog"></i>
										Settings
									</a>
								</li>

								<li>
									<a href="#">
										<i class="icon-user"></i>
										Profile
									</a>
								</li>
                                -->

								<li class="divider"></li>

								<li>
									<a href="/logout">
										<i class="icon-off"></i>
										Logout
									</a>
								</li>
							</ul>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
					</script>

					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<a class="btn btn-success" href="/admin/dashboard">
								<i class="icon-signal"></i>
							</a>

                            <a class="btn btn-info" href="/admin/post/create">
								<i class="icon-pencil"></i>
							</a>

                            <a class="btn btn-warning" href="/admin/user">
								<i class="icon-group"></i>
							</a>

                            <a class="btn btn-danger" href="#">
								<i class="icon-cogs"></i>
							</a>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
							<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->

					<ul class="nav nav-list">
						<li class="tobe-highlight" data-highlight-url="/admin/dashboard">
                        <a href="/admin/dashboard">
								<i class="icon-dashboard"></i>
								<span class="menu-text"> Dashboard </span>
							</a>
						</li>

						<li class="">
							<a href="#" class="dropdown-toggle">
								<i class="icon-edit"></i>
								<span class="menu-text"> Post </span>
								<b class="arrow icon-angle-down"></b>
							</a>

							<ul class="submenu">
								<li class="tobe-highlight" data-highlight-url="/admin/post.*">
                                <a href="/admin/post">
										<i class="icon-double-angle-right"></i>
                                        Post List
									</a>
								</li>

								<li class="tobe-highlight" data-highlight-url="/admin/post/create">
                                <a href="/admin/post/create">
										<i class="icon-double-angle-right"></i>
                                        Create New Post
									</a>
								</li>

                                <li class="tobe-highlight" data-highlight-url="/admin/category.*">
                                <a href="/admin/category">
										<i class="icon-double-angle-right"></i>
                                        Category List
									</a>
								</li>

                                <li class="tobe-highlight" data-highlight-url="/admin/post/tag">
                                <a href="/admin/tag">
										<i class="icon-double-angle-right"></i>
                                        Tags
									</a>
								</li>
							</ul>
						</li>

						<li>
							<a href="#" class="dropdown-toggle">
								<i class="icon-file"></i>
                                <span class="menu-text"> Media</span>

								<b class="arrow icon-angle-down"></b>
							</a>

							<ul class="submenu">
                                <li class="tobe-highlight" data-highlight-url="/admin/media.*">
									<a href="/admin/media">
										<i class="icon-double-angle-right"></i>
                                        Media List
									</a>
								</li>

								<li class="tobe-highlight" data-highlight-url="/admin/media/upload">
                                <a href="/admin/media/upload">
										<i class="icon-double-angle-right"></i> Upload
									</a>
								</li>
							</ul>
						</li>


						<li>
							<a href="#" class="dropdown-toggle">
								<i class="icon-user"></i>
								<span class="menu-text"> User </span>

								<b class="arrow icon-angle-down"></b>
							</a>

							<ul class="submenu">
                                <li class="tobe-highlight" data-highlight-url="/admin/user.*">
									<a href="/admin/user">
										<i class="icon-double-angle-right"></i>
                                        User List
									</a>
								</li>

                                <li class="tobe-highlight" data-highlight-url="/admin/user/permission">
									<a href="/admin/user/permission">
										<i class="icon-double-angle-right"></i>
                                        Permission
									</a>
								</li>
							</ul>
						</li>


					</ul><!-- /.nav-list -->

					<div class="sidebar-collapse" id="sidebar-collapse">
						<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
					</div>

					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
					</script>
				</div>

				<div class="main-content">
                    <?=$this->tag->flashOutput()?>
                    <?=$this->getContent()?>

				</div><!-- /.main-content -->


			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/parsley/parsley.remote.js"></script>
        <script src="/assets/js/parsley/parsley.js"></script>
        <script src="/assets/js/parsley/i18n/zh_cn.js"></script>
        <script type="text/javascript" src="/vendor/js/epiceditor/js/epiceditor.js"></script>
        <script type="text/javascript" src="/vendor/js/ckeditor/ckeditor.js"></script>
        <script type="text/javascript" src="/vendor/js/ckeditor/adapters/jquery.js"></script>
        <script type="text/javascript" src="/vendor/js/select2/select2.js"></script>
        <script type="text/javascript" src="/vendor/js/select2/select2_locale_zh-CN.js"></script>
        <script type="text/javascript" src="/vendor/js/jquery.noty.js"></script>
        <script type="text/javascript" src="/vendor/js/Uri.min.js"></script>
        <script src="/assets/js/bootstrap-tag.min.js"></script>
        <script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>
        <script src="/assets/js/date-time/bootstrap-timepicker.min.js"></script>
        <script src="/assets/js/dropzone.min.js"></script>
        <script src="/js/backend.js"></script>
		<script type="text/javascript">
		</script>
	</body>
</html>
