<link rel="stylesheet" href="/assets/css/datepicker.css" />
<link rel="stylesheet" href="/assets/css/bootstrap-timepicker.css" />

<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/post">Post</a>
        </li>
        <li class="active">Category</li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <!--
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
        -->
    </div><!-- #nav-search -->
</div>

<form id="" action="/admin/category/create" method="POST" enctype="multipart/form-data" novalidate="novalidate">
<div class="page-content">
    <div class="page-header">
        <h1>Create New Category</h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-9">
            <!-- PAGE CONTENT BEGINS -->

                <div class="form-group">
                    <label class="block clearfix">
                        <?=$form->render('categoryName', array(
                            'class' => 'form-control input-lg',
                            'placeholder' => 'Title',
                            'required' => 'required',
                        ))?>
                    </label>
                    <div class="input-group">
                        <span class="input-group-addon input-sm">
                            <i class="icon-link"></i>  http://www.goldtoutiao.com/admin/category/
                        </span>
                        <?=$form->render('slug', array(
                            'class' => 'form-control input-sm',
                            'placeholder' => 'Url, No fill will generate a random url',
                        ))?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="block clearfix">
                        <div id="epiceditor">
                            <?=$form->render('description', array(
                                'class' => 'form-control wysiwyg',
                                'rows' => 12,
                                'required' => 'required',
                            ))?>
                        </div>
                    </label>
                </div>

                <!--
                <div class="clearfix form-actions">
                    <button type="submit" class="btn btn-info">
                        <i class="icon-ok bigger-110"></i>
                        Submit
                    </button>
                </div>
            <div class="hr hr-double dotted"></div>
                -->
        </div><!-- /.col -->
        <div class="col-xs-3">

            <div class="widget-box">
                <div class="widget-header widget-header-small">
                    <h4>Publish</h4>
                    <span class="widget-toolbar">
                        <a data-action="collapse" href="#">
                            <i class="icon-chevron-up"></i>
                        </a>
                    </span>
                </div>
                <div class="widget-body">
                    <div class="widget-main">
                        <fieldset>
                        </fieldset>
                    </div>
                    <div class="clearfix form-actions no-margin">
                        <input type="hidden" name="__redirect" value="" />
                        <button type="submit" class="btn btn-info">
                            <i class="icon-save"></i>
                             Save
                        </button>
                        <button type="submit" class="btn btn-info" data-redirect-btn="/admin/category/create">
                            <i class="icon-ok"></i>
                            Save &amp; Add Another
                        </button>
                    </div>
                </div>
            </div><!--widgex box-->

            <div class="hr hr-double dotted"></div>
            <div class="widget-box">
                <div class="widget-header widget-header-small">
                    <h4>Image</h4>
                    <span class="widget-toolbar">
                        <a data-action="collapse" href="#">
                            <i class="icon-chevron-up"></i>
                        </a>
                    </span>
                </div>

                <div class="widget-body">
                    <div class="widget-main">
                        <input name="upload" type="file" id="id-input-file-3" multiple="">
                    </div>
                </div>
            </div><!--widgex box-->

            <div class="hr hr-double dotted"></div>
            <div class="widget-box">
                <div class="widget-header widget-header-small">
                    <h5 class="lighter">Parent</h5>
                    <span class="widget-toolbar">
                        <a data-action="collapse" href="#">
                            <i class="icon-chevron-up"></i>
                        </a>
                    </span>
                </div>
                <div class="widget-body">
                    <div class="widget-main">
                        <div class="control-group">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="ace" name="form-field-checkbox">
                                    <span class="lbl"> choice 1</span>
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="ace" name="form-field-checkbox">
                                    <span class="lbl"> choice 2</span>
                                </label>
                            </div>
                        </div>

                    </div>
                </div>
            </div><!--widgex box-->

        </div><!-- /.col -->

    </div><!-- /.row -->
</div><!-- /.page-content -->
            </form>

            <script type="text/javascript" src="/vendor/js/tinymce/jquery.tinymce.min.js"></script>
            <script type="text/javascript" src="/vendor/js/epiceditor/js/epiceditor.js"></script>
            <script type="text/javascript" src="/vendor/js/ckeditor/ckeditor.js"></script>
            <script type="text/javascript" src="/vendor/js/ckeditor/adapters/jquery.js"></script>
            <script src="/assets/js/bootstrap-tag.min.js"></script>
            <script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>
            <script src="/assets/js/date-time/bootstrap-timepicker.min.js"></script>
            <script src="/assets/js/dropzone.min.js"></script>
            <script type="text/javascript">
				$('#id-input-file-3').ace_file_input({
					style:'well',
					btn_choose:'Drop files here or click to choose',
					btn_change:null,
					no_icon:'icon-cloud-upload',
					droppable:true,
					thumbnail:'small'//large | fit
					//,icon_remove:null//set null, to hide remove/reset button
					/**,before_change:function(files, dropped) {
						//Check an example below
						//or examples/file-upload.html
						return true;
					}*/
					/**,before_remove : function() {
						return true;
					}*/
					,
					preview_error : function(filename, error_code) {
						//name of the file that failed
						//error_code values
						//1 = 'FILE_LOAD_FAILED',
						//2 = 'IMAGE_LOAD_FAILED',
						//3 = 'THUMBNAIL_FAILED'
						//alert(error_code);
					}
			
				}).on('change', function(){
					//console.log($(this).data('ace_input_files'));
					//console.log($(this).data('ace_input_method'));
				});
                var editor = new EpicEditor({
                        autogrow : {
                                minHeight : 200,
                                maxHeight : 300
                        },
                        theme: {
                                base: 'http://www.goldtoutiao.com//vendor/js/epiceditor/themes/base/epiceditor.css',
                                preview: 'http://www.goldtoutiao.com/vendor/js/epiceditor/themes/preview/bartik.css',
                                editor: 'http://www.goldtoutiao.com/vendor/js/epiceditor/themes/editor/epic-light.css'
                        },
                        button: {
                                preview: false,
                                fullscreen: true,
                                bar: "auto"
                        },
                        string: {
                                togglePreview: '预览(快捷键Alt+p)',
                                toggleEdit: 'Toggle Edit Mode',
                                toggleFullscreen: '全屏(快捷键Alt+f)'
                        },


                }).load();

				$('.date-picker').datepicker({autoclose:true}).next().on(ace.click_event, function(){
					$(this).prev().focus();
				});
				$('#timepicker1').timepicker({
					minuteStep: 1,
					showSeconds: true,
					showMeridian: false
				}).next().on(ace.click_event, function(){
					$(this).prev().focus();
                });

				//we could just set the data-provide="tag" of the element inside HTML, but IE8 fails!
				var tag_input = $('#form-field-tags');
				if(! ( /msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase())) ) 
				{
					tag_input.tag(
					  {
						placeholder:tag_input.attr('placeholder'),
						//enable typeahead by specifying the source array
						source: ace.variable_US_STATES,//defined in ace.js >> ace.enable_search_ahead
					  }
					);
				}
				else {
					//display a textarea for old IE, because it doesn't support this plugin or another one I tried!
					tag_input.after('<textarea id="'+tag_input.attr('id')+'" name="'+tag_input.attr('name')+'" rows="3">'+tag_input.val()+'</textarea>').remove();
					//$('#form-field-tags').autosize({append: "\n"});
				}

                $(window).on("paste", function(e){
                        if(!e || !e.originalEvent || !e.originalEvent.clipboardData) {
                                return;
                        }
                        console.log(e);
                        var items = e.originalEvent.clipboardData.files,
                        i = 0,
                        item;
                        for(i in items) {
                                item = items[i];
                                if(item.type && item.type.match(/^image\//i)) {
                                        console.log(item);

                                        //var blob = item.getAsFile();
                                        var reader = new FileReader();
                                        reader.onload = function(event){
                                                console.log(event.target.result);
                                                $('#epiceditor').after('<img src="' + event.target.result + '" alt="">');
                                        }
                                        reader.readAsDataURL(item); 


                                }
                        }
                });


            </script>


