<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/post">Post</a>
        </li>
        <li class="active">Write New Post</li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<form id="" action="" method="POST" enctype="multipart/form-data" novalidate="novalidate">
    <div class="page-content">
        <div class="page-header">
            <h1>Write New Post</h1>
        </div><!-- /.page-header -->

        <div class="row">
            <div class="col-xs-9">
                <!-- PAGE CONTENT BEGINS -->

                <div class="form-group">
                    <label class="block clearfix">
                        <?=$postForm->render('title', array(
                            'class' => 'form-control input-lg',
                            'placeholder' => 'Title',
                            'required' => 'required',
                        ))?>
                    </label>
                    <div class="input-group">
                        <span class="input-group-addon input-sm">
                            <i class="icon-link"></i>  http://www.goldtoutiao.com/admin/category/
                        </span>
                        <?=$postForm->render('slug', array(
                            'class' => 'form-control input-sm',
                            'placeholder' => 'Url, No fill will generate a random url',
                        ))?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="block clearfix">
                        <div id="epiceditor">
                            <?=$textForm->render('content', array(
                                'class' => 'form-control ',
                                //'class' => 'form-control wysiwyg',
                                'rows' => 12,
                                'required' => 'required',
                            ))?>
                        </div>
                    </label>
                </div>

                <!--
                <div class="clearfix form-actions">
                    <button type="submit" class="btn btn-info">
                        <i class="icon-ok bigger-110"></i>
                        Submit
                    </button>
                </div>
                <div class="hr hr-double dotted"></div>
                -->
            </div><!-- /.col -->
            <div class="col-xs-3">

                <div class="widget-box">
                    <div class="widget-header widget-header-small">
                        <h4>Publish</h4>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
                    </div>
                    <div class="widget-body">
                        <div class="widget-main">
                            <fieldset>
                                <?=$postForm->render('status', array(
                                    'class' => 'form-control',
                                ))?>
                            </fieldset>


                        </div>
                        <div class="clearfix form-actions no-margin">
                            <button type="submit" class="btn btn-info">
                                <i class="icon-ok"></i>
                                Publish
                            </button>
                        </div>
                    </div>
                </div><!--widgex box-->

                <div class="hr hr-double dotted"></div>
                <div class="widget-box">
                    <div class="widget-header widget-header-small">
                        <h4>Image</h4>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
                    </div>

                    <div class="widget-body">
                        <div class="widget-main">
                            <input name="upload" type="file" class="ace-file-input" multiple="">
                        </div>
                    </div>
                </div><!--widgex box-->

                <div class="hr hr-double dotted"></div>
                <div class="widget-box">
                    <div class="widget-header widget-header-small">
                        <h5 class="lighter">Categories</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
                    </div>
                    <div class="widget-body">
                        <div class="widget-main">
                            <div class="control-group">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" class="ace" name="form-field-checkbox">
                                        <span class="lbl"> choice 1</span>
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" class="ace" name="form-field-checkbox">
                                        <span class="lbl"> choice 2</span>
                                    </label>
                                </div>
                            </div>

                        </div>
                    </div>
                </div><!--widgex box-->


                <div class="hr hr-double dotted"></div>
                <div class="widget-box">
                    <div class="widget-header widget-header-small">
                        <h5 class="lighter">Tags</h5>
                        <a data-action="collapse" href="#">
                            <i class="icon-chevron-up"></i>
                        </a>
                    </div>

                    <div class="widget-body">
                        <div class="widget-main">
                            <div class="form-group">
                                <input type="text" placeholder="Enter Tags ..." value="" name="tags" class="tag-input">
                            </div>
                        </div>
                    </div>
                </div><!--widgex box-->

                <div class="hr hr-double dotted"></div>
                <div class="widget-box">
                    <div class="widget-header widget-header-small">
                        <h5 class="lighter">Publish Time</h5>
                        <a data-action="collapse" href="#">
                            <i class="icon-chevron-up"></i>
                        </a>
                    </div>

                    <div class="widget-body">
                        <div class="widget-main">
                            <div class="input-group">
                                <input name="day" type="text" data-date-format="yyyy-mm-dd" class="form-control date-picker">
                                <span class="input-group-addon">
                                    <i class="icon-calendar bigger-110"></i>
                                </span>
                            </div>
                            <div class="input-group bootstrap-timepicker">
                                <input type="text" class="form-control time-picker">
                                <span class="input-group-addon">
                                    <i class="icon-time bigger-110"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div><!--widgex box-->

            </div><!-- /.col -->

        </div><!-- /.row -->
    </div><!-- /.page-content -->
</form>
